app/src/main/java/org/kiwix/kiwixmobile/library/LibraryAdapter.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.java
When going from no filters to any filter the app would crash, because the
filteredBooks list would be set to the immutable allBooks and couldn't be
cleared anymore. Instead do a deep copy of the elements.
Also some minor fixes (typos, style).
=> Fix language selector crash.

app/src/main/java/org/kiwix/kiwixmobile/library/LibraryAdapter.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.java, app/src/main/res/layout/language_check_item.xml
Shows the name of the language in that language for each choice in the
picker. Also shows number of matching items for that language.
A bit of refactoring, cleaning up the language population logic. Fixes
bug where after the initial language population & persisting no new
languages would be populated (if new item with that lang got downloaded).
=> Add localized language and matching item count to language picker.

app/build.gradle, templates/Constants.java
By default, literal numbers are `int`. If the size of a zim doesn't fit in
a `int`, java will complains.
By appending a `L` at the end of the literal number, java will interpret
it as a `long` and will accept it.
=> Force ZIM_FILE_SIZE literal to be a long.

app/src/main/java/org/kiwix/kiwixmobile/ZimContentProvider.java
Instead of directly copying "icudt.dat" file, copy all file in "icu"
assets directory.
The icu data filename must include the version of icu lib.
But we don't want android code to be dependent of the icu lib version.
So let's copy all files in the icu directory.
Fixes #201.
=> Don't assume about icu data filename.

app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/tests/DownloadTest.java, app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/tests/NetworkTest.java, app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/tests/ZimTest.java, app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/utils/StandardActions.java
The tests passed on devices that didn't have a hardware menu key but failed on those that did. 
Espresso contains two similar calls to launch the menu. Either are OK on devices that don't have a menu key (the vast majority of devices) so this bug was latent until I tested on a wider mix of devices.
See
https://developer.android.com/training/testing/espresso/recipes.html#matching-view-inside-action-bar
and keep reading until you reach the example for "contextual action
bar".
See #213 for the
historical context where this problem was initially exposed. It took
working with Isaac in person for us to discover the cause.
=> Fixed a hard to find quirk where the tests failed on devices with a hardware menu key

app/build.gradle, app/src/main/java/org/kiwix/kiwixmobile/di/modules/NetworkModule.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryPresenter.java
This is the initial skeleton that proves the approach can work. Future work will enable us to control whether to fully mock network operations, have a local download server, or use the public Kiwix download server.
=> Added two build variants to help us control the scope of our testing of network operations.

app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/tests/ZimTest.java
`@SdkSuppress` enables us to cleanly control whether to run a test or not. It's simple to use and works well.
=> Now using @SdkSuppress

app/build.gradle, app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/tests/DownloadTest.java, app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/tests/ZimTest.java, build.gradle
Once we are happy with using Spoon we can add code that automatically
takes a screenshot when tests fail. This may help us debug some of the
problems we encounter running the tests on various devices. Using Spoon
exposed a limitation/key behaviour of ActivityTestRule that references
the intended Activity under test. To account for this behaviour I
restructured DownloadTest so it simply tests the download, rather than
reading the contents of the file.
I also discovered that the tests would fail on wide-screens as the Home
menu option moves from the overflow menu to the main menu. I've modified
one test to cope. Again, once we're happy with this approach (which
involves a little extra code) we can revise all the tests so they can
run equally competently on various screen sizes.
=> The main change is to add support for Spoon to take screenshots.

app/build.gradle
Test if the zim_file path is existing. If yes, it is used as it is.
If not, we assume it is a local path relative to the custom directory
(as before).
This is needed to be able to custom app with embedded zims.
=> Support absolute path when specifying zim_file in info.json for custom app

app/build.gradle, build.gradle
I was irked by having a compile dependency on a testing library. 
Addressing the cause took several hours, it seemed to be there to address other side-effects. In the end I discovered we had incompatible library versions which weren't reconciled by Gradle unless the extraneous dependency was there.
The error was described in https://sites.google.com/a/android.com/tools/tech-docs/new-build-system/user-guide#TOC-Resolving-conflicts-between-main-and-test-APK
The resolution was to align the version numbers for various Android support libraries to a common value: 25.4.0 for now although there are newer versions so we might want to migrate to the current releases soon. I applied the concepts others use, which is to specify the version once
and use it throughout, see …
=> Cleaning up gradle dependencies and versions.

app/build.gradle, app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/tests/KiwixMobileActivityTest.java, app/src/main/java/org/kiwix/kiwixmobile/di/modules/NetworkModule.java
Added limited (basic) Http request and response logging to augment the current logging used in the DownloadService. Hopefully the extra log messages will help us debug problems when tests fail, particularly remotely e.g. on BitBar's TestDroid service.
I've used the packaged Logging Interceptor https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor configured as a network level interceptor https://github.com/square/okhttp/wiki/Interceptors 
The logs are local to the device and don't contain any sensitive additional information. The extra information helps diagnose network issues when they occur during testing.
PS: I noticed that the logs don't necessarily report the end of the zim file download. We can infer this from the following log message …
=> Added limited (basic) Http logging to help us diagnose network issues

app/src/main/java/org/kiwix/kiwixmobile/library/LibraryAdapter.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.java
A sample library_zim.xml is available at
https://github.com/kiwix/testfiles/blob/master/libraryfiles/one_item_in_library/library_zim.xml
The bug seems to have been introduced inadvertently in
https://github.com/kiwix/kiwix-android/commit/b9930252e1a540366d7ecae5e0336a22497bc92c
which returned a null to `getView(...)`
I've left a key log statement as this was one clue (after checking
various other areas of the codebase) that indicated there might be a
problem related to the number of entries rather than the attributes of
the item. I aim to revise the format of the log message as part of a
wider update on logging.
=> Bug fix for #320 triggered when the library contained 1 item.

app/build.gradle
Tested locally using a Raspberry Pi with the new hostname `kiwix-download-server`
=> Replaced hardcoded URL with hostname to make tests more portable.

app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java
It looks like this has been forgotten at the time the whole stuff as been migrated (to gradle if I correctly remember).
=> 'Get content' menu entry should be masked in custom apps #341

app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryViewCallback.java, app/src/main/res/values/strings.xml
Tested locally using a web server to return this empty XML file:
```
<?xml version="1.0" encoding="UTF-8"?>
<library>
</library>
```
Signed-off-by: David Sn <divad.nnamtdeis@gmail.com>
=> Show "no items available" if returned library XML is empty

app/src/main/java/org/kiwix/kiwixmobile/ZimContentProvider.java
Zim files now open according to the one being clicked.
Fixes #236 
Changes: Just changed a single line. Previously, only for the first time the file being clicked was opened and after that it was opening the same file.
=> Fixed zim file not opening issue.

README.md, docs/codestyle.md, docs/commitstyle.md
Fixes #419 
Changes: Improved the README of the project by adding various informations.
Screenshots/GIF for the change: NA
To check the final rendered README, please switch to ```srv-twry/improvereadme``` branch.
@mhutti1 Can you suggest what to do with the ```Legal and Disclaimer``` section. It looks weird. I couldn't find the "COPYING" file.
=> chore: Improve the README of the project

app/src/main/res/layout/zim_list.xml
Fixes #472 
Changes: Fix text visibility in night mode in library screen.
=> Fix text visibility in library screen in dark mode

app/src/main/res/layout/language_check_item.xml, app/src/main/res/values/dimens.xml
=> Language name overlap resolved

app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java
Fixes #569.
Changes: Implemented the back button action using `onKeyDown()` to support going back till the parent WebView and then exit the full-screen.
Screenshots/GIF for the change: Attached in the issue itself.
=> Fix: App minimizing on back pressed in fullscreen mode

app/src/main/java/org/kiwix/kiwixmobile/utils/NetworkUtils.java
Fixes #345 
Changes: Added checks to avoid runtime exception.
=> Avoid StringIndexOutOfBoundsException in Content search

app/build.gradle
Fixes #664
Changes: Use leak canary stub by default. Switch out for debug.
=> Add leak canary stub as a dependency for all builds by default

app/src/main/java/org/kiwix/kiwixmobile/TableDrawerAdapter.java, app/src/main/java/org/kiwix/kiwixmobile/utils/DocumentParser.java
Fixes #691 
Changes: Minor change made so that the right drawer's adapter doesn't get previous value of content header if it doesn't exist in the current article.
=> Fix Content Header stale value bug

gradle/wrapper/gradle-wrapper.properties
In addition to #518
Changes: Update the Gradle version to `4.6`. If we are going to use the latest, why not the best? Pros can be found [here](https://docs.gradle.org/4.6/release-notes.html?_ga=2.267775561.670026300.1523168361-990718775.1522529703). Tested and verified.  
=> Improve: Update Gradle version

app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadService.java, app/src/main/java/org/kiwix/kiwixmobile/utils/Constants.java, app/src/main/res/values/strings.xml
First steps for issue #702.
Changes: Added a notification channel named "Ongoing Downloads".
Pending Tasks:
This will be beneficial as user can then change the settings for these notifications independently. For e.g. - A user may choose to increase the _importance_ (or _priority_) of the "zim downloaded notification" so that he/she gets a [Heads-up notification](https://developer.android.com/guide/topics/ui/notifiers/notifications.html#Heads-up) for the download complete event.
Screenshots/GIF for the change: 
Kiwix Notification is now visible in the notification drawer.
App settings screen for notification channel.
=> [WIP] Added ongoing downloads notification channel

app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.java
Fixes #600 
Changes: Added unregisterReceiver() in LibraryFragment to stop the crash.
=> Unregister Receiver

app/src/main/java/org/kiwix/kiwixmobile/utils/NetworkUtils.java
A minor fix that was uncovered by running our automated tests on devices without an internet connection (but WiFi had networks available).
I mimiced the behaviour of the lines earlier in the method. It might be worth revising the code soon as it's not entirely accurate these days.
Fixes #722
=> Fixing a NPE in isWiFi

app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java
Fixes #672 
Changes: Implemented the back button action using `onKeyDown()` to close the `ActionMode` of `Find in page`. 
Screenshots/GIF for the change: Attached in the issue itself.
=> Fix: App directly minimizes on back pressed in Find in page

app/src/main/java/org/kiwix/kiwixmobile/library/LibraryAdapter.java
Fixes #694 
Changes: Temporarily removes stack exchange zim files from the remote library.
=> Remove stack exchange zim files from remote library

app/src/main/java/org/kiwix/kiwixmobile/utils/SplashActivity.java
Work on #615
Changes: Error activity create uses application context rather than splash activity context that should be destroyed after use.
=> Update error activity create to use application context

app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/tests/BasicTest.java, app/src/main/java/org/kiwix/kiwixmobile/TableDrawerAdapter.java
Work on #620 
Changes: Use page title as table of contents header if h1 is not set.
=> Use page title as toc header if h1 is not used

app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java, app/src/main/java/org/kiwix/kiwixmobile/database/BookmarksDao.java, app/src/main/java/org/kiwix/kiwixmobile/database/KiwixDatabase.java, app/src/main/java/org/kiwix/kiwixmobile/utils/Constants.java, app/src/main/java/org/kiwix/kiwixmobile/utils/UpdateUtils.java
Fixes #706 
Changes: Correctly updates URL paths from org.kiwix.zim.base to the correct app specific path.
=> Fix provider domain when updating from 2.2

app/src/main/java/org/kiwix/kiwixmobile/downloader/ChunkUtils.java, app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadService.java, app/src/main/java/org/kiwix/kiwixmobile/utils/files/FileUtils.java
Fixes #355 
Changes:
1. Changed code to accommodate the new `.part.part` scheme in `DownloadService#downloadChunk`. Now it changed `.part.part` -> `.part`
2. Added code to remove the `.part` from chunks after the entire book has finished downloading.
3. Changed file removal methods to take into consideration the new naming scheme in  `FileUtils`.
=> Separate partially downloaded zim files until download finishes. 

app/src/main/res/values/strings.xml
The string 'help_1' on the help screen was changed from:
"x allows you offline access to websites such as Wikipedia in a highly compressed form."
to
"Kiwix gives you offline access to websites such as Wikipedia in a highly compressed form."
=> fix string on help screen

app/src/main/java/org/kiwix/kiwixmobile/help/HelpActivity.java
Fixes #810 
Changes: 
The Intent structure was changed. The intent action is now ACTION_SENDTO instead of ACTION_SEND. Using this intent action, putExtra does not work. Therefore Uri has been used to add the email id , and the subject to the email.
=> Fix intent on help Screen

app/src/main/res/values/styles.xml
Changes: 
added the **buttonBarNeutralButtonStyle** item to the style **AppTheme.Dialog.Night** and set it to **@color/accent**.
Before:
After:
=> Fix Color Scheme in external link dialog box in night mode

app/build.gradle
Wow, this 1 line change was painful to discover and apply. Many of the
details are in https://github.com/kiwix/kiwix-android/issues/836
NB: We've still to arrange and enable code coverage to be generated in
the CI process.
First steps for issues #836 We then need to decide and agree how to generate coverage as part of the build process.
Changes: enabled coverage to be a target for running the tests.
=> Got Code Coverage Reports working while preserving dev debugging!

app/build.gradle, build.gradle
Closes #879
Changes: Place `google()` as the first priority repository in `build.gradle` files
=> Place `google()` as the first priority repository

app/src/main/java/org/kiwix/kiwixmobile/settings/SliderPreference.java
Fixes #914 
Changes: Added variable to keep track of initial seekBar value and reset seekBar value when zoom change is cancelled.
=> Added variable to keep track of initial seekBar value

app/src/main/java/org/kiwix/kiwixmobile/main/BooksAdapter.java, app/src/main/java/org/kiwix/kiwixmobile/main/KiwixWebView.java, gradle.properties
Fixes #905 
Changes: 
- Since this home page is actually within a web view and not a regular activity, the colour inversion for its night-mode is handled like that for other web pages - Complete inversion (by the GPU) of the screen currently being rendered
- This PR checks if the night-mode is enabled, and then renders inverted icons for the books list - which get inverted again by the GPU to give original colours
Screenshots/GIF for the change: <p align="center">
</p>
=> Fix Bug #905: Launch activity (night-mode) inverts colour of icons

app/src/main/java/org/kiwix/kiwixmobile/settings/KiwixSettingsActivity.java, app/src/main/res/anim/fade_in.xml, app/src/main/res/anim/fade_out.xml
Right now we are using slide animations all throughout the app. However for mode change (from light to dark, and vice versa), the fade transition should be a much better option.
1. Created the *res/anim* resource directory to store animation resource xml files.
2. Created two animation resource xml files to store the fade in and out animations in *fade_in.xml* and *fade_out.xml* respectively.
3. Implemented `overridePendingTransitions()` (in the *KiwixSettingsActivity.java* file) when the `PREF_NIGHTMODE` and `PREF_AUTONIGHTMODE` keys are changed. 
@siddharth2010 :)
=> Fix night-mode transitions

.editorconfig
checked the formatting now better, SquareAndroid uses continuation-indent
=> add continuation_indent_size to editorconfig, SquareAndroid has it.

app/build.gradle, app/src/androidTest/java/org/kiwix/kiwixmobile/data/local/KiwixDatabaseTest.java, app/src/androidTest/java/org/kiwix/kiwixmobile/testutils/TestUtils.java
* In build.gradle. I added.
When you're using Android X you need to make sure you have the following in your app's build.gradle file.
androidTestImplementation "androidx.test.ext:junit:1.1.0"
androidTestImplementation 'androidx.test:core:1.1.0'
* In KiwixDatabaseTest.java
I added import androidx.test.platform.app.InstrumentationRegistry because it is the latest class according to Android Developers documentation
Reference: https://developer.android.com/reference/androidx/test/platform/app/InstrumentationRegistry#getInstrumentation()
* Same was done in the TestUtils.java class and method calls are made accordingly.
=> Fixes#943 Resolving Deprecated API Usage

app/src/main/res/values/styles.xml
Fixes Issue #913 
Changes: The dialog width was set to 95% of screen width and the styles for light theme were modified.
=> Alert Dialogs made uniform in both modes

app/src/main/res/layout/download_management.xml
In downloading fragment the last image is not fully
visible #954
Changes: Add padding in Downloading Fragment.
=> In downloading fragment the last image is not fully visible #954

app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadFragment.java, app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadService.java, app/src/main/java/org/kiwix/kiwixmobile/library/LibraryAdapter.java, app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryPresenter.java
Fixes #538 @GeVic comment.
Changes: [Add here what changes were made in this issue and if possible provide links.]
Use Fragment methods onSaveInstanceState and onViewStateRestored to reload the books. Now the app don't use Internet every time the user rotates the device. As you can see on the GIF the reload is quite faster.
=> Saving time and resources when list reload in Library

app/src/main/AndroidManifest.xml, app/src/main/res/xml/network_security_config.xml
Fixes #993 
Changes: Adds kiwix.org the the network cleartext whitelist
=> Allow cleartext for kiwix.org

app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadService.java
* Using bundle, adding Extras to each notification object.
* In the extras, adding notificationTitle for each object.
* Then getting the notificationTitle for each notification using Bundle.
* Displaying the notificationTitle for each notification accordingly.
=> Fixed Multiple Files Download Results in Wrong Content Title In The Notification

app/src/main/java/org/kiwix/kiwixmobile/main/TabsAdapter.java
* Add an else if statement to check if the webViewTitle contains the URI
* Set the webViewTitle to "Home"
=> Fix Incorrect Tab headings in tab overview after deleting all zim files

app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadService.java, app/src/main/res/values/strings.xml
* add Resume string value
* add this label to the download notification label instead of PLAY.
=> <Fixes#967> Fix button names in download notification

app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadService.java
* Set some dummy action on the Intent, otherwise extras are dropped. For example
```
intent.setAction(Long.toString(System.currentTimeMillis())) 
```
* And using 
``` FLAG_ONE_SHOT ```
instead of
``` PendingIntent.FLAG_CANCEL_CURRENT ```
**REFERENCE:**  [Stackoverflow](https://stackoverflow.com/questions/3168484/pendingintent-works-correctly-for-the-first-notification-but-incorrectly-for-the)
=> Fixed Pending Intent For Multiple Download Notifications 

app/src/main/java/org/kiwix/kiwixmobile/settings/SliderPreference.java
Zoom level option color should be grayed when disabled #556 
=> Zoom level option color should be grayed when disabled #556

app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.java
Fixes #1019 
Changes: 
1. When files are selected on long press, swipeRefreshLayout is disabled.
2. It is enabled back when CAB disappears.
=> SwipeLayout disabled after long press 

build.gradle.kts, gradle.properties
byte-buddy is a mockito dependency. it introduced java modules, and
jetifier cannot deal with it.  disable jetifying at the moment, as
suggested after considering:
https://stackoverflow.com/questions/52816022/failed-to-resolve-variable-project-groupid
https://issuetracker.google.com/issues/119135578#comment5
https://github.com/raphw/byte-buddy/issues/541
@mhutti1 this feature is experimental again, hope is ok.
Fixes #950
=> upgrade mockito, disable jetifying byte-buddy

app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java
Fixes #891 #895 
Issues #891 and #895 have a common root to callbacks which gives NullPointerExceptions.
Changes:
1. Added a function named CheckNull. 
2. CheckNull checks for NullPointerException for views in MainActivity.
=> Fixes NullPointerExceptions due to callbacks in MainActivity

app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java
Fixes #1034
* Add a method to check if there are zero tabs.
* Call the method where required.
* Time of 1500ms removed.
* Now, when the user closes the last opened tab or tries to close all tabs at once using the CloseAllTab Floating Action Button, the default tab("HOME PAGE") opens immediately.
=> Fixes Access A Deleted File After Closing All Tabs

app/src/main/res/layout/item_book.xml
Text begins cut by the right edge on Home screen #968 
=> Text begin cut by the right edge on Home screen #968

app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java
Fixes #1051 
Changes: 
1. Added below line in onCreate in MainActivity which will block its descendants from receiving focus.
*drawerLayout.setDescendantFocusability(ViewGroup.FOCUS_BLOCK_DESCENDANTS);*
=> Closes opened table drawer on first back press

app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java
Fixes #1049
Changes: 
Now, the tab switcher would close and user would be taken to the previously open tab when the tab switcher button is clicked again.
GIF for the change:
=> Close tab switcher on clicking again

app/build.gradle, app/src/main/java/org/kiwix/kiwixmobile/KiwixApplication.java, app/src/main/java/org/kiwix/kiwixmobile/history/HistoryAdapter.java, app/src/main/res/values/strings.xml, kiwixlib/build.gradle
Fixes #949 
* In the HistoryAdapter.java, before setting text, I get today's date, format it, convert it into a string.
* Then compare it with the history dates, if it's Today's date, "Today" should be written.
* Similarly, I implement a logic to get yesterday's date.
* And then compare it with History dates.
* Used Java 8's classes LocalDate which works for API 26 and onwards.
* Added JakeWharton's ABPThreeTen For BackwardCompatibility before API 26.
[ThreeTenAbp JakeWharton](https://mvnrepository.com/artifact/com.jakewharton.threetenabp/threetenabp)
* Hence, I had to increase the minSdkversion to 15 as it doesn't works with 14.
[Android versions](https://en.wikipedia.org/wiki/Android_version_history) Suggests this should be safe.
* I've tested this on both API>=26 and API<26 and it's …
=> Added 'Today' and 'Yesterday' instead of specific dates in History

.travis.yml
Changes: To enable automatic publishing on tagging we must enable the option "build pushed branches" on travis, however we don't want every pushed banch to be built, only the tags.
=> Prevent builds of pushed branches unless it is a tag

CONTRIBUTING.md
Fixes #1200 
Changes: addition of paragraph to CONTRIBUTING.md
=> #1200 explain how the branching model will work post 2.5

.github/stale.yml
Fixes #1226 
Changes: Stalebot will mark issues with 60 days inactivity with the label `stale`
=> #1226 create stalebot configuration

app/src/main/java/org/kiwix/kiwixmobile/data/ZimContentProvider.java, app/src/main/java/org/kiwix/kiwixmobile/main/AddNoteDialog.java, app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java, app/src/main/java/org/kiwix/kiwixmobile/utils/AnimationUtils.java, app/src/main/res/drawable/ic_close_black_24dp.xml, app/src/main/res/layout/tab_switcher.xml
**Fixes:** Previously file storage in [feature/NoteKeeper](https://github.com/kiwix/kiwix-android/pull/1198) used the zim file title to name the directory for notes corresponding to a particular zim file; which is not unique for each zim file.
Commits in this PR correspond to:
1. Changing that path to `.../Kiwix/Notes/ZimFileName/ArticleUrl.txt` (previously ".../Notes/ZimFileTitle/ArticleTitle.txt")
2. Bug relating to the use of resource close icon - [Commit](https://github.com/kiwix/kiwix-android/commit/865b579057692f3165645f1f5b98ad31b88e9c1b)
@mhutti1 @macgills could you review this?
=> Addition to #1198

app/src/main/java/org/kiwix/kiwixmobile/main/AddNoteDialog.java, app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java
Fixes #1302 
Changes: Added a check in `onCreate()` of Add Note Dialog for fresh installs (with no zim file opened previously)
=> Hotfix: Add "no zim open" check for Add Note Dialog in case of fresh install

app/src/main/java/org/kiwix/kiwixmobile/utils/files/FileUtils.kt
Fixes #1361 
Changes: Breaking a line to adhere to the line length in the code style meant interpolation was broken for 1 file separator
=> #1361 Custom app cannot find contents bug

app/build.gradle
=> #1259 Allow a local kiwix-lib aar to be used

app/src/main/java/org/kiwix/kiwixmobile/main/KiwixWebViewClient.java, app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java
See https://github.com/kiwix/kiwix-android/issues/1364 for details.
Fixes #1364 
Changes: 
- Extracted the code for reading content for custom apps into a separate method.
- Added logic to stop doing irrelevant steps when the content isn't there, as the app isn't going to work without the content
- Added additional ugly logic in the WebView to stop it trying to load content when there's none available in a custom app. This stops the app from crashing because various assumptions e.g. that there's a page to add to the History don't hold true when there's no content... (see logcat output added to the issue).
=> Fix for a bug that affects custom apps missing their contents.

app/src/main/AndroidManifest.xml
See https://github.com/kiwix/kiwix-android/issues/1370 for details.
Fixes #1370 
Changes: Added the MONKEY category to the launcher activity so Android Monkey can be configured to target it rather than targetting the LAUNCHER category (which causes it to also call the LAUNCHER added by LeakCanary as part of the build process).
I have built and tested a Custom app (PhET) and Kiwix using Monkey and all seems to work well.
=> Added MONKEY property which facilitates testing using Android Monkey.

app/src/main/java/org/kiwix/kiwixmobile/database/newdb/dao/NewBookmarksDao.kt
Fixes #1323
Changes: We fetch bookmarks by name instead of id
=> #1323 Bookmarks are not permanent over ZIM files update

app/src/main/AndroidManifest.xml
Fixes #681 easily sets round icon in APIs which require them.
=> #681 specify round icon in Android manifest

.idea/codeStyles/Project.xml, app/src/main/res/layout/activity_library.xml, app/src/main/res/layout/layout_download_management.xml, app/src/main/res/layout/zim_list.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/styles.xml
Fixes #390 
Changes: Fixed text inconsistency across the Device, Online and Downloading screens by changing the corresponding xml files.
=> removing text inconsistency

app/src/main/java/org/kiwix/kiwixmobile/utils/AlertDialogShower.kt
Fixes #430
Changes: Use AndroidX Dialog instead of the standard
=> #430 Inappropriate dialog box in downloading fragment - use androidX

app/src/main/java/org/kiwix/kiwixmobile/utils/files/FileUtils.kt
Fixes #1445
Changes: null was being returned to a non nullable type, now that type is nullable (inferred from the function return type)
=> #1445 stop crash on null return

app/build.gradle
Attempt to fix quickly #1410. App was failing to install on hdpi emulators. We will need to supply the missing resources for the respective densities, will be solved by #1274
=> Disable density splits

app/src/main/java/org/kiwix/kiwixmobile/database/newdb/dao/FetchDownloadDao.kt, app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloaderImpl.kt
Fixes #1471 
Changes: Use transaction to disallow the adding of a download that already exists
=> #1471 run download insertion inside transaction

README.md
chat on freenode duplicates chat public badge.
=> Remove duplicate badge from README.md

CONTRIBUTING.md
As zsh shows 'zsh: no matches found:' when checking out a branch with a # in it
=> Remove hash from branch naming convention

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java
=> #1656 Crash Report 3.1.2: NPE CoreMainActivity.hideTabSwitcher mainMenu

core/src/main/java/org/kiwix/kiwixmobile/core/history/HistoryActivity.java, core/src/main/res/layout/activity_history.xml, core/src/main/res/menu/menu_history.xml, core/src/main/res/values/dimens.xml, core/src/main/res/values/strings.xml
Fixes #1058 
Made the following changes in the menu of the history section:
- Removed the menus
- Created an icon in the top bar to enable/disable the display of all (versus current) book/tab history
- Replace the 3 dots menu with a simple trash icon. The click on trash deletes what is displayed.
=> #1058 Revamp the menu of the History Activity

core/src/main/res/values-night/color.xml, core/src/main/res/values/colors.xml
Fixes #1748 
In low brightness the text are now readable.
Material colors have been used under the WCAG AA/AAA guidelines.
* changed `blue800` for dark theme to `blue400` (improved contrast ratio 6.08:1 )
* changed color_surface to `grey900` from` #121212`(hexcode) 
* changed color_error to `pink300` from `#cf669`(hexcode) (contrast ratio 5.26:1 )
Real images(sorry for bad quality)
=> Improve problems with low contrast text  in dark mode

core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ImageViewExtensions.kt
Fixes #1709 
The tag condition while setting the icon has been removed for proper changing of icons. Now when an item is selected or unselected in the bookmarks or history activity, the icon is changed properly.
=> #1709 Change icon of history and bookmarks items on selection and unselection

core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.java
Linked issue #1510
I added checks to see if the voice that is going to be used is available on the device or needs downloading.
if it is not available a toast informing the user that the voice needs downloading appears. if Google TTS engine is used it will automatically download the voice whenever Wifi is available.
There is a scenario where tts object adds a language `tts.setLanguage(locale);` but tts is not used again. Should I do something about this ?
=> Add voice data checks for Read Aloud

.idea/inspectionProfiles/kiwixAndroidInspections.xml, buildSrc/src/main/kotlin/plugin/AllProjectConfigurer.kt
Fixes #1272
Managing or fixing MissingTranslations on our side is not feasible. As such it is marked a warning and can be listed by running lint/inspections should the list ever need to be created
=> #1272 Lint Issue: MissingTranslation - make MissingTranslation a warning

README.md
Fixes #1799 
Updated README with Slack badge and Slack invite details.
=> #1799 Update README with slack details

core/src/main/res/layout/item_help.xml, core/src/main/res/values/colors.xml
Fixes #1792 
Changed the color of the arrow next to help questions to grey so that it is visible in the light as well as dark mode. 
=> Fix #1792 Change color of arrow to be grey 

README.md
Fixes #1794 
Highlighted a portion in the readme to make it clear that the project has to imported and built instead of opening it the regular way.
=> Fix #1794 Improve README instructions about project import

core/src/main/java/org/kiwix/kiwixmobile/core/bookmark/BookmarksActivity.java, core/src/main/java/org/kiwix/kiwixmobile/core/di/components/CoreActivityComponent.kt, core/src/main/java/org/kiwix/kiwixmobile/core/di/components/CoreComponent.kt, core/src/main/java/org/kiwix/kiwixmobile/core/history/HistoryActivity.java, core/src/main/java/org/kiwix/kiwixmobile/core/utils/KiwixDialog.kt, core/src/main/res/values/strings.xml
Fixes #1798 
Added confirmation dialogs in `HistoryActivity` and `BookmarkActivity` which asks the user to confirm the deletion of history/bookmarks. 
=> #1798 Confirm before deleting bookmarks and history

app/src/main/java/org/kiwix/kiwixmobile/webserver/ZimHostActivity.kt
Fixes #1852 
The layout is changed back to the start server layout even when the server is stopped using the stop button in the notification.
=> Fix #1852 Change layout when the server is stopped via notification

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java
Fixes #1872  #1873 
Added `tabsAdapter.notifyDataSetChanged();`
And another snack bar saying **Tab Restored** to notify the user.
Passed tabSwitcherRoot in  Snackbar View.
[Video Link](https://imgur.com/OfpI03u)
=> Fixed: Undo Option in TabSwitcher view

app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.kt
Fixes #1856
It removes the loading icon when LibraryFragment is created without internet connection being available.
=> Dismiss loading icon if no internet connection detected

core/src/main/java/org/kiwix/kiwixmobile/core/dao/NewRecentSearchDao.kt
Fixes #1825 
- User's recent searches to be unique
- Before saving a recent search, delete duplicates of that search title in the database.
=> #1825: Fix search history to show Unique searches

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java
Fixes #1881 
Modified `onBackPressed` in CoreMainActivity.java to land the home screen before exiting.
[Link](https://imgur.com/lflWQdr)
=> Fix #1881 Land home screen before exiting

core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.java
Fixes #1894 
Brought cursor to the end of saved notes
[Link](https://imgur.com/Ut7g4Cg)
=> Fix #1894 Cursor position fixed in notes

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java
Fixes #1908 
Added a condition to check if the search is just being canceled by the user to prevent the error toast from showing up.
=> Fix #1908 Put condition to check for cancelling search to prevent incorrect toast

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java
Fixes #1885 
The 'Search Kiwix' menu item from the text-selection menu now enters the Search Activity correctly. This also fixes the Search Widget from entering an infinite loop if the app is closed when the widget is called. This fix was done by moving the intent handling from onResume to onCreate and the onNewIntent method. 
We should discuss the use of the Search Widget as I am unsure of its intended purpose. Currently the search widget opens the app without going to the search activity if the app is currently closed. If the app is open in the background, the search widget opens the search activity with the currently opened book/zim file.
=> 1885 fixes search from widget and text selection from entering infinite activity restarting loop

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java
Fixes #1869
Moved updateNightMode() from the `BookDelegate` to the `webViewUrlFinishedLoading` method. This seems to fix the issue. Works with and without dark mode. 
=> #1869 Fix flickering when opening file in dark mode.

core/src/main/java/org/kiwix/kiwixmobile/core/search/adapter/SearchDelegate.kt, core/src/main/res/layout/item_bookmark_history.xml, core/src/main/res/layout/section_list.xml
Fixes #1915. Previously, there were no pressed states.
=> Fix #1915 Add selectable background to RecyclerViews

core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.java, core/src/main/res/layout/dialog_add_note.xml
Fixes #1902 
The note's title can be completely visible now even if it's too long. Users can view the entire title by scrolling it. 
**Screenshot**
=> Fix #1902 Make note title completely visible

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java
Fixes #1868
The bug occurs when the `currentWebViewIndex` is the last index of the `webViewList` and a tab is closed. After any tab is closed, the `webViewList` length is reduced by one. When we then try to open any tab: `hideTabSwitcher()` is called, which in turn calls `selectTab(currentWebViewIndex)`. Since `currentWebViewIndex` is the previous last index of the `webViewList` we get an index out of bounds exception. 
To solve this I added `currentWebViewIndex = 0;` to the `closeTab()` method. This seems to fix the issue. A more robust solution might be to calculate the new index when a tab is closed but just setting it  to zero seems to work as well.
=> #1868 Fix app crash on tab navigation after closing tab.

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java
Fixes #1949
`webViewUrlFinishedLoading()` did not update to full screen mode, and since it is called after onResume 
it overwrites any visibility changes to the toolbars on its `updateBottomToolbarVisibility()` call. To solve this I added `updateBottomToolbarVisibility()` after this call. 
=> #1949 full screen now opens after a page is loaded if it is enabled.

core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.java
Fixes #1963 
Keyboard is now closed when the add notes dialog is closed using the close button on the top left corner.
=> Fix #1963 Close keyboard when dialog is dismissed

app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt, core/src/main/res/values/dimens.xml, core/src/main/res/values/strings.xml, core/src/main/res/values/themes.xml
Fixes #1918 
Now just a snackbar is shown with the appropriate message when storage is insufficient for downloading a zim instead of showing a toast and a snackbar both. 
=> Fix #1918 Show only a snackbar when space is insufficient

app/detekt_baseline.xml, app/src/main/java/org/kiwix/kiwixmobile/settings/KiwixPrefsFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/AvailableSpaceCalculator.kt, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/dao/FetchDownloadDao.kt, core/src/main/java/org/kiwix/kiwixmobile/core/di/modules/DownloaderModule.kt, core/src/main/java/org/kiwix/kiwixmobile/core/downloader/model/DownloadModel.kt, core/src/main/java/org/kiwix/kiwixmobile/core/settings/StorageCalculator.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.java, core/src/test/java/org/kiwix/kiwixmobile/core/settings/StorageCalculatorTest.kt
Fixes #2002 
Downloader no longer preallocates. The AvailableSpaceCalculator queries the database and the filesystem to report if there is enough space for a download to succeed
=> #2002 Stop pre allocation of downloads and instead check currently downloading books to calculate available space

core/src/main/res/values-ar/strings.xml, core/src/main/res/values-qq/strings.xml, core/src/main/res/values/strings.xml
Fixes #1824
The strings for turning night mode on, off and automatic were earlier hardcoded. Now they are not and hence should be properly visible in all languages in which they are translated.
=> Fix #1824 Make night UI properly translated

app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.kt, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.kt, app/src/test/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModelTest.kt
Fixes #1899 
The action mode is now finished when a user shifts from the library to the online fragment. 
=> Fix #1899 Finish action mode when shifting fragments

core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt
Fixes #2038 
- prevent IllegalStateException
After checking our email crash reports it seems the IllegalStateException was what kotlin thought was nonNullable returning null
=> #2038 Crash Report 3.3.0: ZimFileReader.mimeTypeFromReader (ZimFileReader.java:132) 

core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.java, core/src/main/java/org/kiwix/kiwixmobile/zim_manager/MountPointProducer.kt
Fixes #1775 
Add sdfat to list of filesystems that can't support 4GB
Fix error in diagnostic report where external dirs weren't getting newlines appended
=> #1775 Kiwix does not find the ZIM files on SD-Card since Jan. Update

app/src/main/java/org/kiwix/kiwixmobile/webserver/ZimHostActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/KiwixDialog.kt, core/src/main/res/values-qq/strings.xml, core/src/main/res/values/strings.xml
Fixes #2071 
Update the start server dialog to give user information that books can also be hosted if the devices are on the same wifi network. 
=> Fix #2071 Update the start server dialog

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java
Fixes #2079 
- check mainMenu is not null
=> #2079 Crash Report 3.3.1: NPE MainMenu.isInTabSwitcher 

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java
Fixes #2108 
Fixes #2103  
- constrain position to be within bounds
=> #2108 Crash Report 3.3.1: java.lang.ArrayIndexOutOfBoundsException CoreMainActivity.selectTab

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java
Fixes #2194 
- guard against negative values
=> #2194 Crash Report 3.3.3: ArrayIndexOutOfBoundsException: CoreReaderFragment.getCurrentWebView (CoreReaderFragment.java:932)

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java
Fixes #2193 
- stop performing updates if fragment is not attached
=> #2193 Crash Report 3.3.3: IllegalArgumentException LanguageUtils.getCurrentLocale 

core/src/main/res/layout/fragment_main.xml
Fixes #2178 
Drawerlayout no longer uses `fitSystemWindows`. 
=> 2178 fix flickering when navigating

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/ReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java
Fixes #2230
The webviews Y translation and the reader fragments bottom margin are set to 0 on openFullscreen. The bottom nav bar is also hidden on `openFullscreen` and shown on `closeFullScreen`.
The alpha does not work on the `activity_main_fullscreen_button` image button. Any ideas? It works if the background color is set with a hard coded alpha value (or if we create a new theme attribute) e.x. `#CC000000` Where CC is the alpha value. 
=> #2230 fullscreen now works

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/ReaderFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/TableDrawerAdapter.java
Fixes #2242
Because the main activities toolbar is set for each fragment and is not disposed of, the fragment reference is probably kept and the garbage collector can't collect the fragments. Setting the support action bar to null before switching fragment allows the reference to be collected and fixes the memory leak that causes tab switching to be slow and crashing.
=> Fix crash-causing memory leak

core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModel.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/FinishActivity.kt, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModelTest.kt, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/FinishActivityTest.kt
Fixes #2302
The back button did not work because the search activity was cast to CoreMainActivity. The FinishActivity side-effect is re-added and used in the search view model.
=> #2302 back-button now works from search

core/src/main/java/org/kiwix/kiwixmobile/zim_manager/MountPointProducer.kt
Fixes #2282 
- mark sdfat as virtual
=> #2282 Samsung exfat driver "sdfat" forbids to write big files

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java
Fixes #2338
Memory leaks present in ReaderFragment and OnlineLibraryFragment were fixed. 
One leak is reproducible by the following steps: 
1. Open app.
2. Open book and go to reader.
3. Go to history.
4. Go to OS home screen. That is, minimize Kiwix. 
This leaks either the `webViewList`, or the `actionBar` in CoreReaderFragment. 
Fixed by adding:
```
webViewList.clear();
actionBar = null;
```
to `onDestroyView()` in CoreReader.
Another memory leak from the `OnlineLibraryFragment`.
Reproduced by:
1. Open online library fragment.
2. Go to history.
3. Minimize kiwix.
libraryAdapter seems to be the villain here. 
Edit: Fixed by setting the `libraryList` `adapter` to null in `onDestroyView`.
=> Feature/frans lukas/2338 fix memory leaks

buildSrc/src/main/kotlin/Versions.kt
This uses the latest libzim 6.2.0 which integrates a cache system a lot better than before. Worth make it available in 3.4.
=> bump kiwixlib version 9.4.0"

core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt
=> #2104 CrashReport 3.3.1: java.lang.NullPointerException FileUtils.contentQuery

core/src/main/java/org/kiwix/kiwixmobile/core/utils/ServerUtils.kt, core/src/test/java/org/kiwix/kiwixmobile/core/utils/ServerUtilsTest.kt
Fixes #2348
Made the `formatIpForAndroidPie` function not iterate out of bounds. What is the purpose of this function? Given the input `"192.168.10.141.1"` it returns `"192.168.10.1"` which seems might broken, not that it would ever get `"192.168.10.141.1"`.
=> #2348 out of bounds error fixed on ip formatting.

core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FragmentExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/SearchFragment.kt
Fixes #2378 
`closeKeyboard()` was moved to FragmentExtensions.
Keyboard now closes on fragment exit (from searchFragment).
=> Feature/frans lukas/2378 fix search keyboard

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java, core/src/main/java/org/kiwix/kiwixmobile/core/page/viewmodel/effects/OpenPage.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/Constants.kt, core/src/test/java/org/kiwix/kiwixmobile/core/page/viewmodel/effects/OpenPageTest.kt
Fixes #2308
The page fragment was not popped from the fragment backstack when a page was opened. This is now fixed, which fixes the back button in the top action bar from requiring double taps if two page fragments are active. 
=> #2308 duplicate page fragments will no longer occur.

.github/workflows/coverage.yml, .github/workflows/pull_request.yml
Fixes #2504 
Added the `always` condition for upload steps/jobs.
NA
=> CI: Upload Reports to GH Actions even on check failures

custom/src/main/res/drawable-night-v23/launch_screen.xml, custom/src/main/res/drawable-night/launch_screen.xml, custom/src/main/res/drawable-v23/launch_screen.xml, custom/src/main/res/drawable/launch_screen.xml
Fixes #2534 
Note: The only problem is that it shows perfectly on the device that stretched before but it doesn’t show(i.e splash screen) at all on not stretched before
=> bug/gouri-panda/2534 WikiMedia AR app doesn't start interface very well

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java
Partial #2545 
- simplify tab restoration
This does not address the images of tabs being blank post restoration, however selecting one tab will restore the others
=> #2545 New Tabs & recreation is loading home page on other tabs 

.github/workflows/pull_request.yml, buildSrc/src/main/kotlin/Versions.kt
Many users complain that downloads get stuck in the middle since latest release of Kiwix 3.4.3. Considering that we have updated to Fetch 3.1.5, this might be the cause of the regression. Updating to the latest version.
=> Bump-up fetch to 3.1.6

buildSrc/build.gradle.kts
Updated the Detekt Dependency from version `1.9.1` to version `1.10.0` which was released on July 7th, 2020. Also tested and verified with various scenarios while running the app.
=> Added Update for Detekt Dependency

buildSrc/build.gradle.kts
Reverts #2610 
Concerened PR broke staticAnalysis and was merged inadvertently, therefore reverting it so that further PRs don't fail sA by default.
NA
=> Revert "Added Update for Detekt Dependency"

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java, core/src/main/res/layout/reader_fragment_content.xml
Fixes #2647 
default visibility set to `GONE`
=> Default visibility changed Fixes #2647

core/src/main/res/layout/activity_kiwix_error.xml
Fixes #2566
Hello, the buttons are anchored to each other and the outside of the parent, so they should be visible now and not overlap.  The other issue in the checkbox list of details does scroll, but the window is small since the text is maximized.  Just touch and drag and you'll see it move.
=> 2566 re-anchor diagnostic activity buttons

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java
Fixes #2398 
Note: In order to successfully create the bug you have to completely kill the `kiwix-android` app, and start searching from another app as in the issue mentioned.
=> Fixes Search Kiwix is just redirecting to kiwix

.github/workflows/nightly.yml
Fixes #
**Problem fixed:**
Again nightly builds were failing for a long time. Turned out, there were some changes made in API27+ SDK's installation from CLI which required user to _manually_ accept the license, which wasn't the case earlier.
Find failing builds here: [actions/nightly](https://github.com/kiwix/kiwix-android/actions/workflows/nightly.yml)
NA
=> ci: Bump RC version to accept API-29 SDK license

app/src/main/AndroidManifest.xml
Fixes #2693 
Starting with API level 30, if the application is targeting that version or higher, the app can't see, or directly interact with, most external packages without explicitly requesting allowance, either through a blanket QUERY_ALL_PACKAGES permission, or by including an appropriate <queries> element in your manifest. More info [here](https://developer.android.com/training/package-visibility)
Note:
Here I added all the browsable links. If we want to query appropriate links we can do that. IMO we should redirect all the links to the browser.
=> Supported external links in android 11 and higher

app/build.gradle.kts
Fixes #2704 
The language is disabled so that the App Bundle does NOT split the APK for each language. We're gonna use the same APK for all languages.
=> Fixes play store language issues

.github/workflows/release.yml
Due to version duplicates, we can't publish APK and bundle twice.
=> Removed `publishReleaseApk` to `assembleRelease` in download.kiwix.org

buildSrc/src/main/kotlin/plugin/AppConfigurer.kt
Necessary to allow bundle releases on the Play Store. Version code should stay the same if non-bundle compilation.
=> Add version-code lead number for bundles

app/detekt_baseline.xml, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt, core/src/main/AndroidManifest.xml, core/src/main/java/org/kiwix/kiwixmobile/core/settings/CorePrefsFragment.java, core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/KiwixDialog.kt, core/src/main/res/values/strings.xml, core/src/main/res/xml/preferences.xml
Fixes #2694 
Fixes #2716
**Description**
Added `MANAGE_EXTERNAL_STORAGE` permission. For the first time android 11 and later we'll ask specifically to give us permission in order to access all the zim files in android. If the user clicks yes then we'll navigate to Our app's android settings screen, then the user will give access permission.
If the user currently doesn't want to give the permission, We implemented a preference in our app's preference screen. That will allow users to go to our app's navigate settings screen. 
NOTE:-
Currently, if the user first allows the permission and then disallows the permission then the app will show all external files too even though clicking the zim files will not open that. In order to open(read or delete the external)zim files that you have to give …
=> Added `MANAGE_EXTERNAL_STORAGE` permission for Android 11 and later

core/src/main/res/values/strings.xml
1. Remove unnecessary apostrophe.
2. Replace a slash with "and", which is more natural to read.
=> Rephrase pref_allow_to_read_or_write_zim_files_on_sd_card

app/src/main/AndroidManifest.xml, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/settings/KiwixPrefsFragment.kt, core/src/main/AndroidManifest.xml, core/src/main/java/org/kiwix/kiwixmobile/core/Intents.kt, core/src/main/java/org/kiwix/kiwixmobile/core/settings/CorePrefsFragment.java
Fixes #2732 
* Refactored all the manage files permission code of external sd card functionality to the app module. Currently, we have code in the core module. Which makes no sense at all. We don't need permission at all in our custom apps.
* Fixes unnecessary permission showing on our Custom apps.
=> #2732 Refactored all files access permission code to the  app module

buildSrc/src/main/kotlin/Versions.kt
Fixes #2828 
updating to maven repo with version 2.9.1
=>  io.objectbox:objectbox: updating to maven repo with version 2.9.1 

.github/workflows/nightly.yml
Fixes #2898 
It was failing due to environment Java 11 was missing.
=> Fix nightly CI failure

.github/workflows/nightly.yml
Fixes #2971 
Due to Gradle caches, NDK wasn't able to find some classes.
=> Fixes Nightly CI

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt
Fixes #2618
This PR fixed `DrawerLayout` leaking from the `CoreMainActivity`. We are now setting it to null when the activity finishes.
=> Fixed `DrawerLayout` memory leak

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, app/src/main/res/layout/fragment_destination_library.xml, core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FragmentExtensions.kt
Fixes #2984
Fixes #3069 
Fix Misalignment of FloatingActionButton and BottomNavBar is Blank.
We Are Setting margin to parent fragment in KiwixReaderFragment
```
private fun setFragmentContainerBottomMarginToSizeOfNavBar() {
val actionBarHeight = context?.getAttribute(android.R.attr.actionBarSize)
if (actionBarHeight != null) {
setParentFragmentsBottomMarginTo(
complexToDimensionPixelSize(
actionBarHeight,
resources.displayMetrics
)
)
}
}
```
on first run we take permission of storage and then we ask ``` MANAGE_EXTERNAL_PERMISSION ``` from user (in android 11 and above) so ```onPause``` method of ```KiwixReaderFragment``` not called where we set margin 0 to parent fragment that's why this blank space is visible on first run.
Removed the extra margin from parent fragment in …
=> Fix Misalignment of FloatingActionButton and BottomNavBar is Blank

.github/workflows/nightly.yml
=> Fix Nightly build are actually running on default API but showing as its running on google_apis

app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/help/HelpFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/intro/IntroFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/main/TopLevelDestinationTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/settings/KiwixSettingsFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/splash/KiwixSplashActivityTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/testutils/RetryRule.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/testutils/TestUtils.kt, app/src/main/java/org/kiwix/kiwixmobile/intro/IntroFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/ConnectivityReporter.kt
Fixes #2678 
**Changes:** solved Wifi local hosting server not working as wifi was not getting detected 
**possible error**:  ``getConnectionInfo()`` was deprecated in Api level 31. ``WifiInfo`` available in ConnectivityManager. [more info](https://developer.android.com/reference/android/net/wifi/WifiManager#getConnectionInfo())
=> Improved wifi detection

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt
Fixes #3197 
I have placed a fix for it. If no ```zim file``` were selected in ```local library fragment``` then ```action mode``` would be ```null``` .
=> Fixed Action mode always visible after deleting zim file in ```LocalLibraryFragment```

core/src/main/res/values/strings.xml
Fixes #3180 
I'm introducing escape character in English string.xml which will be sufficient for string count issue but translate wiki update will be required after this merge.
=> Adding escape character in pref_text_zoom_summary

app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/testutils/TestUtils.kt
Fixes #3190
**How i fix this problem**
* I have improved test cases for better emulator performance.
* I have increase some wait for it in ```DownloadTest``` , ```InitialDownloadTest``` to visible ```Delete dialog``` properly. So ```Espresso``` can easily find it.
=> Fixed sometimes ```DownloadTest``` failing in CI

app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadTest.kt
Fixes #3199 
* I have added ```ActivityScenario``` to launch the activity for ```InitialDownloadTest``` instead of ```ActivityTestRule``` which is deprecated now.
=> Fixed sometimes ```InitialDownloadTest``` failed to launch screen

contrib/instrumentation.sh
Fixes #3202 
I have added retry count in bash script if emulator freeze then it will kill the adb and start again.
=> Fixed Sometimes CI failed due to Broken pipe (32) error in android 33 

app/src/androidTest/AndroidManifest.xml
Fixes #3172
I have added ```android:forceQueryable="true"``` in android test manifest (for sometimes apk not installing in android 33 with error ```FAILED TO INSTALL APK Error: UNKNOWN```) using ```forceQueryable``` basically lets other apps (like the orchestrator app) communicate with the test package. [More infomation here](https://developer.android.com/training/package-visibility)
=> CI sometimes failing on target 33

app/src/androidTest/java/org/kiwix/kiwixmobile/BaseActivityTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/help/HelpFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/intro/IntroFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/mimetype/MimeTypeTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchFragmentTest.kt, buildSrc/src/main/kotlin/Libs.kt, buildSrc/src/main/kotlin/Versions.kt
Fixes #3204 
* I have removed deprecated ```ActivityTestRule``` from test cases.
* Upgraded test dependencies to latest stable versions to better test performance.
| Dependency | From | To |
| :---         |     :---:      |     :---:      |
|  androidx.test:rules  |   1.4.0   | 1.5.0  |
|  androidx.test:runner  |   1.4.0   | 1.5.1  |
|  androidx.test:core  |   1.5.0-alpha02   | 1.5.0  |
|  androidx.test:rules  |   1.5.0-alpha02   | 1.5.0  |
|  androidx.test.espresso:espresso-web  |   3.4.0   | 3.5.0  |
|  androidx.test.espresso:espresso-intents  |   3.4.0   | 3.5.0  |
|  androidx.test.espresso:espresso-core  |   3.4.0   | 3.5.0  |
|  androidx.test.espresso:espresso-contrib  |   3.4.0   | 3.5.0  |
|  org.junit.jupiter:junit-jupiter  |   5.7.0   | 5.9.1  |
|  androidx.test.ext:junit  | …
=> Fixed remove deprecated ActivityTestRule from test cases. Upgrade test dependencies to latest stable version.

app/src/main/java/org/kiwix/kiwixmobile/language/viewmodel/SaveLanguagesAndFinish.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/webserver/WebServerHelper.kt, app/src/main/java/org/kiwix/kiwixmobile/webserver/wifi_hotspot/HotspotService.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/Fat32Checker.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModel.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/libraryView/AvailableSpaceCalculator.kt, buildSrc/src/main/kotlin/plugin/AllProjectConfigurer.kt, core/src/main/java/eu/mhutti1/utils/storage/StorageSelectDialog.kt, core/src/main/java/org/kiwix/kiwixmobile/core/NightModeConfig.kt, core/src/main/java/org/kiwix/kiwixmobile/core/downloader/DownloaderImpl.kt, core/src/main/java/org/kiwix/kiwixmobile/core/downloader/fetch/FetchDownloadMonitor.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/MainRepositoryActions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt, core/src/main/java/org/kiwix/kiwixmobile/core/settings/CorePrefsFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/settings/SettingsPresenter.kt, core/src/test/java/org/kiwix/kiwixmobile/core/dao/NewBookDaoTest.kt
Fixes #1273 
**What's the isssue**
It's giving lint error ```CheckResult``` on ```subscribe``` because we are only defining the objects but not disposing them after there use.
**What i do for fix this problem**
* I have disposed rxjava objects after there use.
* On some rxjava objects we have no control like we don't know when to dispose them (They have no life cycle events). so for now i have suppress lint warning for them.
```
SaveLanguagesAndFinish.kt (invokeWith) method.
Fat32Checker.kt (init) method.
NightModeConfig.kt (init) method.
DownloaderImpl.kt (download) method.
FetchDownloadMonitor.kt (init) method.
ZimFileReader.kt (streamZimContentToPipe) method.
(books deletes entities whose file does not exist) test case.
```
**We can do 2 thing for these object**
* We can store this …
=> Fixed lint issue CheckResult

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt
Fixes #3210 
**What is the problem**
When in local library fragment we have less book to scroll down then this happens because bottom navigation is not scroll down.
**How i fix this problem**
I have added bottom margin to ```SwipeRefreshLayout```. So all books will always above on bottom navigation view.
=> Fixed Last book (at the bootom of the screen) is still not fully visible

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, app/src/main/res/layout/fragment_destination_download.xml, core/src/main/res/values-ar/strings.xml, core/src/main/res/values-cs/strings.xml, core/src/main/res/values-de/strings.xml, core/src/main/res/values-fr/strings.xml, core/src/main/res/values-hi/strings.xml, core/src/main/res/values-it/strings.xml, core/src/main/res/values-iw/strings.xml, core/src/main/res/values-ku/strings.xml, core/src/main/res/values-mk/strings.xml, core/src/main/res/values-nqo/strings.xml, core/src/main/res/values-ru/strings.xml, core/src/main/res/values-sc/strings.xml, core/src/main/res/values-sk/strings.xml, core/src/main/res/values-sv/strings.xml, core/src/main/res/values-ta/strings.xml, core/src/main/res/values-tr/strings.xml, core/src/main/res/values-zh-rTW/strings.xml, core/src/main/res/values-zh/strings.xml, core/src/main/res/values/strings.xml
Fixes #3211 
* If user click on no button in internet permission dialog then allow permission text and button appears on zim file.
**How i fix this problem**
* I have set ```visibility=GONE``` to recyclerview of zim files when allow permission text and button is visible. 
* I have changed message as mention on ticket.
* I have removed allow button from online fragment.
* I have improved library loading (previously it's showing blank screen after placing above fixes) when network state is changed (from mobile network to WIFI).
=> Fixed bad visual artefact around network authorisation

app/src/main/java/org/kiwix/kiwixmobile/language/viewmodel/SaveLanguagesAndFinish.kt
Fixes #3208 
The main culprit is ```activity.onBackPressed()``` in ```SaveLanguagesAndFinish.kt``` for this bug beacuse it's not called from ```main thread```. That's the reason our activity did not recognised this is ```OnlineFragment``` after saving language.
```
Flowable.fromCallable { languageDao.insert(languages) }
.subscribeOn(Schedulers.io())
.subscribe({
activity.onBackPressed()
}, Throwable::printStackTrace)
```
**What i do for fixing this issue**
* I have tested with ```AndroidSchedulers.mainThread()``` and it's works as expected (Bottom Navigation is visible after saving language).
=> Fixed Bottom Navigation disappear after saving language

core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/ExternalLinkOpener.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/KiwixDialog.kt, core/src/main/res/values/strings.xml
Fixes #2065 
**What is the problem**
* In TTS (Text to speech) has not that language which user were using in read aloud feature.
* We are previously showing wrong message to user.
https://github.com/kiwix/kiwix-android/blob/30773dad42bd90b8d108bd292e47ab474a9df032/core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt#L120
**What i did to fix this problem**
* I have added a dialog. If TTS has not that language then this dialog popup to the user (After clicking on read aloud).
* After clicking on download button it automatically download the required language in TTS (through intent with action ```TextToSpeech.Engine.ACTION_INSTALL_TTS_DATA``` . It will go into phone settings and automatically installed the TTS language without user interaction).
=> Fixed read aloud feature on the wiki med offline app

core/src/main/res/values/strings.xml
Fixes #3225 
I have removed the unnecessary part of that message according to #3225.
=> Fixed wrong TTS message if language is not available

app/build.gradle.kts
Fixes #3176 
I have created a gradle task and it run before gradlew build. It will copy all strings from tarask file and add into tarask+old file after that it will delete the tarask file. so there is no compilation error and also we get latest changes from translate wiki if any change comes in tarask file.
=> FIxed Translate wiki PR failed to compile application due to tarask string file

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt
Fixes #3224 
* We have a condition if we click on no button in ```allow download content via mobile network dialog``` . then it save a boolean value in ```sharedprefrence``` and when we back to online fragment from another. It checked that value is true or not, if that value is true it shows the dialog. there is no other condition in that code block (if WIFI is active or not).
**How i fixed this problem**
* I have placed a condition in that code block, If allow content dialog is true and wifi is active then ```allow download content via mobile network dialog``` will not show.
=> Fixed Allow download content via mobile network message still not proper

app/src/androidTest/java/org/kiwix/kiwixmobile/utils/ExternalLinkOpenerTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/ExternalLinkOpener.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/AlertDialogShower.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/DialogShower.kt, core/src/main/res/values/strings.xml, core/src/test/java/org/kiwix/kiwixmobile/core/utils/ExternalLinkOpenerTest.kt
Fixes #2966
Fixes #2965
Made changes to files related to Dialog Boxes, to show the URL of external link in the warning dialog box 
Light mode       |  Dark mode |
:-------------------------:|:-------------------------:
=> Added the feature to display the external link in the warning dialog box

.github/workflows/ci.yml, .github/workflows/fdroid_nightly.yml, .github/workflows/nightly.yml, .github/workflows/pull_request.yml, .github/workflows/release.yml
To stop having the CI display warnings because these actions (old versions) were relying on deprecated Node.js 12.
=> Update GitHub workflow actions

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/settings/CorePrefsFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/LanguageUtils.kt
Fixes #37 
* ```Custom LayoutInflatorFactory``` code is outdated now.
* This code is not working on above android 12 (Now we are targeting android 13) I have tested with redmi note 9 **Android 12**.
**How i solve this problem**
* I have removed ```Custom LayoutInflatorFactory``` code (so now it's not giving error on android 12 and above).
* I have use ```window.decorView``` for getting text views from window and set custom fonts to those ```textviews``` .
| First Header  | Second Header | Second Header |
| ![first](https://user-images.githubusercontent.com/34593983/217535981-edf0aa51-8ce8-4c77-b6a4-b0c8fe05582a.jpg)  | ![second](https://user-images.githubusercontent.com/34593983/217535976-5f1e1c5a-2f8c-414a-b0f2-863349 …
=> Fixes of remove custom LayoutInflatorFactory for custom fonts

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/SimpleRecyclerViewScrollListener.kt
Fixes #3240 
**What is the problem**
We have implemented a fix for issue #3210. In this fix, we have set the bottom margin to ```SwipeRefreshLayout```. Our ```SwipeRefreshLayout``` has a scrolling behaviour, so when we scroll up, it shows white space.
**Fix**
* When we scroll up, I have set the bottom margin to 0 (so no more white space is showing). When we scroll down, I have set the bottom margin to the height of the bottom navigation, just as we did previously(for fix of #3210). 
**Video**
https://user-images.githubusercontent.com/34593983/221561321-d0da66e1-f5d3-4096-880e-c0d76fe3b4cf.mp4
=> Fixes of When we scroll up, then white space showing in ```LocalLibraryFragment```

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/Fat32Checker.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/libraryView/AvailableSpaceCalculator.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/libraryView/adapter/LibraryDelegate.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/libraryView/adapter/LibraryListItem.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/libraryView/adapter/LibraryViewHolder.kt, app/src/test/java/org/kiwix/kiwixmobile/zimManager/libraryView/adapter/LibraryListItemTest.kt
Fixes #2639 
* I have added a condition for both internal and external storage. if file system is OK but device has not enough space then ZIM file will showing as grey.
* I have added a new condition on grey view. If ZIM file showing as grey(this means device has not enough space in storage (But ZIM file can be download) which might be internal or external). Then user can long click on grey zim file, it shows a storage selection dialog (like previously showing when we clicking on zim file).
**For Internal Storage**
https://user-images.githubusercontent.com/34593983/217218341-ae428202-a8b2-45a3-bf0d-fb71d8443b7f.mp4
**For External Storage**
https://user-images.githubusercontent.com/34593983/217218892-af801fcd-6de3-4cdc-b520-ba15f5911fef.mp4
* Fixed downloading start after clicking on …
=> Fixes of files which are too big to be downloaded in the local storage should be greyed

core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt, core/src/main/res/layout/dialog_add_note.xml
Fixes #3255
1) Previously if user clicked on deleteNote button accidentally it used to delete the whole text and show a toast. There was no functionality to retrieve the deleted text.
2) Now on clicking on deleteNote Button it displays a snack-bar with an undo button embedded in it from which the user can restore their previously deleted text in the note.  
!<img src="https://user-images.githubusercontent.com/61341524/222450355-3828f946-2368-468d-8b90-3e97231b2682.gif" width=30% height=30%>
!<img src="https://user-images.githubusercontent.com/61341524/222449123-1ecb8400-aa07-487c-8a3d-c2e48524c9d2.jpeg" width=30% height=30%>
=> Issue#3255/delete note snackbar

app/src/androidTest/java/org/kiwix/kiwixmobile/page/history/NavigationHistoryRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/history/NavigationHistoryTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/di/components/CoreActivityComponent.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/history/NavigationHistoryClickListener.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/history/NavigationHistoryDialog.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/history/adapter/NavigationHistoryAdapter.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/history/adapter/NavigationHistoryDelegate.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/history/adapter/NavigationHistoryListItem.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/history/adapter/NavigationHistoryViewHolder.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/KiwixDialog.kt, core/src/main/res/layout/dialog_navigation_history.xml, core/src/main/res/values/strings.xml
Fixes #3042 
* I have use ```WebBackForwardList``` list of ```WebView``` class for showing navigation history(backward and forward).
* I have create a dialog to show ```NavigationHistory``` to user (this list is scrollable), when user long click on backward and forward button.
| Backward History  | Forward History |
| ![backwardhistory](https://user-images.githubusercontent.com/34593983/220615616-eb6d602e-176a-40ff-abf2-3dc848b48b46.jpg)  | ![forwardhistory](https://user-images.githubusercontent.com/34593983/220615649-95297e23-a942-4f66-a0d2-62e9acaed31f.jpg) |
* I have create automated test (```NavigationHistoryTest```) for testing this functionality.
> In the preference panel, an option should allow to clear the history.
<del> @kelson42 , since we are …
=> Fixes of Display Navigation History

core/src/main/res/values/strings.xml
Fixes #3262 
Replaced ```....``` with ellipsis character in English string file for ```performing_handshake``` and ```preparing_files```.
=> Replaced ... with ellipsis character

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/Intents.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/KiwixDialog.kt, core/src/main/res/values/strings.xml, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt
Fixes #3229 
* I have corrected the message and button text in custom app(in dialog which is un-clear to user previously)
* I have added a UI as mention on #3229 , if kiwix haven't storage permission.
* I have made a extension function to go into ```app setting``` for reusability in both (custom and kiwix ) app.
=> Fixed Endless media access permission request

buildSrc/src/main/kotlin/Libs.kt, buildSrc/src/main/kotlin/Versions.kt
This was split out from https://github.com/kiwix/kiwix-android/pull/3261#discussion_r1138198931 . In that PR, I was going to bump the version of a dependency, but I removed the lines instead when I realized that the lines were unused (the library was used but it ignored those lines).
This PR removes misleadingly unused versions. This was done with a bash script to grep the entire codebase to find variables in the `{Lib,Version}s.kt` files that were unreferenced. `gradle build` continued to succeed with all unit tests passing. It's assumed that it will work at runtime because this PR shouldn't affect the resulting apk. Consider the following misleading versions:
Listed as "6.7.1" at https://github.com/kiwix/kiwix-android/blob/e19bb9cf978ea628935df5f777fc02748b62cc32/buildSrc/src/main/kotlin …
=> Remove misleadingly unused library versions

core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt
Fixes #3269 
1) Previously if the user saved a note after writing a text the save button would still be enabled and clicked on it would repeatedly show the toast of "Note Successful".
2) Now after saving a note the save note button is disabled until the user makes some changes to the note.
https://user-images.githubusercontent.com/61341524/225615351-2f53bf7c-84f1-44b9-853d-47d5ff6f61dd.mp4
!<img src="https://user-images.githubusercontent.com/61341524/225616359-ab9da20b-f553-4e62-ad87-651b9f324197.jpeg" width=30% height=30%> !<img src="https://user-images.githubusercontent.com/61341524/225616756-399a4459-6c97-4f4b-a2d6-3a20ba0c70ab.jpeg" width=30% height=30%>
=> created and implemented disableSaveNoteMenuItem function

app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/library/LibraryRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryTest.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt
Fixes #3273 
* In this PR we have fixed the blank screen showing in android 13, Also i have found a bug while testing if we grant permission inside the application(on android 10 and below if we have not any zim file in our device) then it's showing same blank screen as showing in android 13 because in ```onRequestPermissionsResult``` we are settings the visibility of ```Recyclerview``` now i have replaced the visibility with ```requestFileSystemCheck()``` method which automatically check the file system and set the UI according to the file system.
**Edited**
* We have add the test cases for testing the ```LocalLibraryFragment``` , we are testing the both scenario if device has not any zim file and after downloading the zim files Zim list is visible or not.
=> Fixed library showing blank screen in android 13

app/src/androidTest/java/org/kiwix/kiwixmobile/utils/ExternalLinkOpenerTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/ExternalLinkOpener.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/AlertDialogShower.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/DialogShower.kt
Fixes #3279 
Previously we were using `URL` Java API to parse the given the url. Which makes sense for basic url protocol but in geo location case the api couldn't parse the url because it was designed by Android and the Java API doesn't support it. So in this case we put the Androids `Uri` to access all the Android related protocol plus basic protocol.
=> Bug: Protocol added for the geo location 

team-props/git-hooks.gradle
Fixes #3276
This PR fixes Git worktree support.  It does so by using the proper `git rev-parse --git-path hooks` command instead of assuming `.git/hooks` exists. In worktrees, `.git` is a file instead of a directory, and it's a text file containing a path.
Tested in a worktree on Ubuntu 22.10:
```
BUILD SUCCESSFUL in 2m 6s
```
=> Support git worktrees

.github/workflows/ci.yml, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Versions.kt, buildSrc/src/main/kotlin/plugin/AllProjectConfigurer.kt, custom/src/customexample/res/mipmap-anydpi-v26/ic_launcher.xml, custom/src/customexample/res/mipmap-anydpi-v26/ic_launcher_round.xml, gradle/wrapper/gradle-wrapper.properties, jacoco.gradle, lintConfig.xml
Fixes #3266 
* We have upgraded android Gradle version to ```8.0``` .
* In this PR we have replaced ```com.dicedmelon.gradle:jacoco-android:0.1.5``` with ```org.jacoco:org.jacoco.core:0.8.8``` . Because this library contains the deprecated code which is not compatible with gradle ```8.0```.
* WE have upgraded ```com.android.tools.build:gradle``` from ```7.3.1``` to ```7.4.2``` .
* Gradle ```8.0``` comes with updated lint rules. Currently in this PR two lint errors are present 
* ```NotificationPermission``` for this lint error we have ticket open https://github.com/kiwix/kiwix-android/issues/3268
* ```Monochrome icon is not defined```  in Custom application , It needs a small fix so i have placed in this PR.
=> Upgraded android Gradle version to 8.0

.github/workflows/ci.yml
This is the recommended (by https://github.com/ReactiveCircus/android-emulator-runner) way/version to instanciate. This allows as well to catch a more recent version.
=> Use latest version of android-emulator action

core/src/main/java/org/kiwix/kiwixmobile/core/entity/LibraryNetworkEntity.kt
Fixes #3092 
* Since `remoteUrl` is no longer used in our project and it is marked as deprecated, so it is better to remove this.
* For `File` Object we have not found any good reason on the issue as well as on PR description, so for now we have removed the deprecated annotation from `File` object https://github.com/kiwix/kiwix-android/issues/3092#issuecomment-1453472762 .
=> Fixes of deprecate objects in LibraryNetworkEntitiy

app/proguard-rules.pro
Fixes #3287 
We are using `isMinifyEnabled=true` in this variant [More Information Here](https://developer.android.com/build/shrink-code). The issue caused by the minification process. `MetaLinkNetworkEntity$Pieces` , `MetaLinkNetworkEntity$FileElement` constructors has changed or removed by the minification process.
**Solution**
We have added the code in `app/proguard-rules.pro` to keep all the classes of `MetaLinkNetworkEntity.kt` as it is in `Play Store Variant`.
**Video Sample After Fixing**
https://user-images.githubusercontent.com/34593983/231706478-962741b0-e189-4ffb-abc1-55866ce8148d.mp4
=> Fixed Downloading ZIM files are not working in Play Store Variant

core/src/main/res/mipmap-anydpi-v26/ic_launcher.xml, core/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
Fixes #3291 
This pull request implements the latest Android 13 feature, Themed Icons, into the app. Themed Icons provide a fresh and modern look to the app, aligned with the updated Android design guidelines. This enhancement adds a new set of icons that are designed to dynamically adapt to the app's current theme, whether it's light or dark, without compromising on visual consistency.
Changes made in this pull request:
Added a new set of Themed Icons that follow the Android 13 design guidelines.
Testing:
* Tested the app on various Android devices running Android 13 and confirmed that the Themed Icons are displayed correctly in both light and dark themes.
* Conducted thorough manual testing of the app's functionality, including icon usage and theming, to ensure that the implementation …
=> Implementing Android 13: Themed Icons Integration into the App

buildSrc/src/main/kotlin/custom/Auth.kt, custom/build.gradle.kts
Fixes #3290 
* Now we are uploading `Android app bundle` on `Play Store` instead of `APK` for custom apps.
* Previously we are uploading multiple `APK` on `Play Store` for different `ABI` , now we are uploading `Single App Bundle` on `Play Store` like we are uploading for `app module`. So for this we have refactored the code to upload only `app bundle` instead of uploading `Multiple Architecture APK`.
* We have also removed the deprecated methods (`versionCodeOverride`, `versionNameOverride`) , now we are using `VariantOutput.versionCode()` instead of `ApkVariantOutput.getVersionCodeOverride()`
=> Upload bundle on `Play Store` instead of `APK` for custom apps

.github/workflows/ci.yml, app/src/androidTest/java/org/kiwix/kiwixmobile/NetworkTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/help/HelpFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/intro/IntroFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/main/TopLevelDestinationTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/mimetype/MimeTypeTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/library/LibraryRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/history/NavigationHistoryTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/reader/KiwixReaderFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/settings/KiwixSettingsFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/splash/KiwixSplashActivityTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/testutils/TestUtils.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/utils/StandardActions.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/webserver/ZimHostFragment.kt, buildSrc/src/main/kotlin/Libs.kt, buildSrc/src/main/kotlin/Versions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ActivityExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
Fixes #3189 
* Fixed the `DownloadTest` which is failing on `Android 13` due to the `NotificationPermission` permission dialog being visible on the window so we have placed a condition if the test cases are running then it will not ask for `Notification permission`.
* `NetworkTest` is broken for now and we have ignored but somehow it is giving an error on this test in `Android 13`. so we have placed a fix here for this error.
```
04-28 08:50:12.166  5954  6406 E TestRunner: failed: initializationError(org.kiwix.kiwixmobile.NetworkTest)
04-28 08:50:12.166  5954  6406 E TestRunner: ----- begin exception -----
04-28 08:50:12.172  6071  6104 I FontLog : Received query Noto Color Emoji Compat, URI content://com.google.android.gms.fonts [CONTEXT service_id=132 ]
04-28 08:50:12.174  6071  6104 I …
```
=> Fixes of test failing on android 13(API level 33) with google_apis(System image) emulator

app/src/main/res/navigation/kiwix_nav_graph.xml
Fixes #3246 
When we are clicking on the buttons (`Download Books` and `Open Library`) to navigate between fragments then the navigation history is empty because we are not defined the history of the navigation graph, which is the reason the `reader` and `library` buttons are disabled after navigating through the action.
**Solution**
We have added the `popUpTo` tag in both actions to make the history of navigation. Like it makes when we clicked on the bottom navigation button.
**Before**
https://user-images.githubusercontent.com/34593983/234534466-5fc08cb0-4220-4082-94a5-bbc22e5087af.mp4
**After**
https://user-images.githubusercontent.com/34593983/234570182-c8a516cf-04c0-46a4-a8d6-05c94197a927.mp4
=> Fixes of unable to navigate between the fragments

core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/KiwixDialog.kt
Fixes #3330 
We were using `android.R.string.yes` and `android.R.string.no` in KiwixDialog, which is deprecated by the android as mentioned in the below screenshot.
**Fixes**
We have replaced the deprecated strings (`android.R.string.yes`, `android.R.string.no`) with their corresponding replacements provided by the Android framework (`android.R.string.ok`, `android.R.string.cancel`). These new strings have the same text as the deprecated ones.
=> Fixed deprecated Android dialog strings (android.R.string.yes, android.R.string.no)

buildSrc/src/main/kotlin/custom/Auth.kt, custom/build.gradle.kts
Fixes #3355 
Currently, we are trying to upload the app bundle on the play store, but the expansion file is not supported by the app bundle.
Expansion files are necessary for our custom apps.
**Fix**
Now we are uploading the apk on play store for custom apps.
=> Upload apk on play store instead of uploading the app bundle for custom apps

buildSrc/src/main/kotlin/plugin/AllProjectConfigurer.kt
Fixes #3353
We have made a change in our code by replacing `packagingOptions.exclude()` with `packagingOptions.resources.excludes`. This modification was necessary because the exclude method has been [officially](https://developer.android.com/reference/tools/gradle-api/7.2/com/android/build/api/dsl/PackagingOptions#exclude(kotlin.String)) deprecated by Android.
=> Fixed deprecated `exclude` method of `packagingOptions`

core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt
Fixes #3304 
When there is already an attached sd card in the phone and we are opening the zim file from a USB stick via the `+` icon it fails to load the zim file because we are taking the first index from `getExternalFilesDirs()` when the selected zim file is not from primary storage.
https://github.com/kiwix/kiwix-android/blob/ce423820f0b2aee20cdd69e064095ba4db24b4a2/core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt#L268
**Fix**
* When we select zim files using the `+` button, it returns the `DocumentId`, which includes the storage name as shown in the screenshots below. To obtain the actual storage path from where we select the zim file, we have made modifications to our getSdCardMainPath() method.
* Now, the `getExternalFilesDirs()` method …
=> Fixed open ZIM-File on external USB-Stick in Android

app/src/main/java/org/kiwix/kiwixmobile/webserver/ZimHostFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
Fixes #3337 
We were using `resources.getColor(Int)` to retrieve colors from the `colors.xml` file and apply them to our views.
**Fix**
We have replaced the deprecated getColor method with the corresponding replacement provided by the Android framework 
`ContextCompat.getColor(context, Int)`
=> Fixed deprecated resources.getColor(Int) method

app/src/main/AndroidManifest.xml
Fixes #3361 
**Issue**
We introduced this permission in https://github.com/kiwix/kiwix-android/pull/2810 to address the Wi-Fi issue on the Android 30 emulator on CI. However, the Play Store marks this permission as sensitive, and not allowing us to publish our application with it on the Play Store.
**Fix**
We have removed the permission from our application as now we have updated many test dependencies and now android 30 emulator is working without this permission so we don't need to use this permission.
=> Removing `QUERY_ALL_PACKAGES` permission

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/settings/KiwixPrefsFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/fileselectView/effects/DeleteFiles.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/fileselectView/effects/OpenFileWithNavigation.kt, core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FileExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimReaderContainer.kt, core/src/main/java/org/kiwix/kiwixmobile/core/settings/StorageCalculator.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt
Fixes #3250 
* We have `StrictModePolicy` warning in our project while using the `File` object methods e.g. `exists()`,  `freeSpace`, `totalSpace`, `canRead()`, `delete()`.
* This warning showing because we are performing a disk read operation on the main thread, which can result in UI freezing and decreased performance.
**What is the solution**
* We created a class for `File extensions` that performs disk operations on a background thread using `Coroutine`.
**Before Fix**
https://user-images.githubusercontent.com/34593983/236447464-177ea47e-f05e-42a9-a911-05ca1d035942.mp4
**After Fix**
https://user-images.githubusercontent.com/34593983/236447504-90bdbf06-176b-4a05-acd6-fb334a369193.mp4
=> Fixed red effect while changing the tabs

.github/workflows/release.yml
Fixes #3364 
We have temporarily commented the publishing version info task in our release CI, once we will publish 3.7.0 then we will uncomment this code.
=> Removed version info publishing task from release CI

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
Fixes #3371 
In the custom app, the webview does not adjust its height correctly when we open the full-screen mode. This causes a blank top bar to appear, as depicted in the image below. However, this feature works properly in our main app because we programmatically adjust the webview's height in our `Kiwix-android` app.
Please ignore the temporary red background, as it is added only to highlight the difference.
| Kiwix-android app  | Custom app |
| ![1685430529741](https://github.com/kiwix/kiwix-android/assets/34593983/303cf192-8591-4a28-b183-ca5c0beff56d) | ![1685430530747](https://github.com/kiwix/kiwix-android/assets/34593983/74492a86-8f58-4954-a107-7adb702ec841) |
**Fix**
To address this issue, we have made the following …
=> Fixed fullscreen feature is broken in custom app

core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt
Fixes #3383 
**Issue**
We are calling the setSelection method if the file already exists in the storage. However, if the file is not deleted for some reason, but doesn't contain any text, it causes a crash.
**Fix**
We have added a condition to check if the file has any content when loading it. If the file contains text, we will call the `setSelection` method; otherwise, we will skip that part.
https://github.com/kiwix/kiwix-android/assets/34593983/264b88cd-4764-4a17-8994-2369c9a11675
=> Fixed Application crashing while adding notes

core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt
Fixes #3389 
**Issue**
We encountered an issue while using the `substringBeforeLast('.', "")` method to extract the name from the URL for the file name. In the URL (https://kiwix.app/A/Portail:Tunisie/Index_th%C3%A9matique), there is no dot (.) present after the last slash (/), and we are passing an empty string as the `missingDelimiterValue` in the second parameter of this method. The implementation of this method checks if the `delimiter` is present in the string and returns the `missingDelimiterValue` if it is not found. In this case, we are passing an empty string, which is then returned by the method.
As a result, when we have an empty file name, we set the article name as the file name, as mentioned here
https://github.com/kiwix/kiwix-android/blob/3f86175a8b81244037ac17ec08b7751cdfd5 …
=> Fixed notes are not saving in custom app

core/src/main/java/org/kiwix/kiwixmobile/core/settings/CoreSettingsFragment.kt
Fixes #3385 
**Issue**
we were not handling the back-pressed event if the back button was clicked in the setting fragment, so we are seeing this error.
**Fix**
* We have modified the `setUpToolbar()` to handle the back icon click event properly like we are handling in other screens e.g. notes, bookmark, etc.
* Previously we were using the double bang operator on `supportActionBar` object to set its values, but this is not recommended because if the `supportActionBar` is null then it will lead to a crash, so we have refactored the code. Now we have placed a null check after that we are setting its values.
https://github.com/kiwix/kiwix-android/assets/34593983/0093dc41-1aa4-49bb-9aa4-6b5145d3ba8e
=> Fixed Custom apps back button doesn't work from setting screen

core/src/main/java/eu/mhutti1/utils/storage/Bytes.kt, core/src/main/java/org/kiwix/kiwixmobile/core/downloader/model/Base64String.kt, core/src/main/java/org/kiwix/kiwixmobile/core/downloader/model/Seconds.kt, core/src/main/java/org/kiwix/kiwixmobile/core/extensions/HeaderizableList.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/ImageUtils.kt, core/src/main/java/org/kiwix/kiwixmobile/core/zim_manager/KiloByte.kt, core/src/main/java/org/kiwix/kiwixmobile/core/zim_manager/fileselect_view/ArticleCount.kt
Fixes #3328 
**Issue**
We are using the inline modifier when defining the class, but in newer versions of Kotlin, this modifier is deprecated for classes. This deprecation was introduced in Kotlin 1.5.
**Fix**
now we are using `value` modifier which is recommended by the official kotlin page [mentioned here](https://kotlinlang.org/docs/whatsnew15.html#inline-classes)
=> Fixed deprecated inline modifer

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomFileValidator.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomMainActivity.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt
Fixes #3370 
**Issue**
We are requesting `read-write` permission at app startup, but it is unnecessary because we can read the zim file without this permission in custom apps.
**Fix**
* We have removed the permission request at app startup. To implement this, we modified our `OpenZimFile` method in the `CoreReaderFragment`. Now, if this method is called from custom apps, it will not prompt for storage permission. https://github.com/kiwix/kiwix-android/blob/8e7df7921a789ce976c9bbb5f66f7c2cf22e3e81/core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt#L1272 
* However, we still require storage permission for saving notes. Therefore, we made modifications to our `requestExternalStorageWritePermissionForNotes()` method. It now asks for permission from the user when the note …
=> Fixed Invasive access photos and media permission request at start

app/src/androidTest/java/org/kiwix/kiwixmobile/NetworkTest.kt
Fixes #3345 
* Now we are using updated `androidx.test.platform.app.InstrumentationRegistry` instead of deprecated `androidx.test.InstrumentationRegistry`.
* Now we are using `ActivityScenario` to launch the application instead of deprecated `ActivityTestRule`.
=> Fixes of deprecated methods in `NetworkTest`

app/src/androidTest/java/org/kiwix/kiwixmobile/testutils/TestUtils.kt
Fixes #3346 
**Issue**
We were using `androidx.test.runner.screenshot` class to capture a screenshot, but this class is deprecated and not work properly in the future versions.
**Fix**
Now we are using the updated test class `androidx.test.core.app.DeviceCapture` to capture the screenshot.
=> Fixed deprecated screenshot class

core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/RateDialogHandler.kt
Fixes #3331 
**Issue**
We were using an intent flag in `RateDialogHandler` when users go to the play store to rate our application, this intent flag is deprecated.
https://github.com/kiwix/kiwix-android/blob/1a31752f564e404858f3511bd127a92b8368a430/core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/RateDialogHandler.kt#L84
**Fix**
Now we are using the recommended Intent flag by [official docs ](https://developer.android.com/reference/android/content/Intent.html#FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET).
This new start supporting from android 21 and our minimum SDK version is 21 so we are using this flag without adding any condition.
=> Fixed intent flag `FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET` is deprecated

core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt
Fixes #3347 
**Issue**
We were using `intent.extras.getSerializable` in ErrorActivity to send the exception via Gmail, but this method is deprecated in `Android 33`.
**Fix**
Since this method is deprecated in Android 13, the Android team introduced a new way to obtain a serializable object in Android 13 and above. This new approach involves using `intent.extras.getSerializable(String, Class)`, where we need to pass the class of the object. This method is more type-safe. For versions below Android 13, we continue to use the same method as before. So to implement this we have placed a condition there.
=> Fixes of getSerializable() method of Intent is deprecated in android 13

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ActivityExtensions.kt
Fixes #3344 
**Issue**
We were utilizing the observe extension method of the LiveData class, this extension method is now deprecated in the newer kotlin version.
**Fix**
Now we are directly using the observe method of LiveData class instead of using the extension function.
=> Fixed observe extension method, which is deprecated in newer kotlin version

core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/KiwixDialog.kt
Fixes #3329 
**Issue**
We are using WifiConfiguration in the `ShowHotspotDetails` dialog.
https://github.com/kiwix/kiwix-android/blob/1a31752f564e404858f3511bd127a92b8368a430/core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/KiwixDialog.kt#L126
**Fix**
The `WifiConfiguration` class has been deprecated in Android 29, and although this method is still functional for those versions which are below android 29, we are currently not utilizing it anywhere in our codebase. However, to address the deprecation, we will adopt the [WifiNetworkSuggestion API](https://developer.android.com/reference/android/net/wifi/WifiNetworkSuggestion) as recommended in the [official documentation](https://developer.android.com/reference/android/net/wifi/WifiConfiguration). As a result, we have modified the …
=> Fixes of WifiConfiguration is deprecated

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/LanguageUtils.kt
Fixes #3335 
**Issue**
We are using the default constructor of `Handler()` in our code base, which is now deprecated because it is implicitly choosing a Looper during Handler construction which sometimes leads to a crash (if a handler is sometimes created on a thread without a Looper active, mentioned on the official docs).
**Fix**
Now we are using the android-recommended Handler's constructor, we are passing the `mainLooper()` to Handler() constructor.
=> Fixed default constructor for Handler is deprecated

app/src/main/AndroidManifest.xml, buildSrc/src/main/kotlin/plugin/AllProjectConfigurer.kt, core/src/main/AndroidManifest.xml, custom/src/main/AndroidManifest.xml
Fixes #3342 
**Issue**
We have been setting `android:extractNativeLibs=false` in each module of our application. However, this approach is deprecated in newer Gradle versions and may not work correctly in upcoming versions of Gradle.
**Fixes**
Now, we are using `jniLibs.useLegacyPackaging = false` in the `packagingOptions`, which is recommended in newer Gradle versions.
We have defined this in the `AllProjectConfigurer` class, as we include this class in every module.
Furthermore, we have removed the deprecated `android:extractNativeLibs="false"` from each manifest.
=> Fixed setting `android:extractNativeLibs=false` in manifest file is deprecated

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt
Fixes #3407 
**Issue**
Scenario / workflow  where bottom view is lost 
**Approach**
The bottom view animated back to it's original position when the user proceeds to delete item/s i.e. when the delete action is detected.
* Observed for the "RequestDeleteMultiSelection" action.
* Set the translationY of the bottom view to 0F which resets the vertical translation of the view to it's original position . Also animated it to a duration of 225L which is the default behaviour of the *HideBottomViewOnScrollBehaviour* of the material bottom view ,making sure consistent reappearing behaviour. 
**Result** 
https://github.com/kiwix/kiwix-android/assets/111702455/07de4e83-4755-4bea-8efd-831d758c9983
@kelson42 This is ready to be reviewed
=> Fixed bottom view lost issue

app/src/main/java/org/kiwix/kiwixmobile/zimManager/DefaultLanguageProvider.kt
Fixes #3340 
**Issue**
We were using `context.resources.configuration.locale.isO3Language` in `DefaultLanguageProvider`, this way of getting the locale is deprecated in Android 24.
**Fix**
We already have an extension function for the `Context` class that handles this deprecation. This extension function is being used in our `LanguageUtils` class to retrieve the current locale. Therefore, we have utilized it to handle the deprecation in the `DefaultLanguageProvider`.
https://github.com/kiwix/kiwix-android/blob/8e4fd413ef2b94e13b91cf535e0f599246380def/core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ContextExtensions.kt#L55
=> Fixes of local is deprecated

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt
Fixes #3334 
We were using the `requireFragmentManager()` which is deprecated now, it returns `getParentFragmentManager()` as shown in the below image. Now we are directly using the `getParentFragmentManager()` method in our code instead of using this deprecated method.
=> Removed deprecated `requireFragmentManager()` method

core/src/main/java/org/kiwix/kiwixmobile/core/compat/Compat.kt, core/src/main/java/org/kiwix/kiwixmobile/core/compat/CompatHelper.kt, core/src/main/java/org/kiwix/kiwixmobile/core/compat/CompatV21.kt, core/src/main/java/org/kiwix/kiwixmobile/core/compat/CompatV33.kt, core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/settings/CorePrefsFragment.kt
Fixes #3348 
We were using the deprecated `getPackageInfo()` method of the `PackageManager` class to retrieve the application's `package name` and `version code`. However, starting from `Android 13`, this method is deprecated. Additionally, we were relying on the deprecated `versionCode` field of the `PackageInfo` class to obtain the application's version code, which is also deprecated in `Android Pie`. Currently, our target SDK version is 33.
**Fix**
* To handle these deprecations, we have already introduced the `Compat33` and `Compat21` files. In Android 13 and above, we have created an extension function for the `PackageManager` class, utilizing the recommended method to retrieve the package information. For versions below Android 13, we continue to use the …
=> Fixed deprecated getPackageInfo() method of PackageManager

app/src/main/java/org/kiwix/kiwixmobile/webserver/wifi_hotspot/HotspotNotificationManager.kt
Fixes #3338 
**What is the Issue**
We were currently using NotificationCompat.Builder(context) to create the notification displayed to users when the hotspot is active on their device. However, this method is deprecated
**Fix**
We have replaced the deprecated constructor with a new one, `NotificationCompat.Builder(context, HOTSPOT_SERVICE_CHANNEL_ID)`.
=> Fixed NotificationCompat.Builder(context) is deprecated

app/src/main/java/org/kiwix/kiwixmobile/ConnectivityManagerExtensions.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModel.kt, app/src/test/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModelTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/compat/Compat.kt, core/src/main/java/org/kiwix/kiwixmobile/core/compat/CompatHelper.kt, core/src/main/java/org/kiwix/kiwixmobile/core/compat/CompatV23.kt, core/src/main/java/org/kiwix/kiwixmobile/core/compat/CompatV33.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/ConnectivityReporter.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/NetworkUtils.kt, core/src/test/java/org/kiwix/kiwixmobile/core/utils/NetworkUtilsTest.kt
Fixes #3339 
Refactored deprecated methods of ConnectivityManager class.
This PR refactors the deprecated methods of the ConnectivityManager class to ensure compatibility with different Android versions. The changes include:
- Introduced a new `CompatV23` class to handle the deprecation of `NetworkInfo` and utilize the new `NetworkCapabilities` APIs available from Android 23 onwards.
- Retained the existing methods for Android versions below 23 to maintain backward compatibility.
- Updated the test cases to cover both the new and old APIs.
These updates address the deprecation warnings and ensure that the code functions correctly on different Android versions.
=> Fixes of deprecated methods of ConnectivityManager class

app/src/main/java/org/kiwix/kiwixmobile/localFileTransfer/LocalFileTransferFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/webserver/ZimHostFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/NavigationHostFragment.kt
Fixes #3332 
Changed the `requestPermission` method of the fragment to utilize the new permission API `registerForActivityResult`.
* Updated the permission request for write storage permission, which is required for saving notes.
* Updated the permission request for read/write storage, necessary for scanning the file system in the LocalLibraryFragment.
* Fixed an issue where the permission layout would be displayed alongside the library list if the user swiped down to refresh.
* Suppressing the deprecation warning on onRequestPermissionsResult is necessary because we are requesting permission from the activity (as shown in the below code) and obtaining the result in the fragments. As a result, we cannot remove these methods, which is why we are currently suppressing the warning.
``` …
```
=> Fixes of requestPermission is deprecated

app/src/main/java/org/kiwix/kiwixmobile/language/viewmodel/SaveLanguagesAndFinish.kt, app/src/test/java/org/kiwix/kiwixmobile/language/viewmodel/SaveLanguagesAndFinishTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/help/HelpFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/PageFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/history/NavigationHistoryDialog.kt
Fixes #3400 
**Issue**
We were using the deprecated `onBackPressed` method.
**Fix**
This PR introduces changes to refactor the usage of the deprecated `onBackPressed` method. The `onBackPressedDispatcher` API is now used instead.
Here's a summary of the changes made:
- Updated `AddNoteDialog.kt` and `NavigationHistoryDialog.kt` to handle the back button press on the navigation bar using the `onBackPressedDispatcher`.
- Modified `CoreMainActivity.kt` to handle all back button press operations in the application using the `onBackPressedDispatcher`.
- Updated `HelpFragment.kt` and `PageFragment.kt` to handle the back button press when the user clicks on the back arrow button in the toolbar.
- Refactored the `onBackPressed` method in `SaveLanguagesAndFinish.kt` to use the updated API, and …
=> Refactored onBackPressed method with updated API

core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FragmentExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt
Fixes #3349 
**Issue**
we were using the deprecated method `toggleSoftInput` of `InputMethodManager` class.
**Fix**
Now we are using the officially recommended methods `hideSoftInputFromWindow` for hiding the keyboard and `showSoftInput` for showing the keyboard.
=> Fixes of toggleSoftInput(Int, Int) method of InputMethodManager is deprecated

core/src/main/AndroidManifest.xml, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt
Fixes #3408 
* To use the TTS feature in Android 11 and above we need to declare `TextToSpeech.Engine.INTENT_ACTION_TTS_SERVICE` in the queries elements of their manifest to properly use the TTS service on our application.
You can find this in the [official docs](https://developer.android.com/reference/android/speech/tts/TextToSpeech).
* **Enhanced the TTS feature:**
Now, during the screen launch, we only set up the TTS service with the WebView. This is necessary to configure the JavaScript interface when the WebView is created. Otherwise, the JavaScript interface is not recognized. We initialize the TTS feature when the user tries to use it for better optimization.
=> Fixes of Text to Speech init failed

core/src/main/res/layout/bottom_toolbar.xml
Fixes #3434 
Fixes snackbar buttons which are small and increased sensitive zone.
=> Fixes of Snackbar buttons

app/build.gradle.kts, buildSrc/src/main/kotlin/plugin/AllProjectConfigurer.kt, buildSrc/src/main/kotlin/plugin/KiwixConfigurationPlugin.kt, custom/build.gradle.kts
Fixes #3351
**Issue**
Some lint options are deprecated in new Gradle version.
**Fix**
* We have introduced a new method, `configureCommonExtension`, in the `AllProjectConfigurer.kt` file since `Lint` is only available in `CommonExtension`. This allows us to configure Lint in one place for every module. Previously, we couldn't directly use Lint in the `android-library` project, but with this approach, we can now configure Lint for the `android-library` project as well.
* We have replaced the deprecated `ignore` method with updated `diseble` option.
* We have remove some small deprecation e.g. `setMatchingFallbacks` and `flavorDimensions`.
=> Fixed some `lintOptions` are deprecated

core/src/main/java/org/kiwix/kiwixmobile/core/help/HelpFragment.kt
Fixes #3428 
`onActivityCreated` is deprecated and replaced by the `onViewCreated` method of fragment, so now we are using this updated method in our `HelpFragment`.
=> Fixes of Fragment's onActivityCreated is deprecated

buildSrc/src/main/kotlin/custom/Auth.kt, buildSrc/src/main/kotlin/plugin/AppConfigurer.kt, custom/build.gradle.kts
Fixes #3429 
* We have suppressed the lint warning for `ApkVariantOutput` because we had previously refactored this deprecated method when uploading the app bundle for custom apps on the Play Store. However, we have recently uploaded the APK again and added this deprecated code. https://github.com/kiwix/kiwix-android/pull/3356.
* We have reduced the usage of the `androidpublisher` library for `GoogleCredential` and `JacksonFactory` in order to fix the issue with uploading the Kiwix app on the Play Store. This reduction in usage introduced deprecation. Currently, we have suppressed the deprecation warning for this. https://github.com/kiwix/kiwix-android/pull/3286.
* For the `capitalize` method of the String class, we are now using the `replaceFirstChar` method, which is recommended by the …
=> Fixed Auth.kt file using some deprecated method

app/src/main/java/org/kiwix/kiwixmobile/zimManager/libraryView/adapter/LibraryViewHolder.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/AlertDialogShower.kt
Fixes #3430 
* We already handled the deprecation of `fromHtml`, we have a string's extension function to handle the this so we are now using that function.
* Since `Toast.getView()` is no longer supported after Android 11 (it always returns null on Android 11 and above devices), we no longer need to show the toast on the ZIM file that is clicked by the user for UI enhancement. Therefore, we have removed this function and are now using the context class extension function to display the toast message.
**Before**
https://github.com/kiwix/kiwix-android/assets/34593983/822f2d80-96f9-479b-b9a7-a07906f40c1a
**After**
https://github.com/kiwix/kiwix-android/assets/34593983/2205d6f9-a9b7-4318-a745-0fe71763fa46
Please ignore the downloading start after showing the snack bar and toast it is only to …
=> Fixed `Toast.getView()` and `Html.fromHtml()` is deprecated

core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt
Fixes #3419 
**Issue**
We were using the `PreferenceManager.getDefaultSharedPreferences()` method of `android.preference` package to get the `SharedPreferences`, which is deprecated.
**Fix**
We are using the same method to get the `SharedPreferences`, but now we are using the `androidx.preference` package which is recommended by the [android docs](https://developer.android.com/reference/android/preference/Preference).
=> Fixes of PreferenceManager.getDefaultSharedPreferences() is deprecated

app/src/main/java/org/kiwix/kiwixmobile/localFileTransfer/KiwixWifiP2pBroadcastReceiver.kt, app/src/main/java/org/kiwix/kiwixmobile/localFileTransfer/WifiDirectManager.kt
Fixes #3431 
* Since `NetworkInfo` is deprecated, and we are already handling this type of deprecation in the `Compat` class, we were using the `NetworkInfo` class here to check the internet connection status. Now, we are using the Compat method to check the internet connection status.
* To address the deprecation of `intent.getParcelableArrayExtra(String)` (which was deprecated in Android 13), we are now using the `intent.getParcelableArrayExtra(String, Class)` method. This method was introduced in API level 33. However, for earlier versions of Android, we will continue using the deprecated method to handle the deprecation of `intent.getParcelableArrayExtra(String)`.
=> Fixes of KiwixWifiP2pBroadcastReceiver using some deprecated methods

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/ConnectivityBroadcastReceiver.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/Fat32Checker.kt, app/src/test/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModelTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/data/remote/KiwixService.kt, core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ContextExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/NavigationHostFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/SearchFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModel.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/StartSpeechInput.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/LanguageUtils.kt, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/StartSpeechInputTest.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt
Fixes #3443 
As we already fixed the deprecated code for Android 13 and below, we have suppressed the deprecation warning because we do not have any alternative for these methods and these are only deprecated in Android 13.
=> Fixes of Some deprecation warnings are showing in the logs but they are already fixed

core/src/main/java/org/kiwix/kiwixmobile/core/page/notes/NotesFragment.kt
Fixes #3448 
We were saving the switch value in the sharePreference but in the `NotesFragment`, we are not initially setting the saved value to `switcher`. Now we have set the saved value to the `switcher`.
https://github.com/kiwix/kiwix-android/assets/34593983/898a2492-3443-4f24-a730-adf6851d12af
=> Fixes of View Notes from all books Switch is always enabled

core/src/main/java/org/kiwix/kiwixmobile/core/downloader/fetch/FetchDownloadNotificationManager.kt
Fixes #3441 
We encountered an issue where the download remained pending indefinitely if we canceled it from the notification. This happened because when we canceled the download by clicking the notification cancel button, it kept a reference in the fetch system. Consequently, if we tried to download the same file again, fetch created a new download ID, resulting in a conflict with the existing instance of the file. As a result, the download did not start.
However, when we canceled the download within the app itself, it deletes the instance from fetch, which automatically deletes the temporary file from storage.
To resolve this issue, we have made a change. Instead of using the CANCEL action, we now use the DELETE action. So, if the user cancels the download from the notification, it will …
=> Fixes of Zim file does not download / pending forever

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
Fixes #3370 
**Issue**
The custom permission dialog is shown directly without asking the permission.
**Fix**
We have made improvements to the permission-asking process for custom apps. It will now check if the permission has been asked before, and if not, it will ask for permission. If the user denies the permission twice, then the custom permission dialog will be shown.
**Permission granted scenario**
https://github.com/kiwix/kiwix-android/assets/34593983/41ab11cc-f749-4c38-a674-cf12b026551d
**Permission deny scenario**
https://github.com/kiwix/kiwix-android/assets/34593983/538347f4-fd8a-4565-95a3-b648352b3a65
=> Improved the permission asking scenario for custom apps

core/src/main/java/org/kiwix/kiwixmobile/core/settings/CorePrefsFragment.kt
Fixes #3463 
Now we are not showing the storage selection dialog in `OnlineLibraryFragment` if the user already configured the storage in `settings`.
https://github.com/kiwix/kiwix-android/assets/34593983/bf43ddc8-1625-4fd9-85ea-e3bcae9418cc
=> Fixes of Storage configured dialog showing again in OnlineLibraryFragment if we configured it from settings's screen

README.md
Fixes #3406 
This PR updates the `README.md` file to provide clear and detailed information about the `ZIM File Picker` restriction and `storage scanning` in the `Play Store variant` of the `Kiwix app`. The updated `README.md` file now includes a dedicated section explaining that starting from `Android 11`, the zim file picker feature is restricted in the Play Store variant due to Play Store policies. It clarifies that users running `Android 11 and above` will not be able to load zim files from `internal/external` storage directly within the app. Additionally, it mentions that the Play Store variant does not have the `MANAGE_EXTERNAL_STORAGE` permission, which is required for scanning storage and accessing zim files from arbitrary locations. To address this restriction, the `README.md` …
=> Updated README.md file to explain ZIM File Picker Restriction and Storage Scanning in play store variant

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebChromeClient.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/WebViewCallback.kt
Fixes #3468 
Fixed Keyboard repeatedly disappearing and reappearing in search when any article is loading in the background.
* When any article is loading then we invalidate the `OptionMenu` from `KiwixWebChromeClient` (It does not check whether the fragment is visible or not) which also invalidates the toolbar and the search bar is inside the toolbar that's the reason the keyboard showing and hiding repeatedly.
* Now we are invalidating the `OptionMenu` inside the `CoreReaderFragment` when it is visible to the user since this fragment loads the content in the webview. Hence, it is better to update the UI when it is visible to the user so it would not affect any other UI part.
=> Fixed Keyboard repeatedly disappearing and reappearing in search when any article is loading in the background

app/src/main/java/org/kiwix/kiwixmobile/zimManager/FileWritingFileSystemChecker.kt, core/src/main/java/org/kiwix/kiwixmobile/core/zim_manager/MountPointProducer.kt
Fixes #2889 
See https://github.com/kiwix/kiwix-android/issues/2889#issuecomment-1695520167
Enhanced FileSystem Check.
* Added `tmpfs` filesystem to `support 4GB filesystem` list since this type supports writing files over 4GB.
* Updated the name of the writing test result file to `kiwix_4gb_writing_test_result` to enhance readability.
=> Added tmpfs filesystem to `support 4GB filesystem` list and improved the writing test file name

core/detekt_baseline.xml, core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt
Fixes #3462 
Previously, we had added support for `USB-OTG` for Android 10 and below devices in https://github.com/kiwix/kiwix-android/pull/3311 but at that time we did have not any way to add support for `Android 10` and above devices, because `context.getExternalFilesDirs("")` does not provide the USB path in `Android 10` and above devices for security reasons. There is no direct way to access the `USB-OTG` on these devices, but `USB-OTG` is mounted under the `/mnt/media_rw` directory, so now we are directly using this to open zim files from the USB drive for Android 10 and above devices.
https://github.com/kiwix/kiwix-android/assets/34593983/e475cc53-3598-4ae1-b454-fdc10a3ac9a9
=> Fixed USB-OTG not working on android 11 and above devices

app/src/androidTest/java/org/kiwix/kiwixmobile/BaseActivityTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/NetworkTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/settings/KiwixSettingsFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/splash/KiwixSplashActivityTest.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
Fixes #3472 
* We have `bookmarkingDisposeble` for handling the bookmark which is perfectly working when we are opening a new zim file and with a previously open zim file, but the problem was if a zim file is opened and we are switching between screens then the bookmark functionality was broken. Because we are disposing the `bookmarkingDisposeble` if the screen is not visible to the user, to avoid memory leak. But when the screen is again visible to the user then we were not setting up `bookmarkingDisposeble` to handle the bookmarks that's the reason the bookmark functionality was broken, now we have set up the `bookmarkingDisposeble` again when the reader is visible to the user.
https://github.com/kiwix/kiwix-android/assets/34593983/3df8a8f7-5dd3-4289-bbd5-858d6fc63f75
* Improved test …
=> Fixed Bookmark toggle is not ON for saved bookmarks

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
Fixes #2561 
The issue was that we were not properly uninitialized the service worker, which was sometimes causing problems and preventing us from reading the `Zimit-generated` zim files. Therefore, we have now implemented the proper uninitialization of the service worker before loading the URLs for new zim files.
https://github.com/kiwix/kiwix-android/assets/34593983/179f5992-015e-411c-b0c0-79bb7962b8cb
=> Fixed Zimit-generated zim files were partially failing to open.

app/src/main/java/org/kiwix/kiwixmobile/zimManager/libraryView/adapter/LibraryListItem.kt, core/src/main/java/org/kiwix/kiwixmobile/core/data/remote/BasicAuthInterceptor.kt, core/src/main/java/org/kiwix/kiwixmobile/core/di/modules/DownloaderModule.kt, core/src/main/java/org/kiwix/kiwixmobile/core/di/modules/NetworkModule.kt, core/src/main/java/org/kiwix/kiwixmobile/core/downloader/model/DownloadItem.kt, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt, core/src/main/res/values/strings.xml, core/src/test/java/org/kiwix/kiwixmobile/core/remote/BasicAuthInterceptorTest.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/download/CustomDownloadFragment.kt, custom/src/test/java/org/kiwix/kiwixmobile/custom/download/CustomDownloadViewModelTest.kt
Fixes https://github.com/kiwix/kiwix-android/issues/3499
* Implemented downloading for authentication URLs in custom apps.
* Secret name extracted from the URL itself to avoid adding additional code for future apps similar to this one.
* For this we have made two extension functions one for checking whether the URL is an authentication URL or not, second one is for extracting a secret key from the URL.
* To properly test functionality for these functions we have added test cases for it.
* We properly handling the download at the first run, we are now showing a custom error message to the user if the zim file is unable to download(when the server returns an unsuccessful response).
=> Authentication created for DWDS app

app/src/androidTest/java/org/kiwix/kiwixmobile/localFileTransfer/LocalFileTransferRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/localFileTransfer/LocalFileTransferTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/main/TopLevelDestinationTest.kt, app/src/main/java/org/kiwix/kiwixmobile/localFileTransfer/KiwixWifiP2pBroadcastReceiver.kt, app/src/main/java/org/kiwix/kiwixmobile/localFileTransfer/WifiDirectManager.kt, core/src/test/java/org/kiwix/kiwixmobile/core/remote/BasicAuthInterceptorTest.kt
Fixes #3491 
* In Android 13, we previously used `intent.getParcelableArrayExtra` to retrieve the status of `P2P_DEVICE_CHANGED`. However, this method returned null because it's not actually an array. To resolve this issue, we have updated it to use `intent.getParcelableExtra`.
* For Android 12, we used to check the network state through `ConnectivityManager` every time the `WIFI_P2P_CONNECTION_CHANGED_ACTION` action was triggered. However, this approach wasn't reliable, as the action being triggered didn't guarantee a change in the network state. Instead, it sends an intent that we should now check for network changes. As a result, we have modified our code to utilize this intent within the `KiwixWifiP2pBroadcastReceiver`.
* Added test case for testing the functionality of …
=> Fixed, The File transfer feature does not work in android 12, android 13.

core/src/main/res/values/strings.xml
1. Replace comma with full stop—it's better to have to separate sentences.
2. Write "Play" with a capital letter, because it's a name.
=> Improve punctuation in a recently-added message

core/src/main/java/org/kiwix/kiwixmobile/core/data/remote/BasicAuthInterceptor.kt, core/src/test/java/org/kiwix/kiwixmobile/core/remote/BasicAuthInterceptorTest.kt, custom/build.gradle.kts
* We have removed the authentication of the URL to make it a normal URL because we are adding authentication in headers so does not need to be added to url.
* Enhanced getting secret function, if the URL is encoded then it will fail to get the secret from it so now we are properly decoding the URL before extracting the secret key from it.
* To properly test these two functions we have added test cases for it.
=> Remove Authentication from URL before downloading.

app/src/main/AndroidManifest.xml, core/src/main/AndroidManifest.xml
Fixes #3426 
**Issue**
The issue was introduced after we removed `QUERY_ALL_PACKAGE` tag from our manifest due to Play Store policy. It failed to open `pdf/supportLinks/zimfileUrlLinks/sendingEmails` on Android 10 and above with the default browser, because `intent.resolveActivity(activity.packageManager)` failed to resolve the intent with the default apps of the phone.
https://github.com/kiwix/kiwix-android/assets/34593983/476d49e7-8a2c-47b4-bbe7-13cf79931435
https://github.com/kiwix/kiwix-android/assets/34593983/ae3c0081-eb88-4cc8-989a-80cf94dfe358
**Fix**
We have added the query in the manifest to resolve the intent with the default apps of phones.
* Fixed, pdf is not opening with default pdf viewer.
* Fixed, sending emails failed with the default email service.
* Fixed, opening …
=> Fixed, unable to open the support link with default browser.

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Libs.kt, buildSrc/src/main/kotlin/plugin/AllProjectConfigurer.kt, custom/build.gradle.kts
Fixes #3502
* In this update, we've replaced the `URLConnection` with the OkHttp library, and now headers are being correctly passed in the request. As a result, the Zim file is successfully downloading.
* To integrate OkHttp into our Gradle project, we've moved the OkHttp dependency to our `buildSrc` folder.
| Download task successfull  | File Downloaded |
| ![Screenshot from 2023-10-10 13-03-25](https://github.com/kiwix/kiwix-android/assets/34593983/66eed99d-93c5-4eb2-9a28-f1950ca14eb7)  | ![Screenshot from 2023-10-10 13-03-34](https://github.com/kiwix/kiwix-android/assets/34593983/e50003df-d35c-4f8f-9b09-462c252319ac)  |
=> Fixed URLConnection not adding headers to the request.

buildSrc/src/main/kotlin/custom/Auth.kt, buildSrc/src/main/kotlin/custom/CustomApps.kt, custom/build.gradle.kts, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomFileValidator.kt, install_time_asset/build.gradle, install_time_asset_for_dwds/build.gradle, settings.gradle.kts
Fixes #3505 
Fixes [#kiwix-android-custom/issues/111](https://github.com/kiwix/kiwix-android-custom/issues/111)
* We have implemented Play Asset Delivery to include the ZIM file within the Android App Bundle (AAB).
* To achieve this, we've created Gradle tasks to automatically download the ZIM file and place it inside the assets folder.
* In order to utilize this asset file, we've refactored our custom application code.
* We haven't removed the functionality of uploading the APK, as this approach remains static for now. Thus, we are retaining both codebases.
=> Fixed, Unable to upload APK on play store for new apps.

app/detekt_baseline.xml, app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/localFileTransfer/LocalFileTransferRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/localFileTransfer/LocalFileTransferTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/main/TopLevelDestinationTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/library/LibraryRobot.kt, app/src/main/java/org/kiwix/kiwixmobile/localFileTransfer/LocalFileTransferFragment.kt, app/src/main/res/layout/fragment_local_file_transfer.xml, buildSrc/src/main/kotlin/Libs.kt, buildSrc/src/main/kotlin/Versions.kt, buildSrc/src/main/kotlin/plugin/AllProjectConfigurer.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt, core/src/main/res/values/strings.xml
Fixes #1532
* Reduced the `view_device_list_boundary` height to match the one below it, resulting in a more consistent appearance.
* Enhanced the permission request scenario; previously, permissions were requested one by one when the user clicked on the search button. Now, we request all necessary permissions at once to improve the user experience.
* Introduce the 'MaterialShowCase' feature to educate users on the file transfer functionality.
* Added test cases to comprehensively assess the `ShowCaseView` functionality. Ensured that the showcase view is displayed in full only once, and subsequent displays are prevented.
* Improved test cases which sometimes fail:
* Resolved the issue where `testShowCase` sometimes hung and failed. The test was failing because it only allowed showcasing a …
=> Fixed Refactor LocalFileTransfer UI.

app/detekt_baseline.xml, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt
Fixes #3515
* Fixed, can not open ZIM files from phone storage via the file picker in Android 13.
* Improved the permission request scenario for 'MANAGE_EXTERNAL_STORAGE' in Android 13. In the non-play store variant, we were not prompting users to grant this permission, and they were unaware that it was necessary to access the ZIM files in their storage. To resolve this issue, we now request this permission.
**Issue**
https://github.com/kiwix/kiwix-android/assets/34593983/2b428621-859e-41b5-b58b-31dec81c89ae
**Fix**
https://github.com/kiwix/kiwix-android/assets/34593983/dea7750d-1181-4bae-ae42-cc9fbcb932bf
=> Fixed, can not open ZIM files from phone storage via the file picker in Android 13.

core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ActivityExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/PageFragment.kt
Fixes #3523 
Since custom apps only have a single zim file, there is no need to display these switches, which can potentially confuse users. Therefore, we have hidden these switches in custom apps.
**Custom apps**
https://github.com/kiwix/kiwix-android/assets/34593983/2ed2233a-0ac1-4826-b7dc-31af2f642d6d
**Kiwix App**
https://github.com/kiwix/kiwix-android/assets/34593983/05a93912-d26a-4099-ab74-90993226050f
=> Fixed the redundancy of the 'All-Books-Mode' option for Bookmarks, Notes, and History in custom apps.

app/src/androidTest/java/org/kiwix/kiwixmobile/mimetype/MimeTypeTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/MainRepositoryActions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/bookmark/adapter/BookmarkItem.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/history/adapter/HistoryListItem.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/notes/adapter/NoteListItem.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/notes/viewmodel/effects/ShowOpenNoteDialog.kt, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimReaderContainer.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt, core/src/main/java/org/kiwix/kiwixmobile/core/webserver/KiwixServer.kt, core/src/main/java/org/kiwix/kiwixmobile/core/webserver/ZimHostFragment.kt, custom/build.gradle.kts, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomFileValidator.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomMainActivity.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt
Fixes #56
Fixes #3519 
Fixes #3522 
* We are introducing reading zim file content through `fileDescriptor` instead of creating a file to avoid using storage twice for the same zim file.
* As now we are using `fileDescriptor` for custom apps, and our notes functionality breaks with this change so we have refactored our notes functionality to properly work with `fileDescriptor`.
* Fix #3519. The problem was that we were saving the note name combined with `zimFileTitle` and `articleTitle`. When opening the saved note from `NotesFragment`, it retrieved the `noteTitle` from the database, which already contained the combined name. Subsequently, when saving the note again, it redundantly combined the name. To resolve this issue, we now extract the `articleName` when updating notes in …
=> Fixed, Reduce mass-storage consumption with Android custom apps with embedded ZIM

app/src/androidTest/java/org/kiwix/kiwixmobile/mimetype/MimeTypeTest.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/bookmark/adapter/BookmarkItem.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/history/adapter/HistoryListItem.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/notes/adapter/NoteListItem.kt, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimReaderContainer.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt
Fixes #1447 
* We are now using fileDescriptor to open the zim files with uris when someone tries to open the zim file directly from storage.
* As now we are using the assetFileDescriptor instead of direct files, we have refactored the functionality of saving (note, history, bookmark) so that we can open the same pages on the same zimFile.
https://github.com/kiwix/kiwix-android/assets/34593983/d4d1e98d-a279-4ed7-b60c-766bffbc81bf
=> Fixed, I can't open Zim from an external download.

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt
Fixes #3507 
We removed the activity finishing triggered by pressing the back button in the reader fragment. We initially added this when we were converting CustomReader to a fragment, as we encountered crashing issues at the time. However, it was quite some time ago, and we have since refactored our code. Now, it no longer crashes and functions smoothly without terminating the activity when the back button is pressed. We also made this change for when a user presses the back button from the download screen. This back button press is within the CustomReaderFragment, so it does not impact the functionality of the DownloadFragment.
https://github.com/kiwix/kiwix-android/assets/34593983/40286e03-1156-49fd-9848-df6f04fb4ced
* Moved `openSearchItem`, and `findInPage` functionality to our …
=> Fixed, Hitting back on the DWDS app exits it.

core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt
Fixes #3530 
**Issues**
* It was reading the code part(that is style element) in `Wikivoyage 2023-06` ZIM file.
* While reading the article it is skipping lines. For example:- It reads the first line then skips the second line, then it reads the third line, and skips the fourth line.
**Fix**
* We have removed the including of the `style` attribute if any is present in the content to avoid this type of issue, like we are removing the `(title, .navbox etc)`.
https://github.com/kiwix/kiwix-android/blob/252d846b64fc669670b3028f5d59a3ffc211f51e/core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt#L154
* The issue was caused by an unnecessary increment of the 'currentPiece' index in the onDone callback of the TextToSpeech engine. This double increment led to the skipping of …
=> Fixed, Using TTS on Wikivoyage 2023-06 (Android 13) reads code aloud.

app/build.gradle.kts, buildSrc/src/main/kotlin/Config.kt, core/build.gradle.kts
**Issue** 
_Originally posted by @MohitMaliFtechiz in https://github.com/kiwix/kiwix-android/issues/3538#issuecomment-1820293303_
**Fix**
* The `Config.kt` now holds the version information we can directly change the versionCode here and it will automatically replace in both gradle files.
* Removed duplicate version configurations from the `build.gradle` files.
=> Moved version-related properties from individual build.gradle files to a common configuration file (`Config.kt`).

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
Fixes #3543 
* Previously, when exiting full-screen mode, the `WindowCompat.setDecorFitsSystemWindows` configuration was set to `false`, causing a blank space between the sidebar logo and the Bookmark item because it is preventing to adjust the content.
* This change sets the configuration to `true` when exiting full-screen mode to ensure proper adjustment of the sidebar content, eliminating the undesired blank space.
* The adjustment is necessary to maintain a seamless layout and appearance, particularly after transitioning from full-screen mode.
https://github.com/kiwix/kiwix-android/assets/34593983/fa1ead73-6d8f-4efa-a6c6-ff1fb6571718
https://github.com/kiwix/kiwix-android/assets/34593983/9bdaa154-9669-4c6a-a6aa-1c8013cc2c63
=> Fixed, Sidebar adds unwanted space after closing the full screen mode.

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt
Fixes #3541 
* Previously, the bookmark toggle was not being activated when opening bookmarks for an already opened book.
* Fixed the issue by correctly setting up the bookmark disposable for the current ZIM file when opening bookmarks for the currently opened book.
**Kiwix app**
https://github.com/kiwix/kiwix-android/assets/34593983/83a34032-a786-4bd6-99b8-727f4ab659ac
**Custom app**
https://github.com/kiwix/kiwix-android/assets/34593983/1576324c-b86a-404d-9bf3-c4de085fcff0
=> Fixed, Bookmark toggle is not on when opening bookmarks for existing opened book.

app/src/main/AndroidManifest.xml, lintConfig.xml
Fixes #3549 
* The Play Store highlighted the need to add "/" to the beginning of the `android:pathPattern`. As a result, we have now included "/" at the beginning of all `android:pathPattern` instances to ensure compatibility with the Play Store. Also we have added `category BROWSABLE` to the scheme of the `content` type that is reported by the play store.
| Play store error  | Play store error | Play store for category |
| ![Screenshot from 2023-11-23 14-28-03](https://github.com/kiwix/kiwix-android/assets/34593983/1e73f316-7201-4634-a8f1-204deeeab47b) | ![Screenshot from 2023-11-23 12-29-59](https://github.com/kiwix/kiwix-android/assets/34593983/100d3e24-8a47-4014-a1ca-d3a5e1ad6650)  | ![Screenshot from 2023-11-23 …
=> Fixed: Numerous issues with links were reported by the Play Store.

core/src/main/java/org/kiwix/kiwixmobile/core/search/SearchFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModel.kt, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModelTest.kt
Fixes #3556 
**Issue**
The application was crashing when users rapidly typed to search for an entry. This was caused by frequent retrieval of search data from libkiwix, and the previous search job not being properly cleared, leading to it being retained in memory and causing crashes. 
https://github.com/kiwix/kiwix-android/assets/34593983/0daa7719-361a-4c64-add0-db731e7ea22f
**Logs**
```kotlin
Cmdline: org.kiwix.kiwixmobile
2023-11-28 17:14:15.098 19904-19904 DEBUG                   pid-19904                            A  pid: 19615, tid: 19747, name: DefaultDispatch  >>> org.kiwix.kiwixmobile <<<
2023-11-28 17:14:15.098 19904-19904 DEBUG                   pid-19904                            A        #00 pc 000000000042014c  /data/app/~~y5CudkmP7NaN7eUraxL42Q==/org.kiwix.kiwixmobile-j7pc3 …
```
=> Fixed: Version 3.8.0 shuts down after searching for an entry.

CHANGELOG
=> Updated the CHANGELOG for milestone `3.8.1`.

core/src/main/java/org/kiwix/kiwixmobile/core/search/SearchFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchState.kt, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchStateTest.kt
Fixes #3581 
* Removed the unnecessary estimation matches call on `libkiwix`, as we do not need this since `libkiwix` can handle this automatically.
* Cancelled the previously running job if a new `searchTerm` is in progress; this will avoid unnecessary memory allocation and data load on libkiwix.
=> Fixed the app crashes that occurred when deleting letters in a search.

buildSrc/src/main/kotlin/custom/CustomApp.kt, buildSrc/src/main/kotlin/custom/CustomApps.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/settings/CustomPrefsFragment.kt
Fixes #3586
We have introduced the option to disable `external links` for custom apps. If a custom app is configured not to display the `external links popup`, it will both hide the `external links` preference from settings and refrain from showing the `external link popup` when opening external links. Additionally, we have included relevant comments within the methods and code to provide developers with a clear understanding of the reasons behind these changes.
=> Introduced the disable external links option for custom apps.

custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomMainActivity.kt
Fixes #3584 
We have hidden the help screen from our sidebar. See https://github.com/kiwix/kiwix-android/issues/3584#issuecomment-1847290824
=> Fixes the issue where the "Help" submenu in the sidebar is misleading in custom apps.

app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryTest.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ActivityExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt
Fixes #3577 
If the `ManageExternalStorage` permission has not been granted, introduce the request, particularly when accessing features that necessitate this permission, such as downloading ZIM files, selecting a ZIM file from storage via the file picker, and refreshing the list of available ZIM files in storage.
=> Fixed unable to open zim files on sd card in version 3.8.1

core/src/main/java/eu/mhutti1/utils/storage/StorageDeviceUtils.kt
Fixes #3579
We have limitations in scanning all directories on Android 11 and above in the Play Store variant. If a user copies the ZIM file to the app-specific directory on the SD card, the scanning of the app-specific directory on the SD card has not been added, resulting in the copied files not being displayed on the library screen. Therefore, we added the scanning of app-specific directory to fix the issue.
=> Fixed version `3.8.1` from Google Play cannot find zim on SD card that are copied to app-specific directory.

buildSrc/src/main/kotlin/custom/CustomApp.kt, buildSrc/src/main/kotlin/custom/CustomApps.kt, core/src/main/res/drawable/ic_baseline_info.xml, core/src/main/res/menu/menu_drawer_main.xml, core/src/main/res/values/strings.xml, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomMainActivity.kt
Fixes #3590 
* Introduced the `About the app` option in the navigation for custom apps.
* If the custom app is configured to display the 'About the app' option in navigation, it will be visible. Clicking on it will redirect the user to the configured URL.
=> Fixed: Add Configuration Option for Custom Apps: "About" Link in Sidebar

app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/help/HelpFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/help/HelpRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/localFileTransfer/LocalFileTransferTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/main/TopLevelDestinationTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/mimetype/MimeTypeTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/PlayStoreRestrictionDialogRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/PlayStoreRestrictionDialogTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/history/NavigationHistoryTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/reader/KiwixReaderFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/webserver/ZimHostFragmentTest.kt, app/src/main/java/org/kiwix/kiwixmobile/help/KiwixHelpFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/help/HelpAdapter.kt, core/src/main/java/org/kiwix/kiwixmobile/core/help/HelpFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/KiwixDialog.kt, core/src/main/res/layout/item_help.xml, core/src/main/res/values/strings.xml
Fixes #3576 
* Showing Play Store restriction to the users in the help screen in the Play Store variant.
* Showing play store restriction dialog to the user on the first run.
* Introduced test cases for the new functionality to ensure its expected behavior in both variants, such as Play Store and non-Play Store.
=> Fixed Start-up message to inform about the restrictions on the Google Store app to open sideloaded ZIM files.

core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt
Fixes #3578 
* The getEntryByPath method was being called twice when retrieving content. Consequently, the initial call returned the content entry URL with additional parameters. Subsequently, when making the second call with the provided URL, it resulted in an "entry not found" exception. This issue prevented the loading of the CSS and content of the Zim file.
* Additionally, the getActualUrl method was primarily implemented to retrieve the redirect entry of the URL provided by the webView. It is unnecessary to invoke this method when obtaining content.
**Before fix**
https://github.com/kiwix/kiwix-android/assets/34593983/dc697ced-bc8a-43e0-acd3-ea8b81b96d45
**After fixing**
https://github.com/kiwix/kiwix-android/assets/34593983/650454c2-29f3-461d-b110-d0b5f36bfd99
=> Fixed Zimit archives are not displaying correctly.

app/src/androidTest/java/org/kiwix/kiwixmobile/webserver/ZimHostRobot.kt, buildSrc/src/main/kotlin/custom/CustomApp.kt, buildSrc/src/main/kotlin/custom/CustomApps.kt, core/src/main/res/values/strings.xml, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomMainActivity.kt
Fixes #3601 
* Enhanced the 'Support Kiwix' option, which is configurable in the navigation for custom apps. If the custom app is set to display the "Support" menu item in navigation, it will be shown; otherwise, it will be hidden from the app.
* Replaced the "kiwix" and "the" prefixes in "Support kiwix" and "About the app" with the app name in the navigation.
| Support Url configured  | Support Url not configured | Kiwix App |
| ![Screenshot_20231215-161405_Dwds](https://github.com/kiwix/kiwix-android/assets/34593983/61100373-338d-409c-bb5c-05e10ed9d1ee)  | ![Screenshot_20231215-163753_Dwds](https://github.com/kiwix/kiwix-android/assets/34593983/1247f089-3985-4ddf-8fa9-e74eabf3423d)  | …
=> Fixed: Made a small improvement to the sidebar entries for "About the app" and "Support app."

contrib/instrumentation.sh
Fixes #3613 
**Changes Made:**
Replaced == with `-eq` in the if [ $retry == 3 ] condition to avoid potential infinite loop.
Context:
The current bash script for running Android instrumentation tests and generating a Jacoco coverage report contains a bug in the while loop condition. The use of == for comparison in Bash is incorrect, and it may result in an infinite loop. This pull request addresses the issue by replacing == with `-eq`.
* Fixed: `$/${} is unnecessary on arithmetic variables` error while incrementing the count of retry variable. Since In Bash arithmetic expansion, the `$` is not needed when referencing variables see https://www.shellcheck.net/wiki/SC2004 for more details.
=> Fix potential infinite loop in bash script

core/src/main/java/org/kiwix/kiwixmobile/core/search/SearchFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModel.kt, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModelTest.kt
Fixes #3608
It removes debounce mechanics in order to have a better user experince.
=> Removed Debouncing mechanism

.github/workflows/ci.yml
Fixes #3615 
**Description**
This pull request addresses the redundancy in the GitHub Actions workflow for creating instrumentation coverage with the Android Emulator Runner. The current workflow contains duplicated code, and this PR refactors it into a single job definition with conditional parameter assignments based on the value of matrix.api-level.
=> Refactor GitHub Action for Emulator Runner Job Redundancy

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt
Fixes #3620 
* We are using the `applicationContext` to start the `ErrorActivity`, which is outside the `Activity`. Therefore, to initiate the activity with an external context of the `Activity`, we must include the `FLAG_ACTIVITY_NEW_TASK` flag in the intent. Without this flag, the activity will not start.
https://github.com/kiwix/kiwix-android/assets/34593983/5d483820-d403-48bc-8727-47e8dd143635
=> Fixed: ErrorActivity was not appearing in the non-debug version when the application crashed.

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt
Fixes #3611 
* This PR addresses the scenario where, for any reason, shared preferences and the database are retained on the device, and the list of ZIM files is visible in the library. However, the `MANAGE_EXTERNAL_PERMISSION` is not found, and when a user attempts to open a file, the application lacks the necessary permission. To improve this scenario, we now prompt the user for permission if it is not available when opening ZIM files from the library.
* Additionally, fixed the behavior of the swipe refresh layout if the user clicks on the "NO" button in the permission dialog, since it was showing loading progress and did nothing.
* Removed the lint suppression for "NewApi" which is unnecessary here.
**Issue**
https://github.com/kiwix/kiwix-android/assets/34593983/dde27b80-8bb7-4df2-89c5 …
=> Fixed: 3.9.0 Welcome screen does not run, and Kiwix does not prompt for permissions.

README.md
Fixes #3635 
As we've renamed the default branch from 'develop' to 'main,' we have accordingly updated the links.
=> Fixed: Links to Config.kt and CONTRIBUTING.md were not functioning in the README.md file.

custom/build.gradle.kts
Fixes #3640 
* We have excluded the universal APK from the variant list that is being uploaded to the Play Store.
* This exclusion is necessary because we cannot disable the universal APK, as it is required to set the version code for the bundle. Disabling the universal APK would result in the bundle version code being set exclusively for `x86_64`.
**After placing this fix the variant list not contains the universal apk**
```
[ApkVariantOutputImpl_Decorated{variantOutput=VariantOutputImpl(versionCode=property(java.lang.Integer, fixed(class java.lang.Integer, 3233620)), versionName=property(java.lang.String, fixed(class java.lang.String, 2023-12)), enabled=property(java.lang.Boolean, fixed(class java.lang.Boolean, true)), variantOutputConfiguration=VariantOutputConfigurationImpl(isUniversal …
```
=> Fixed: Resolved the issue where Google Play Store displayed an error during APK upload.

app/src/androidTest/java/org/kiwix/kiwixmobile/help/HelpRobot.kt, app/src/main/java/org/kiwix/kiwixmobile/help/KiwixHelpFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/help/HelpFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/KiwixDialog.kt, core/src/main/res/values/strings.xml
Fixes #3625 
* Removed the link from `zim_files_not_showing_description`.
* Modified the dialog for displaying the link in `PlayStoreRestrictionPopup`.
* Refactored the `rawTitleDescriptionMap`() method in `HelpFragment` to accommodate both strings and arrays for showing links inside the HelpFragment.
https://github.com/kiwix/kiwix-android/assets/34593983/e5599cf2-ce41-4f89-9eb5-070eaa89ebd2
=> Fixed: Extracted the website link from the string file for the Play Store restriction dialog.

buildSrc/src/main/kotlin/Versions.kt
Fixes #3644 
* Upgraded the `WebKit` version to the latest (from 1.3.0 to 1.7.0) to leverage improvements and bug fixes. This update is essential to address the issue with the latest `chromium` dependency, as outlined in #3644.
* Additionally, elevated the `androidx.annotation:annotation` dependency from `1.1.0` to `1.2.0` to meet the requirements of the updated WebKit version.
=> Upgraded `webkit` version to latest to work with latest `chromium` dependencies.

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt
Fixes #3650 
* This fix is particularly beneficial for slow storage or when the storage contains a large number of files, as the scanning process takes time to fully scan the storage and retrieve the ZIM files from it. If the user chooses a ZIM file via the file picker, our application is already aware that this ZIM file exists in the storage. Consequently, we save it directly to the database to ensure it appears on the local library screen.
* After the scanning process is complete, the ZIM file will not appear twice on the local library screen since we have implemented handling to prevent the display of duplicate ZIM files.
As you can see in the below video, if we select the ZIM file via file picker it is added to the local library screen, and scanning is still in progress. …
=> Fixed: When we select any ZIM file using the file picker, it is not being added to the library screen.

CONTRIBUTING.md, README.md
Fixes #3656 
* Fixed the badging of `Build Status` and `Codecov`.
* Since there are no `master` and `develop` branches, we have updated our `CONTRIBUTING.md` to reflect these changes.
=> Updated badges and documentation.

gradle.properties
Fixes #3634
* We utilize `Play Asset Delivery` in our bundle, housing the ZIM file within it. The size of the wikispecies ZIM file is 2.13GB. To process all resources inside the bundle, we require a minimum of 6GB of Java heap memory.
* Our CI is mainly failing on this task `shrinkBundleWikispeciesReleaseResources` which is necessary to reduce the size of the bundle.
* We have increased the `java heap memory` from 5GB to 6GB which is enough to create the bundle with wikispecies ZIM file.
=> Fixed the custom app (wikispecies, wikimed) bundle build problem.

app/src/androidTest/java/org/kiwix/kiwixmobile/webserver/ZimHostFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/webserver/ZimHostRobot.kt, contrib/instrumentation.sh, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/SaveSearchToRecentsTest.kt
Fixes #3627
* Addressed an issue with the `SaveSearchToRecentsTest` test, which occasionally failed. The primary cause of this was the recent modification to save the `RecentSearch` on a background thread using `coroutines`. In some cases, the test validates the output before the coroutine completes its execution. Consequently, we have adjusted our test case to properly wait for the coroutine to finish its work before validating the output.
* To fix `ZimHostFragment` test on API level 33 we have enabled the wifi programmatically on the emulator since it is by default not enabled on the emulator of API level 33.
* Improved test case for showing "Wifi connection dialog".
* Improved the permission.
* Removed the unnecessary logs from CI.
=> Fixed: Nowdays CI frequently failing on API level 24, and 33.

buildSrc/src/main/kotlin/custom/CustomApp.kt
Fixes #3677 
* Changed the date format from `YYDDD0` to `yyDDD0` to accurately calculate the version code for the last day of the year as well. See https://github.com/kiwix/kiwix-android/issues/3677#issuecomment-1914703084
=> Fixed: Release versions are lower in the custom apps.

core/src/main/java/org/kiwix/kiwixmobile/core/main/MainMenu.kt
Fixes #3623 
* Fixed the tab icon showing when there is no ZIM file opened in the reader which causes the unexpected UI behavior.
* Fixed "Read Aloud" menu item is showing when we close all tabs(which means currently no ZIM file is opened in the reader) so showing this button is redundant.
**Before Fix**
https://github.com/kiwix/kiwix-android/assets/34593983/93c44947-b200-4b25-9bed-cea0b05bab19
**After Fix**
https://github.com/kiwix/kiwix-android/assets/34593983/ed6fc494-a692-4959-8c74-b173af8db03d
=> Fixed: Inconsistent Visibility Behavior: Text and Button Overlay When Opening Tabs.

app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteRobot.kt
Parent Issue #3682
* We identified an issue where opening notes crashes the application if the particular ZIM file does not exist. To test this scenario, we have added corresponding test cases.
* These test cases cover both scenarios – when the ZIM file is deleted and when it is present.
=> Added test cases for notes.

buildSrc/src/main/kotlin/Versions.kt
Fixes #3693 
A new version of `java-libkiwix` has been released so we are using the new version of `java-libkiwix` in our project.
=> Upgraded `java-libkiwix` to 2.0.0

core/src/main/java/org/kiwix/kiwixmobile/core/zim_manager/MountPointProducer.kt
Fixes #3684 
* A few Samsung devices use the `f2fs` file system, such as the [Samsung Galaxy Note 10](https://www.sammobile.com/news/galaxy-note-10-uses-f2fs-not-ext4-file-system-whats-the-difference/) and `Samsung s23 ultra` confirmed in the below logs user has provided https://github.com/kiwix/kiwix-android/issues/3684#issuecomment-1917643339. Therefore, we have added the f2fs file system to the support 4GB filesystem list because this file system type allows the writing of files larger than 4GB.
```
MountInfo(device=/dev/block/dm-58, mountPoint=/data/user_de/0/org.kiwix.kiwixmobile, fileSystem=f2fs)
, MountInfo(device=/dev/block/dm-58, mountPoint=/data/data/org.kiwix.kiwixmobile, fileSystem=f2fs)
, MountInfo(device=/dev/block/dm-58, mountPoint=/data/user_de/0/com.google.android.gms, …
```
=> Fixed: Can't download 4+ gb files.

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt
Fixes #3643 
The crashes occurred in the Play Store version due to insufficient permissions for opening a file via `fileDescriptor`. To address this issue, we have modified the implementation to use the `file` instead of `fileDescriptor`. This adjustment ensures smooth operation in the non-Play Store version where we have permission to open a file via its path. In the Play Store version, it will display a proper error message to the user, preventing errors thrown by libkiwix.
=> Fixed: Version `3.9.1` was experiencing occasional crashes when setting the `SuggestionSearcher`.

core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/MainMenu.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.kt, core/src/main/res/layout/ic_tab_switcher.xml, core/src/main/res/values/strings.xml
Fixes #3668 
Added background for ripple
=> #3668 Ripple in Tabs Icon

app/src/main/java/org/kiwix/kiwixmobile/language/LanguageFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/PageFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/SearchFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/SimpleTextListener.kt
Fixes #2896 
* If the search/enter button is pressed and an article is found with the exact query, it will directly open that article. Otherwise, it will proceed with the regular search operation as before.
https://github.com/kiwix/kiwix-android/assets/34593983/a97f74ca-2a36-485b-a8d3-13cbde1ce874
=> Fixed: Added the ability to press Enter to skip the search.

app/src/main/java/org/kiwix/kiwixmobile/language/LanguageFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/language/adapter/LanguageListViewHolder.kt, app/src/main/java/org/kiwix/kiwixmobile/localFileTransfer/LocalFileTransferFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/libraryView/adapter/LibraryViewHolder.kt, app/src/main/res/layout/activity_language.xml, app/src/main/res/layout/fragment_destination_download.xml, app/src/main/res/layout/fragment_destination_library.xml, app/src/main/res/layout/item_library.xml, core/src/main/java/eu/mhutti1/utils/storage/adapter/StorageViewHolder.kt, core/src/main/java/org/kiwix/kiwixmobile/core/base/BaseFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ToolbarExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/MainMenu.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/PageFragment.kt, core/src/main/res/layout/activity_zim_host.xml, core/src/main/res/layout/item_book.xml, core/src/main/res/values/strings.xml
Fixes #3700 
Child Issue https://github.com/kiwix/kiwix-android/issues/3680
* Added content descriptions for all views reported by the Play Store, including RecyclerView, dialog's itemView, pause/resume/stop buttons, and many more.
* Created an extension function to handle both setting the content description to address Play Store accessibility issues and displaying hints to the user using ToolTipText. This function consolidates these tasks in one place, eliminating code duplication.
* Added a few new `contentDescription` for views, which are shown in the below images, if you have any better suggestions for these `contentDescripton`, it would be welcome.
* For the below change we do not have any direct function to get the `navigationIcon` from toolbar. So we make a helper function to get …
=> Fixed: Content labeling issue reported by the playstore.

core/src/main/res/layout/ic_tab_switcher.xml
Fixes #3702 
* Increase the clickable area of the tab switcher to align with the ideal menu item size, ensuring users can easily interact with it. Like other menu items.
| Before Fix  | After fix |
| ![BeforeFixTabSwitcher](https://github.com/kiwix/kiwix-android/assets/34593983/4ae56d6c-1bc6-4d34-ade1-3730e8eb6226)  | ![AfterFixTabSwitcher](https://github.com/kiwix/kiwix-android/assets/34593983/9b54c93f-a224-44b0-90ae-9b6612bb71b1) |
* Playstore showing a warning to convert the `text size` from `dp` to `sp`, but it was inside the `MaterialShowcaseView` lib so we can't change it.
| Playstore warning  | Inside lib |
| ![Screenshot from 2024-02-14 17-23-31](https://github.com/kiwix/kiwix-android/assets/34593983/d0c965e3-1ce9- …
=> Fixed: The Play Store has reported some implementation issues.

app/src/main/java/org/kiwix/kiwixmobile/language/LanguageFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, app/src/main/res/layout/item_download.xml, app/src/main/res/values/dimens.xml, core/src/main/java/org/kiwix/kiwixmobile/core/extensions/SearchViewExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/PageFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/SearchFragment.kt, core/src/main/res/layout/reader_fragment_content.xml, core/src/main/res/values/dimens.xml
Fixes #3701
Child Issue #3680
* Increased the height and width of the views to align with Play Store policies, while ensuring no impact on the UI (as illustrated in the images below).
| ![BeforeIncreasingHeighOfPauseStop](https://github.com/kiwix/kiwix-android/assets/34593983/810e94d9-2f23-4a1d-ab8b-80d6b4b2c71e)  | ![AfterincreasingheightPauseAndStop](https://github.com/kiwix/kiwix-android/assets/34593983/3cca9d5f-efeb-4a98-a616-de9c3925361e)  |
| ![Closeimagebefore](https://github.com/kiwix/kiwix-android/assets/34593983/15aaeca5-5921-49e5-a2bf-ac86687650a9)  | ![Closeimageafter](https://github.com/kiwix/kiwix-android/assets/34593983/52614f6d-c2d0-48e1-817e-b0d2a0f16401)  |
* For the tab switcher touch target issue we already …
=> Fixed: Addressed the touch target size issue reported by the Play Store.

core/src/main/res/values/strings.xml
"Goto" is used in some programming languages,
but not in English :)
=> Fix "go to" spelling

core/src/main/java/org/kiwix/kiwixmobile/core/base/BaseFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreSearchWidget.kt
Fixes #3718 
* The issue happened because we were setting the title directly on the toolbar. When quickly opening the bookmark screen from the widget, the toolbar was getting updates, but they weren't happening smoothly, leading to the title not showing up correctly. To fix this, we set the title on the `actionBar` instead of the toolbar. The `actionBar` handles titles and updates the toolbar in a more synchronized way, especially during fast transitions like opening the bookmark screen from the widget. Switching to `actionBar.title` makes sure the title updates reliably, solving the problem we faced during quick navigation.
* Removed the unnecessary `UnspecifiedImmutableFlag` lint suppression from CoreSearchWidget.
**Before Fix** …
=> Fixed: Bookmark screen title is set as "Kiwix" if we open the Bookmarks screen from Widget

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt
Fixes #3715 
Initially `ActionMode` is null when we are selecting ZIM files because the `ActionMode` is in the creation process that's why it is not showing the selected book count in the ActionMode title. So to fix this we are setting the value when the actionMode is created.
**Before Fix**
https://github.com/kiwix/kiwix-android/assets/34593983/c8f49a92-dd15-4013-9e9a-c55162f823b3
**After Fix**
https://github.com/kiwix/kiwix-android/assets/34593983/090a2ee4-6caa-4e0b-983d-08c1df157bc5
=> Fixed: Selected files count is not showing initially in LocalLibrary screen.

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
Fixes #3726 
Although the ZIM file is loaded, it does not appear in the reader because the "Open Library" button is already visible, and the content view is hidden at this point. To address this, we utilized our `reopenBook()` method when loading the ZIM file in the reader, which manages the visibility of these views.
**Before fix**
https://github.com/kiwix/kiwix-android/assets/34593983/afda9d7c-937a-4edf-952c-f18da2315952
**After Fix**
https://github.com/kiwix/kiwix-android/assets/34593983/34f5f145-e93f-457f-9490-bdc1b296a9c0
=> Fixed: Content is not displaying after opening the ZIM file from Chrome.

app/src/androidTest/java/org/kiwix/kiwixmobile/utils/files/FileUtilsInstrumentationTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/DocumentResolverWrapper.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt
Fixes #3710 
* Enhanced the queryForActualPath() method to retrieve the actual path for a URI. Users faced a `java.lang.UnsupportedOperationException: Unknown URI` exception when querying the contentResolver with an invalid URI. A check has been added to prevent such errors.
* On older devices, the download URI contains the full file path, causing the `documentProviderContentQuery` to fail in retrieving the path, leading to unexpected behavior (failure to open the ZIM file). The code has been improved to handle this scenario.
* In certain devices, the content URI prefix may differ, and using only `public_downloads` to obtain the actual path from the URI might not work if the device has a different URI prefix. The code has been enhanced to consider every possible content prefix when …
=> Add test cases for getLocalFilePathByUri() method.

app/src/androidTest/java/org/kiwix/kiwixmobile/localFileTransfer/LocalFileTransferTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/splash/KiwixSplashActivityTest.kt, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Versions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/settings/CorePrefsFragment.kt, core/src/main/res/layout/reader_fragment_content.xml, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModelTest.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/settings/CustomPrefsFragment.kt
Fixes #3730 
* Upgraded test cases and project dependencies.
* Refactor test cases and project code according to the new changes in dependencies.
| Dependency  | From | To |
| androidx.test.ext:junit  | 1.1.4 | 1.1.5 |
| org.junit.jupiter:junit-jupiter  | 5.9.1 | 5.10.2 |
| androidx.test:runner | 1.5.1 | 1.5.2 |
| com.squareup.okhttp3:mockwebserver | 4.9.0 | 4.10.0 |
| com.squareup.okhttp3:logging-interceptor | 4.9.0 | 4.10.0 |
| com.squareup.okhttp3:okhttp | 4.9.0 | 4.10.0 |
| io.mockk:mockk-android | 1.13.5 | 1.13.7 |
| io.mockk:mockk | 1.13.5 | 1.13.7 |
| org.assertj:assertj-core | 3.18.1 | 3.25..3 |
| com.squareup.leakcanary:leakcanary-android | 2.9.1 | 2.13 |
| com.squareup.leakcanary:leakcanary-android-instrumentation | 2.9.1| 2.13 | …
=> Upgraded many dependencies of our project.

core/src/main/java/org/kiwix/kiwixmobile/core/webserver/ZimHostFragment.kt
Fixes #3728 
* We implemented the `registerForActivityResult` method to handle notification permission, ensuring the hotspot starts seamlessly upon permission grant.
| <video src="https://github.com/kiwix/kiwix-android/assets/34593983/c23bb328-3b52-43e4-a002-5ffcd8d5b52d">  | <video src="https://github.com/kiwix/kiwix-android/assets/34593983/7736640c-3e48-41a8-9b66-8b6132cdff55"> |
* Improved the permission-asking scenario. Before it ask once for notification permission and at the second time it shows the custom dialog that shows why we need this permission. But we can ask permission twice in our application so we have improved the asking of permission. If the user denies this permission then we show the custom dialog with the …
=> Fixed: The WiFi hotspot no longer starts automatically after granting notification permission in Android 13 and above.

app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchRobot.kt
Fixes #3596 
* In this updated test case, we have addressed scenarios involving fast typing/deleting for search queries. Additionally, we implemented a test case where the user types with both short and long delays to ensure the following:
**Short delay:** Properly tests the cancellation of the previously searching task.
**Long delay:** Properly executes the search query letter by letter and ensures that there is no crash during the search.
* We are downloading the "stack exchange" ZIM file in our test case because this ZIM file yields many search results. Therefore, we download and perform all search operations on this file to simulate a real-world scenario, as our test ZIM file only contains three search results.
* The temporary ZIM file is deleted after performing the test to free up …
=> Added test cases for the search functionality.

app/src/androidTest/java/org/kiwix/kiwixmobile/ObjectBoxToLibkiwixMigratorTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/mimetype/MimeTypeTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/bookmarks/BookmarksRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/bookmarks/LibkiwixBookmarkTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/history/NavigationHistoryTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/reader/KiwixReaderFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/testutils/TestUtils.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/webserver/ZimHostFragmentTest.kt, contrib/instrumentation.sh
Fixes #3732 
* Refreshed the ZIM files list before deleting/checking for downloaded ZIM files in `DownloadTest` and `InitialDownloadTest` because sometimes data doesn't show on the `LocalLibraryScreen` after downloading the ZIM file, leading to test failures.
* Hiding the `Storage Restriction` dialog in `LibkiwixBookTest` and `MimeTypeTest` to not show this dialog in these test cases.
* Improved the temporary ZIM file path in `NoteFragmentTest` to properly display the ZIM file in the LocalLibrary screen so that it can be deleted in our test case.
* Enhanced the loading of ZIM files in `LocalLibraryTest`.
* Improved SearchFragmentTest that is sometimes failing on API level 30.
* Improved the ZIM file path in many scenarios so that the created ZIM file will show in the LocalLibraryScreen …
=> Fixed: Test cases are frequently failing on API level 33.

core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt
Fixes #3734 
* For the issue `Caused by java.lang.ClassNotFoundException: org.chromium.base.JniAndroid$UncaughtExceptionException
` it is related to the `org.chromium` lib and we recently upgraded our webview dependency in https://github.com/kiwix/kiwix-android/issues/3644.
* Fixed where restarting the app was not working on Android 11 and above.
|  <video src="https://github.com/kiwix/kiwix-android/assets/34593983/d7bc39d2-1fff-42e1-9164-c97fb6b6fa3b"> | <video src="https://github.com/kiwix/kiwix-android/assets/34593983/843d9ab4-5f72-43e4-8525-58c4a2b2b169">  |
=> Fixed: PlayStore reported an error for Encyclopédie médicale WikiMed app.

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
Fixes #3740 
Used onReadAloudStop method on close tab
=> [Fix]: Read aloud will stop on close tab

core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileLogger.kt
Fixes #3751 
* Changed intent type from `vnd.android.cursor.dir/email` to `text/plain` to ensure compatibility with all applications.
* Now attaching a log file containing all details. WhatsApp has a limitation on message sharing, so if details are lengthy, they might get cut off. We ensure complete details by providing the log file attachment.
* Improved `writeLogFile` method. Now we are deleting the directory from the storage if exist which contains the previously generated logs files since we were deleting the existing file if any are present in the storage but our fileName contains the `currentTimeMillis` so this condition will never be true, and all the logs files are stored in that directory, which takes the memory in user device, so now we are removing the previously saved log …
=> Fixed: [Bug] Diagnostic Report not doing anything.

core/src/main/java/org/kiwix/kiwixmobile/core/data/remote/ObjectBoxToLibkiwixMigrator.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/bookmark/adapter/LibkiwixBookmarkItem.kt
Fixes #3756 
Recent version of custom apps usages the `assetFileDescriptor` which does not have any path that's why migration is not working in these versions of custom apps. However, with apk version of custom apps migration is working fine. So to address this issue we have adjusted our code to work with assetFileDescriptor as well.
=> Fixed: Migration of bookmarks is not working with recent versions of custom apps.

.github/workflows/ci.yml, app/src/androidTest/java/org/kiwix/kiwixmobile/ObjectBoxToLibkiwixMigratorTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/main/TopLevelDestinationTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/library/LibraryRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/reader/KiwixReaderFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/utils/files/FileUtilsInstrumentationTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/webserver/ZimHostFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/webserver/ZimHostRobot.kt
Fixes #2096 
* Improved the deleting of zim files in localibrary, since we already paused for a second to check if the delete dialog is displayed or not, and again we are waiting before clicking on it. The same issue for while clicking on the PlayStoreRestrictionDialogTest where we are first waiting for the dialog to visible and then waiting for clicking on it. So we have removed the second wait since this dialog is displaying in both test cases.
* Improved the TopLevelDestinationTest. Because we were testing the drawer options fragments (Settings, Bookmarks, etc) from the download screen and when we pressed the back button it came to the download screen and refreshed its data due to this our next functionality had to wait to finish this. Now we are testing all the navigation screens from …
=> Fixed the CI on api level 33 and reduce the CI timing.

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt
Fixes #3762 
* The issue occurs because we are not opening the zim file in the reader because it does not exist in the fileSystem but we are [loading the saved URL in webView](https://github.com/kiwix/kiwix-android/blob/d26c1d7daf3bb4dea40b24cf2ab5d0fd24a3ad60/app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt#L99) of that file which does not exist. So when we are switching between fragments then we are opening the previously saved zim file but with the wrong URL which leads to this unexpected behavior. So to fix this we are closing the previously opened book if the new zim file does not exist in the fileSystem.
| Before fix  | After Fix |
| <video src="https://github.com/kiwix/kiwix-android/assets/34593983/61d8e6bf-be71- …
=> Fixed: Opening ZIM file from history that does not exist in fileSystem leads to execpected UI behavior (When already a ZIM file opened in the reader).

app/src/androidTest/java/org/kiwix/kiwixmobile/ObjectBoxToLibkiwixMigratorTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/data/remote/ObjectBoxToLibkiwixMigrator.kt
Fixes #3765 
* Adding the bookmarks in libkiwix even if the bookmark-related files exist or not in fileSystem. This will ensure all the bookmarks will show on the bookmark screen, and it will improve the user experience.
* Implemented test cases to verify this functionality and to test the migration for new custom apps.
=> Fixed: Bookmarks should show in new version of kiwix(`3.10.0`) even the bookmarks related files exist or not in fileSystem.

core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileLogger.kt
Fixes #3769 
* Efficiently creating the log file directory so that it will work properly on every Android version.
=> Fixed: Improved the creation of logDirectory on lower devices (Below Android 10).

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreWebViewClient.kt
Fixes #3647 
* The error toast message is no longer displayed if a URL fails to load. Instead, a debug error message is logged.
* Restricted the loading of external resources when rendering the pages.
| <video src="https://github.com/kiwix/kiwix-android/assets/34593983/bd96889e-7636-4271-855d-029e05781601">  | <video src="https://github.com/kiwix/kiwix-android/assets/34593983/6bea7a08-a40b-4c81-bf3b-300211c88be6">  |
=> Fixed: Spurious message: "Error: Loading article (Url: https://uploadwikimedia.org/wikipedia/commons/6/65/Lock-green.svg"

README.md
Issue #3776 
Our project requires `Java 11` to run. Therefore, developers should set the `Gradle JDK` to `Java 11`. We have included this information in the `Build Instructions` section of the `README` file.
=> Added information about JDK configuration to the README file.

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/res/values/strings.xml
Fixes #3774 
Fixed a static toast which is showing when there is an error in restoring the tabs. We have moved this static error message to our string file so that it will be translated in every language and user will see the error message in their own language.
=> Fixed: If restoring the tabs fails it shows the message in English language even if you are using the application in other languages.

team-props/git-hooks/pre-commit.sh
Fixes #3779 
Refactored the error message to show the correct information to the developers, since our project needs `JDK11` to run so we have added this JDK version to the error message. Also, corrected the gradle wrapper version in this message.
=> Fixed: The wrong message appears while committing the code, if Lint/Static analysis has failed.

.github/workflows/ci.yml, app/src/androidTest/java/org/kiwix/kiwixmobile/ObjectBoxToLibkiwixMigratorTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/help/HelpFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/intro/IntroFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/localFileTransfer/LocalFileTransferTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/main/TopLevelDestinationTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/mimetype/MimeTypeTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/PlayStoreRestrictionDialogTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/library/LibraryRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/bookmarks/LibkiwixBookmarkTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/history/NavigationHistoryRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/history/NavigationHistoryTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/reader/EncodedUrlTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/reader/KiwixReaderFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/settings/KiwixSettingsFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/splash/KiwixSplashActivityTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/testutils/TestUtils.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/utils/StandardActions.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/webserver/ZimHostFragmentTest.kt, contrib/instrumentation.sh
Fixes #3781 
* We are clearing the data of the application on the 2nd and 3rd run, and the test cases are running normally so now we are clearing the application data on the first run as well.
* Improved the `instrumentation.sh` script to clear the application data.
* Additionally, we've implemented drawer closure in `LanguageFragmentTest`, `LocalFileTransferTest`, `NavigationHistoryTest`, `ZimHostFragmentTest`, and `NoteFragmentTest`. These tests sometimes encountered an open navigation drawer due to test failures or process crashes.
* Enhancements have been made to the `testShowCaseFeatureShowOnce` test case. It's now independent of other test cases, ensuring it remains unaffected in the event of a test process crash or failure.
* Improved the `closeSystemDialogs` method since it was …
=> Fixed: Sometimes all the test cases crash on first time and some fail due to the navigation drawer being visible on the window. (Android 13).

app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/help/HelpFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/localFileTransfer/LocalFileTransferRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/localFileTransfer/LocalFileTransferTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/main/TopLevelDestinationRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/main/TopLevelDestinationTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/library/LibraryRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/bookmarks/BookmarksRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/history/HistoryRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/history/NavigationHistoryTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/reader/KiwixReaderFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/settings/SettingsRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/splash/KiwixSplashActivityTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/testutils/TestUtils.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/webserver/ZimHostFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/webserver/ZimHostRobot.kt, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/SaveSearchToRecentsTest.kt
The last CI failed in https://github.com/kiwix/kiwix-android/pull/3738 due to buffer size exceeding https://github.com/kiwix/kiwix-android/actions/runs/8643117644/job/23695477416?pr=3738#step:5:8087, so in this PR, we are fixing that issue.
* The allocated buffer size was exceeded due to the retry policy of our test cases. When we retry a test, more objects are allocated to memory, causing this issue.
* When retrying a test case that failed initially, the "MANAGE_EXTERNAL_STORAGE" permission dialog appears on the window due to clearing the preferences in our test case. Therefore, we have removed that code from our test cases.
* Enhanced the test code to detect the views inside the dialogs since our test cases fail due to these dialog's views, which take a moment to appear on the window, …
=> Fixed allocate_buffer_size on CI.

.github/workflows/ci.yml
Fixes #3784 
* Changed the runner of CI to `ubuntu-22.04` to boost the performance.
*  Enabled the `fail-fast` option in CI, if any of the jobs fail on any emulator then it will cancel all jobs running on other emulators in the current process so that other PRs do not need to wait to finish this job. Also, this will reduce the running timing on CI since if a job fails on any emulator we need to fix that so running other jobs does not make sense. So we are canceling those jobs if any fail.
* Introducing caching for AVD to run test cases faster. It reduced the emulator's boot time. [More details]( https://github.com/ReactiveCircus/android-emulator-runner?tab=readme-ov-file#usage--examples)
* Removed the 'disk-size' option since it was throwing an error, causing the emulator not to boot. …
=> Changing runner to `ubuntu-latest`.

app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/base/BaseActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomMainActivity.kt
Fixes #3794 
* This error was not reproducible on my device and emulators too. But playstore reported this error, and there are 8 occurrences in the last 60 days. So I have check the code and found that code is causing the error that is unused for `KiwixMainActivity`.
* The error was occurring when launching the `KiwixMainActivity`. At this moment, `coreComponent` was in creation process so it is not initialized at this moment, and we are passing this component in our `KiwixMainActivity` through interface for injection of this activity. But we are not using `coreComponent` object in our `KiwixMainActivity` so passing it to the activity is unused because we are injecting this activity through `cachedComponent`, and this unused object causing the error. So we have removed this interface …
=> Fixed: PlayStore reported `UninitializedPropertyAccessException` when launching the `KiwixMainActivity`.

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
Fixes #3790 
This error was occurring due to the user frequently clicking the close icon of the same tab, in this situation first click closes the tab, and the second immediate click again triggers the `closeTab` function but recyclerView does not have the valid view for this position because it is in removing process so this makes this view invalid and recyclerView returns the `-1` index for invalid views. So this was the reason for this issue, to address this issue we have added a check in our `closeTab` method if the incoming index is `-1` then it will not execute the further code.
| Issue  | Fix |
| <video src="https://github.com/kiwix/kiwix-android/assets/34593983/898873c4-9bf0-4201-9b27-6b528b3db7b8">  | <video …
=> Fixed: Play Store reported a crash error when closing the tabs.

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
Fixes #3792 
* This issue occurred because when the Close all tabs button was first clicked, it closed all tabs and stored them into the temp list, emptying the main list. However, if the button was immediately clicked again, it would attempt to copy the main list to the temp list, which was already empty. To address this issue, we have disabled the button after the first click to prevent such situations, as they can occur due to accidental clicks.
* Enhanced the behavior of the "Tabs closed" snackBar. Now, when the user clicks the "UNDO" button to restore a tab, we disable the snackBar's "UNDO" button to prevent subsequent clicks. This prevents the addition of multiple tabs if the "UNDO" button is clicked multiple times, as such restored tabs can lead to unexpected behavior.
| Before FIx …
=> Fixed: Tabs are not restoring if we accidentally click twice on the Close all tabs button.

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
Fixes #3796 
The error is not reproducible on my device and emulators too. But playStore reported this error so somehow this error is occurring. So to fix this issue we are now only performing the click action when the item is available in the `DocumentSectionsList`. This will avoid this type of error.
=> Fixed: PlayStore reported IndexOutOfBoundsException, when we are selecting the item from rightDrawer.

CONTRIBUTING.md
Fixes #2360 
Added documentation for `Git Hooks` in the `CONTRIBUTING` file, and added the guide on how the devs can avoid running the `pre-commit` git hook.
=> Added documentation for `Git Hooks` in the `CONTRIBUTING` file.

app/src/androidTest/java/org/kiwix/kiwixmobile/mimetype/MimeTypeTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/reader/EncodedUrlTest.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/StorageObserver.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/notes/viewmodel/effects/ShowOpenNoteDialog.kt, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimReaderContainer.kt, core/src/test/java/org/kiwix/kiwixmobile/core/StorageObserverTest.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt
Fixes #3805 
* We are now creating the ZimFileReader object on the background thread to not block the UI thread which sometimes causes the ANR because sometimes UI was frozen due to the creation of ZimFileReader with a large file.
* Refactored our functionality to support this new change.
* Refactored the test cases according to this functionality.
* Added the test cases, for testing the scenario where the zim file was not properly loading after opening the note on the notes screen to ensure that this functionality should work properly.
=> Fixed: Sometimes setting the `org.kiwix.libzim.Archive.setNativeArchive` crashes the application.

core/src/main/res/layout/ic_tab_switcher.xml
Fixes #3812 
* Changed the width and height of `ic_tab_switcher_text` to  `wrapContent`  instead of fixed width and height which prevents to expansion of the view if there is more content to display.
* To maintain the current design we have added the `minHeight` and `minWidth` for textView otherwise the background was showing very odd.
* For other issues that are showing in the below screenshots, we can not place a fix for these issues, since these are inside the library and there are no methods for setting the `textSize`. However, the issue is we need to change the `textSize` from `dp` to `sp`, and it is only show once when this feature is first time used.
=> Fixed `Implementation` issue reported by the playstore.

app/src/main/res/layout/fragment_local_file_transfer.xml, core/src/main/java/org/kiwix/kiwixmobile/core/help/HelpFragment.kt, core/src/main/res/layout/fragment_help.xml
Fixes #3810 
* Added the content description for the `send report` image, and fixed the sizing issues of `send feedback` and `send report` `textView` so that users can easily click on these views.
* Added content description for `File transfer list recyclerview`.
* There is only one accessibility warning left which is `Multiple items have the same description` it is because recyclerview items have the same content description and we can ignore this type of error because 2 views can have the same content description because their functionality can be same.
=> Fixed: `Content labeling` issue reported by the playstore.

contrib/instrumentation.sh
Fixes #3819 
* Modified the `instrumentation.sh` script to delete the (app, test app) if already installed in the device before running the test cases.
=> Fixed: Ci is continuously failing.

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/ServiceWorkerUninitialiser.kt
Fixes #3809 
* Rectified the `ServiceWorkerUninitialiser` code to appropriately uninitialize the service worker. Previously, when the uninitializing code ran from the JavaScript interface, we directly called the function, which sometimes functioned correctly but sometimes did not. To address this inconsistency, we are now invoking that function to ensure the main page loads after the service worker is uninitialized.
* Rectified the syntax error in the `ServiceWorkerUninitialiser` JavaScript code, which was causing an issue on API level 24. Consequently, the main page failed to load on this API level. We've refactored our code to ensure compatibility across all API levels.
* Now that our service is functioning correctly, there's no need to explicitly load the main page. Upon service worker …
=> Fixed: issue with front page of Zim on a USB stick loading.

app/src/main/res/layout/fragment_intro.xml, app/src/main/res/layout/item_intro_1.xml, app/src/main/res/layout/item_intro_2.xml, app/src/main/res/layout/item_language.xml, core/src/main/res/drawable/ic_feedback_orange_24dp.xml, core/src/main/res/layout/activity_kiwix_error.xml, core/src/main/res/values/colors.xml
Fixes #3813 
* Changed the background color of `ErrorActivity` and the checkbox to resolve the issue.
| Before (Night mode)  | Before (Light mode)  | After (Night mode) | After (Light mode)  | 
| ------------- | ------------- | ------------- | ------------- |
| ![BeforeNightMode](https://github.com/kiwix/kiwix-android/assets/34593983/068098da-db15-4184-a3a8-ecc7b606b16d)  | ![BeforeLightMode](https://github.com/kiwix/kiwix-android/assets/34593983/c386b198-14e1-4b68-ac6c-ad30bcb39843)  | ![AfterNightMode](https://github.com/kiwix/kiwix-android/assets/34593983/593a2118-7a46-4acf-b0c2-e9a830021481) | ![AfterLightMode](https://github.com/kiwix/kiwix-android/assets/34593983/81805258-79dc-41f4-8444-3af6a57e59fe) |
* Added the background color in `IntroFragment` to resolve the issue, it is the …
=> Fixed: `Low contrast` issues reported by the playstore.

app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/history/HistoryRobot.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/PageFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/bookmark/BookmarksFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/history/HistoryFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/notes/NotesFragment.kt, core/src/main/res/values/strings.xml
Fixes #3825 
* Added correct description to `delete` button on `HistoryFragment`, and `NotesFragment`.
| Notes screen  | History screen |
| ![ClearNotesFixed](https://github.com/kiwix/kiwix-android/assets/34593983/cda84236-6bcb-48ec-9074-a51e950ed39f) | ![ClearHistoryFix](https://github.com/kiwix/kiwix-android/assets/34593983/f2214f0a-7417-4286-893a-7f46724d6958) |
* Refactored the test case according to this new change.
* Sometimes `actionOnItemAtPosition` method gives an internal error, and does not perform the desired operation and fails the `NoteFragmentTest`. So we have moved it inside the `testFlakyView` method so that if there is any internal error occurs it retries this action.
```kotlin
org.kiwix.kiwixmobile.note.NoteFragmentTest > …
```
=> Fixed: The Delete icon is showing wrong content description on the notes and history screen.

app/src/main/AndroidManifest.xml
Fixes #3808 
* Removed the URL type deep link since we are mainly using deep links for opening zim files in the application, and URLs type deep links are for downloading the content not for opening the ZIM files so we are removing these deep links from our application.
* Now user can normally download the zim files from (outside Kiwix) like other zim files.
=> Fixed: PlayStore showing deep linking issue for URLs schema.

app/src/androidTest/java/org/kiwix/kiwixmobile/deeplinks/DeepLinksTest.kt, app/src/main/AndroidManifest.xml, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/DocumentResolverWrapper.kt
Fixes #3832 
* Corrected the deep linking for the `content` type scheme.
* Improved the handling of zim files if the user opens from the storage and our application is not in the background.
* Improved the opening of Zim files when we open directly from storage.
* Also, added necessary comments on the changes to properly understand why we have done these changes.
* Added test cases for testing the deep linking in our application.
https://github.com/kiwix/kiwix-android/assets/34593983/b597d9bc-af18-4f9a-ab9c-e03d21f34015
=> Fixed: Zim files are not opening with kiwix when clicking from the storage.

.github/workflows/ci.yml, README.md, buildSrc/src/main/kotlin/Config.kt, core/src/main/java/org/kiwix/kiwixmobile/core/compat/Compat.kt, core/src/main/java/org/kiwix/kiwixmobile/core/compat/CompatHelper.kt, core/src/main/java/org/kiwix/kiwixmobile/core/compat/CompatV25.kt, core/src/main/java/org/kiwix/kiwixmobile/core/compat/CompatV33.kt, core/src/test/java/org/kiwix/kiwixmobile/core/utils/NetworkUtilsTest.kt
Fixes #3783 
* Updated the `README.md` file for this new change.
* Removed the API level 24 from CI and added the API level 25 since now our minimum SDK version is 25.
* Renamed CompatV24 file since we have upgraded the minimum SDK version so this fileName was irrelevant.
* Added the `heap size` in the API level 25 emulator.
=> Upgraded the minimum SDK version to `25`.

.github/workflows/nightly.yml, app/build.gradle.kts
Fixes #3838 
* Uploading nightly APK with a released signature so that APK can update, if a user downloads the new version of nightly like our released APK.
* Modified the nightly CI for this change.
=> Uploading nightly APK with released signature.

app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/settings/SettingsRobot.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/libraryView/adapter/LibraryViewHolder.kt
Fixes #3666 
* It was due to we were using the hardcoded string for checking the pause state of downloading so pausing and resuming are working fine in the English version and do not work in other languages.
* Added test cases for checking this scenario so that we can avoid this type of error in the future.
Credit goes to @artar94 for finding the real issue.
=> Fixed: Unable to restart download after pausing.

core/src/main/java/org/kiwix/kiwixmobile/core/webserver/KiwixServer.kt, core/src/main/java/org/kiwix/kiwixmobile/core/webserver/ZimHostFragment.kt
Fixes #3845 
* Added a check for checking the `MANAGE_EXTERNAL_STORAGE` permission when starting the server in the non-playStore variant. If there is no permission, then it asks for permission to avoid the crash due to permission lack for file.
* Improved the permission asking when the user tries to start the server in all variants and all versions of Android so that it will ask storage(read/write) permission for below Android 13 in non-playStore variant. Also, ask for the `MANAGE_EXTERNAL_STORAGE` permission in Android 11 and above. This check ensures that without the storage and `MANAGE_EXTERNAL_PERMISSION` user can not start the server. Because if the application does not have storage permission then it crashes when creating the `Archive` object.
* Fixed: application crashing when …
=> Fixed: application was crashing when starting the `kiwix server`.

app/src/androidTest/java/org/kiwix/kiwixmobile/ObjectBoxToLibkiwixMigratorTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/deeplinks/DeepLinksTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/help/HelpFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/intro/IntroFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/localFileTransfer/LocalFileTransferTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/main/TopLevelDestinationTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/mimetype/MimeTypeTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/PlayStoreRestrictionDialogTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/bookmarks/LibkiwixBookmarkTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/history/NavigationHistoryTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/reader/EncodedUrlTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/reader/KiwixReaderFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/reader/ZimFileReaderWithSplittedZimFileTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/settings/KiwixSettingsFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/settings/SettingsRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/webserver/ZimHostFragmentTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimReaderContainer.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/SearchFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModel.kt, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModelTest.kt
Fixes #3848 
* Now we are using the same `ZimFileReader` object to search the articles. It reduces the search timing and avoids unnecessary allocation of objects in memory.
* Refactored the `SearchViewModelTest` for this change.
* After this change, a few codes are become unused so we have removed that from our application.
* Fixed the test cases that were failing if `testPauseAndResumeInOtherLanguage` failed due to any reason. Because the language remains changed and other test cases will fail. Like it was failed in this PR on API level 30(https://github.com/kiwix/kiwix-android/actions/runs/9113243814/job/25054265367).
* Also, improved our `DownloadTest`, because after changing the language of the application online content will change according to the new language so now we are using a …
=> Fixed: Improve article search in our application.

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt
Fixes #3851 
* Fixed the fullScreen mode not properly working on Android 11 and above(It was showing the blue line on the top), and also not showing the navigation options so that the user can close the `fullScreenMode` while pressing the back button in the navigation. Now it started showing the `fullScreenMode` like in earlier version of kiwix.
* Also improved the `fullScreenMode` for lower versions of Android. We have created an extension function so that we can easily reuse the code when we open/close the `fullScreenMode` for a video.
* Fixed the BottomToolbar's options was showing when the application is in the background in `fullScreenMode` and the user opens again the application.
* When the application is running in the `fullScreenmode` and we close the `fullScreenMode` of a video …
=> Fixed: Broken fullscreen mode with `3.10`.

app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchRobot.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
Fixes #3854 
*  The issue was caused by a service worker URL being loaded in the WebView. When the back button was pressed, the callback redirected to the mainPage, causing an infinite loop. To address this, we clear the WebView history if the URL is the main page URL, as WebView cannot clear the history for the current page. If the current URL is a service worker URL and we clear the history, it will not remove the service worker from the history, so it will remain. Therefore, we clear the history when the main page is loaded for the first time.
* Also, fixed the back button problem with service worker ZIM files.
* Improved the showing of `bottomToolbar` visibility code, the null check was placed on the wrong views.
* Preventing saving the Service worker url in history.
* Added necessary …
=> Fixed: If there is a zim file loaded in the reader that has the service worker in it so we can't exit the application with a back Button.

app/src/androidTest/java/org/kiwix/kiwixmobile/KiwixRoomDatabaseTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/ObjectBoxToRoomMigratorTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/RecentSearchRoomDaoTest.kt, buildSrc/src/main/kotlin/Libs.kt, buildSrc/src/main/kotlin/Versions.kt, buildSrc/src/main/kotlin/plugin/AllProjectConfigurer.kt, core/src/main/java/org/kiwix/kiwixmobile/core/dao/RecentSearchRoomDao.kt, core/src/main/java/org/kiwix/kiwixmobile/core/dao/entities/RecentSearchEntity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/dao/entities/RecentSearchRoomEntity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/data/KiwixRoomDatabase.kt, core/src/main/java/org/kiwix/kiwixmobile/core/data/Repository.kt, core/src/main/java/org/kiwix/kiwixmobile/core/data/remote/ObjectBoxToRoomMigrator.kt, core/src/main/java/org/kiwix/kiwixmobile/core/di/components/CoreComponent.kt, core/src/main/java/org/kiwix/kiwixmobile/core/di/modules/ApplicationModule.kt, core/src/main/java/org/kiwix/kiwixmobile/core/di/modules/DatabaseModule.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModel.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/DeleteRecentSearch.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/SaveSearchToRecents.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModelTest.kt, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/DeleteRecentSearchTest.kt, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/SaveSearchToRecentsTest.kt
Fixes #3111 
* Introduced the `Room` database in our project.
* Now all the new recent searches will be saved in the room database instead of `objectbox`.
* We have added the migration code for previously saved `recent searches` from `objectbox` to `room`.  This will ensure that the previously saved `recent searches` will be shown to the user.
* Added the test cases for testing the migration with different scenarios, and with large data sets. Also, added the test cases for `RecentSearchRoomDaoTest`, and `KiwixRoomDatabaseTest` to test that it can save the different types of data.
=> Room introduction & migration of recent search

app/src/androidTest/java/org/kiwix/kiwixmobile/KiwixRoomDatabaseTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/ObjectBoxToRoomMigratorTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/roomDao/HistoryRoomDaoTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/roomDao/NoteRoomDaoTest.kt, buildSrc/src/main/kotlin/Libs.kt, buildSrc/src/main/kotlin/plugin/AllProjectConfigurer.kt, core/src/main/java/org/kiwix/kiwixmobile/core/dao/HistoryRoomDao.kt, core/src/main/java/org/kiwix/kiwixmobile/core/dao/NotesRoomDao.kt, core/src/main/java/org/kiwix/kiwixmobile/core/dao/PageDao.kt, core/src/main/java/org/kiwix/kiwixmobile/core/dao/entities/NotesRoomEntity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/data/DataSource.kt, core/src/main/java/org/kiwix/kiwixmobile/core/data/KiwixRoomDatabase.kt, core/src/main/java/org/kiwix/kiwixmobile/core/data/Repository.kt, core/src/main/java/org/kiwix/kiwixmobile/core/data/remote/ObjectBoxToRoomMigrator.kt, core/src/main/java/org/kiwix/kiwixmobile/core/di/components/CoreComponent.kt, core/src/main/java/org/kiwix/kiwixmobile/core/di/modules/DatabaseModule.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/MainRepositoryActions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/bookmark/viewmodel/BookmarkViewModel.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/bookmark/viewmodel/effects/ShowDeleteBookmarksDialog.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/history/viewmodel/HistoryViewModel.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/history/viewmodel/effects/ShowDeleteHistoryDialog.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/notes/adapter/NoteListItem.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/notes/viewmodel/NotesViewModel.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/notes/viewmodel/effects/ShowDeleteNotesDialog.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/viewmodel/PageViewModel.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/viewmodel/effects/DeletePageItems.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt, core/src/test/java/org/kiwix/kiwixmobile/core/page/history/viewmodel/HistoryViewModelTest.kt
Fixes #3113 
* Now all the new notes will be saved in the room database instead of `objectbox`.
* We have added the migration code for previously saved notes from `objectbox` to `room`. This will ensure that the previously saved notes will be shown to the user.
* Added the test cases for testing the migration with different scenarios, and with large data sets. Also, added the test cases for `NoteRoomDaoTest`, and `KiwixRoomDatabaseTest` to test that it can save the different types of data.
* We have refactored our code to use PageDao for managing data related to Bookmarks, Notes, and History. With the ability to return Flowable from the Room database, the BasePageDao interface has become unnecessary. Consequently, we have removed BasePageDao and streamlined our code to use PageDao, …
=> Migrated Notes to room database.

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
Fixes #3861 
* Catching the exception thrown by the libkiwix with splitted ZIM files when there is a 0 size extra zim chunk so that the application will not crash when libkiwix throw this type of errors.
=> Fixed: Saving bookmarks in the zim-split splitted ZIM files are crashing the application, when there is a 0 size extra zim chunk.

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreWebViewClient.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt
Fixes #3869 
We didn't account for the scenario where a user long-clicks on an image that contains an anchor tag with a URL. For now, we only check when a link is loading(when the user simply clicks on the image button), and if the link is unsupported by Kiwix, we show the save/open dialog. Now, we are also checking for this scenario on long clicks. So now the "Open in new tab" does not show for these types of files.
https://github.com/kiwix/kiwix-android/assets/34593983/b0c17d70-30a7-480f-8a12-a2d0f0ba0c69
=> Fixed: Long clicking on Download button in epub ZIM files shows the `Open in new tab` dialog which leads to a blank page.

core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimReaderContainer.kt
Fixes #3860 
* YouTube videos were not playing in the Android reader because the response code for the video URL was 206 (Partial Content). The `Content-Range` header of the incoming data was being set incorrectly. This happened because the `data` had a size of 0, as the content was being written on the IO thread (to avoid blocking the UI thread) when loading in the WebView. Due to this, the `Content-Range` was set incorrectly, preventing the YouTube video from playing.
* To fix this, the correct content length is now passed to the `Content-Range` header, ensuring that the video plays correctly.
https://github.com/kiwix/kiwix-android/assets/34593983/6f1e2911-38a6-423f-ae4d-e7386d46e21e
=> Fixed: Zimit2 Youtube video still doesn't play on Android reader.

app/src/androidTest/java/org/kiwix/kiwixmobile/mimetype/MimeTypeTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/reader/EncodedUrlTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/reader/ZimFileReaderWithSplittedZimFileTest.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, buildSrc/src/main/kotlin/custom/CustomApps.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimReaderContainer.kt, core/src/main/java/org/kiwix/kiwixmobile/core/webserver/KiwixServer.kt, custom/build.gradle.kts, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomFileValidator.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt
Fixes #3511 
* Introduced the splitting zim file with 500MB for custom apps. Since the bundle has a limit for a file to upload it uses the play asset delivery mode, and for new custom apps, playStore does not allow to upload the apk (with apk we can upload more than 1GB file). So to address this issue we have introduced a feature in libzim where we can load the zim files via the fd list.
* We have modified our code to upload the files with 500MB chunks in the asset folder, and later we are accessing these files from the asset folder and creating the archive object with the help of the new libzim feature.
* Currently CI will fail because we are using the new libzim feature in this PR. But currently new binding of `java-libkiwix` is not released once the new binding is released and we start …
=> Fixed: Not able to upload 512MB+ custom apps anymore.  

core/src/main/java/org/kiwix/kiwixmobile/core/CoreApp.kt, core/src/main/java/org/kiwix/kiwixmobile/core/ServiceWorkerInitialiser.kt
Fixes #3878 
Thanks to @Popolechien for sharing this crash report in https://github.com/kiwix/kiwix-android/issues/3600#issuecomment-2164966644
* ServiceWorker was being initialized every time the `CoreApp` instance was created. When the application crashed, `ErrorActivity` was invoked to send a crash report, running in a separate process. In this new process, the ServiceWorker was also being initialized.
* Upon user interaction (e.g., clicking "No Thanks" to relaunch the app), the application returned to the main process, leading to a second initialization of the ServiceWorker with the same data directory, causing a crash.
* Since `ErrorActivity` does not require any WebView-related functionality, it is unnecessary to initialize the ServiceWorker in this process.
* The fix involves …
=> Fixed ServiceWorker Initialization Issue

app/src/androidTest/java/org/kiwix/kiwixmobile/core/di/components/TestComponent.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchFragmentTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/di/components/CoreComponent.kt, core/src/main/java/org/kiwix/kiwixmobile/core/di/modules/MutexModule.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/SearchFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchState.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModel.kt, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchStateTest.kt, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModelTest.kt
Fixes #3877 
* There was a concurrency issue in the search functionality in a very specific condition, causing data corruption and race conditions when users searched for different terms simultaneously.
* Introduced a global Mutex in the SearchResultsWithTerm class to control access to search results.
* Applied the Mutex in the SearchState class to lock execution and ensure that only one coroutine can process search results at a time. Since here we are getting the data from libzim this global mutex will prevent getting data via multiple coroutines.
* Enhanced retrieval of suggestion lists from libzim.
* Implemented task cancellation if the fragment is not visible.
* Refactored `getVisibleResults` into a suspend method to ensure efficient job cancellation.
* Handled exceptions thrown by …
=> Fixed: Xapian crash scenarios.

app/src/main/res/values/strings.xml
Fixes #3884 
Outdated text was showing when a zim file could not open in the Kiwix, this text was for the older UI, and now we have removed the "Device Tab" from the "Library" screen so this text is outdated and misleading the users. so we have changed this text according to the new UI.
=> Fixed outdated text showing when a zim file could not open.

app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/bookmarks/BookmarksRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/bookmarks/LibkiwixBookmarkTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/bookmark/adapter/LibkiwixBookmarkItem.kt, core/src/test/java/org/kiwix/kiwixmobile/core/page/PageTestHelpers.kt, core/src/test/java/org/kiwix/kiwixmobile/core/page/bookmark/viewmodel/BookmarkStateTest.kt, core/src/test/java/org/kiwix/kiwixmobile/core/page/bookmark/viewmodel/BookmarkViewModelTest.kt, core/src/test/java/org/kiwix/kiwixmobile/core/page/bookmark/viewmodel/effects/ShowDeleteBookmarksDialogTest.kt
Fixes #3889 
* We have implemented `setHasStableIds(true)` in our RecyclerView, which handles data updates efficiently and enhances view recycling. It also provides smooth animations when data is refreshed. However, it requires unique IDs to perform these operations effectively. Since our bookmarks are stored in libkiwix and do not have unique IDs (database IDs), this sometimes results in duplicate data being displayed in the list instead of the actual data, as the lack of unique IDs causes the same data to be repeated when recycling non-visible items.
* To fix this, we have explicitly provided unique IDs by combining a UUID with the maximum value of a long. This ensures that RecyclerView can efficiently handle large data sets.
* Added instrumentation test case to avoid this type of error …
=> Fixed: Sometimes not all Bookmarks are showing.

core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt
Fixes #3897 
Handling the exception thrown by the `getDirectAccessInformation()`. [InvocationTargetException](https://developer.android.com/reference/kotlin/java/lang/reflect/InvocationTargetException) is a checked exception that wraps an exception thrown by an invoked method or constructor, and here it was thrown when constructing the `DirectAccessInformation` constructor. This method is used for loading media files e.g. photos, videos, etc. The reproducible steps are unknown, and there has been only 1 error in the last 60 days so it hardly occurs or occurs when an `Item` fails to provide the `directAccessInformation`. Now, we are catching that exception if thrown by this method so that it will not crash the application, and handle the loading of that media file on the Android side as …
=> Fixed: `getDirectAccessInformation()` method throw the `InvocationTargetException` and crash the application.

app/src/androidTest/java/org/kiwix/kiwixmobile/ObjectBoxToRoomMigratorTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/roomDao/HistoryRoomDaoTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/roomDao/NoteRoomDaoTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/dao/HistoryRoomDao.kt, core/src/main/java/org/kiwix/kiwixmobile/core/dao/NotesRoomDao.kt, core/src/test/java/org/kiwix/kiwixmobile/core/page/viewmodel/effects/DeletePageItemsTest.kt
Fixes #3899
* ID is the primary key for notes/history and when there is an already id available in the room database, and if there is the same id present in the objectbox database and we try to put that entity in the room it gives the SQLiteConstraintException. To fix this we have modified our saving functions of history and notes. If there is already an ID that exists in the room database that we are trying to put in the database it will set the ID to 0 so that the room will automatically assign the ID to that entity and our history/notes will prevent it from being lost.
* Added the test cases to properly test these scenarios.
=> Fixed: `SQLiteConstraintException` when inserting the same id item of hisotry/notes in room database.

app/src/androidTest/java/org/kiwix/kiwixmobile/ObjectBoxToRoomMigratorTest.kt
Fixes #3907 
Increased the migration timing a little bit as migration sometimes takes a few milliseconds more on CI(e.g. 100MS, and sometimes 50MS). On the real devices, it takes a few seconds to migrate 5000 history so the issue is only on the CI emulator.
=> Fixed: Sometimes migration test took longer in migration in lower device(e.g. API level 25) and fails the test case.

core/src/main/java/org/kiwix/kiwixmobile/core/dao/FetchDownloadDao.kt, core/src/main/java/org/kiwix/kiwixmobile/core/di/modules/DownloaderModule.kt, core/src/main/java/org/kiwix/kiwixmobile/core/downloader/fetch/FetchDownloadNotificationManager.kt
Fixes #3908 
In the notification, the information coming from `fetch` does not include the ZIM title (only the file name is currently shown in the notification). However, we have the `FetchDownloadDao` where we save all the details related to downloads. We have created a method in `FetchDownloadDao` that retrieves the `downloadEntity` from the file name, which includes the ZIM title, and we are now displaying that title in the notification.
https://github.com/kiwix/kiwix-android/assets/34593983/39875853-a0be-45c7-8a8a-3af4aa1137ce
=> Displaying the ZIM title in the notification instead of the file name.

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
Fixes #3912 
* Reproduced on a low-end device that is very slow.
* Previously, we are checking the bookmark is added or not when a page is fully loaded in the webView. In the meantime previously set bookmark toggle is showing e.g. if the previous page is added as a bookmark then until the page is fully loaded the toggle is showing that the current is added as a bookmark. However, this new page is not added as a bookmark.
* To fix this latency, we moved our `updateUrlProcessor()` method to the `webViewProgressChanged` method to update the bookmark toggle when a page starts loading in the webView. This fixes the latency in updating the bookmark toggle.
| <video src="https://github.com/kiwix/kiwix-android/assets/34593983/e7209bc0-5 …
=> Fixed: latency in showing whether a bookmark is added in the toggle button.

.github/workflows/ci.yml, contrib/instrumentation-customapps.sh, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimReaderContainer.kt, core/src/main/java/org/kiwix/kiwixmobile/core/webserver/KiwixServer.kt, custom/src/androidTest/AndroidManifest.xml, custom/src/androidTest/java/org/kiwix/kiwixmobile/custom/search/SearchFragmentTestForCustomApp.kt, custom/src/androidTest/java/org/kiwix/kiwixmobile/custom/search/SearchRobot.kt, custom/src/androidTest/java/org/kiwix/kiwixmobile/custom/testutils/RetryRule.kt, custom/src/androidTest/java/org/kiwix/kiwixmobile/custom/testutils/TestUtils.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomMainActivity.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt
Fixes #3920 
* In custom apps we are using the assetFileDescriptor, and the `dup()` method of `parcelFileDescriptor` is internally throwing resource leak exception(found in the debug stacktrace while running the application under the strace) and it somehow impacting the suggestion API.
* Removed the dup method of the `parcelFileDescriptor`.
| With file(in kiwix and custom apps)  | The issue(with assetFileDescriptor in custom apps) | Fix(with assetFileDescriptor in custom apps) |
| <video src="https://github.com/kiwix/kiwix-android/assets/34593983/991950d8-3eec-44d9-afa1-438f3a01f36f" /> | <video src="https://github.com/kiwix/kiwix-android/assets/34593983/9c8bc268-51b5-48a5-8d09-f3d82843661e" />  | <video …
=> Fixed: Suggestions to 90% broken on Wikimed FR.

app/src/androidTest/java/org/kiwix/kiwixmobile/page/bookmarks/ImportBookmarkTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/dao/LibkiwixBookmarks.kt, core/src/main/java/org/kiwix/kiwixmobile/core/di/modules/JNIModule.kt
Fixes #3890 
* [wikipedia_zh_top_maxi_2024-06.zim](https://download.kiwix.org/zim/wikipedia/wikipedia_zh_top_maxi_2024-06.zim) have the same redirected entry(`英伟达`) for searched terms(輝達, 英偉達, Nvidia, Nvidia, NVIDIA) but these search terms have the same content as on `英伟达` probably that's why all these URLs have the same redirect entry like shown below.
```
1) Title = 輝達
Url = https://kiwix.app/A/%E8%BC%9D%E9%81%94
Redirect entry = https://kiwix.app/A/英伟达
2) Title = 英偉達
Url = https://w/kiwix.app/A/%E8%8B%B1%E5%81%89%E9%81%94
Redirect entry = https://kiwix.app/A/英伟达
```
* The user was facing this issue on his device where he saved the bookmark for different URLs due to we had a latency issue #3912 in showing the bookmark toggle, The user saved two bookmarks with different URLs but the …
=> Fixed: Duplicate bookmarks showing on the bookmark screen, and bookmark.xml showing to bookmarks connected to each other.

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt
Fixes #3926 
* Caught the exception if any thrown by the libzim when getting the random entry so that it will not crash the application.
* When this type of error occurs then we have refactored our code to show the random article instead of a (blank/ same page) currently loaded in the webView.
=> Fixed: The application crashes when opening a random article.

core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt
Fixes #3924 
* Articles containing special characters like # in the URL were causing problems. We had previously implemented logic to retrieve data from libzim by trimming the URL before these characters to properly load videos, images, and other articles. However, this logic caused the URL to break under certain conditions.
```
Article = Trouble_du_déficit_de_l'attention 
Url = https://kiwix.app/A/Trouble_du_déficit_de_l'attention_avec_ou_sans_hyperactivité#Épidémiologie
Article = Trouble_du_déficit_de_l’attention_avec_ou_sans_hyperactivité 
Url = https://kiwix.app/A/Trouble_du_déficit_de_l'attention_avec_ou_sans_hyperactivité#Épidémiologie
```
* To address this, we implemented a fallback mechanism. If libzim does not return the expected data using our initial logic, we now attempt to …
=> Fixed: REGRESSION WikimedFR stuck on specifc article

core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimReaderContainer.kt
Fixes #3909 
* Previously the `data` has been read for the video within the application for setting the content range, which slowdowns the process of video loading so we have refactored our code to not use that, and should directly pass the stream for video to webView so that webView handled the stream itself.
* Rendering the HTML data, and video data on the IO thread.
* Now we are passing the stream if any uncompressed item over 1MB comes to render, and loading the data via libkiwix for the rest.
=> Fixed: Playing video is too slow to start.

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
Fixes #3944 
* The application was crashing while casting activityMainRoot to ViewGroup, which was null at that point (possibly because the user switched to another fragment). We were attempting to cast a null variable to a non-nullable type.
* The WebView can return null, and we handle that in our CoreReaderFragment when creating the WebView object.
* To fix this, we modified the `createWebView` method to avoid casting any null variables and to ensure that no null variables are passed when creating the `ToolbarScrollingKiwixWebView`. If a null variable is encountered, it will throw an `IllegalArgumentException`, which we handling during the creation of this object.
=> Fixed: Application crashes when creating the webView.

core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt
Fixes #3945 
The getData method of the Item class was throwing an error due to any condition, the reason is unknown(maybe the data is corrupted or anything) since there are only very less occurrences but it was crashing the application so we are catching the exception if thrown by the `getData()` method so that our application will not crash.
=> Fixed: Application crashes when loading the asset(videos) from cache.

app/src/androidTest/java/org/kiwix/kiwixmobile/utils/files/FileUtilsInstrumentationTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt
Fixes #3936 
* Refactored the code to correctly retrieve the file name from the URL or source, which was causing issues with TED ZIM files.
* Added test cases to prevent this situation in the future.
https://github.com/user-attachments/assets/f34d9175-561a-4aa7-9765-ad5113514ff1
=> Fixed: Images are not saving in TED zim files.

core/src/main/java/org/kiwix/kiwixmobile/core/data/Repository.kt, core/src/main/java/org/kiwix/kiwixmobile/core/entity/LibraryNetworkEntity.kt
Fixes #3892 
Showing zim files in all available languages.
https://github.com/user-attachments/assets/6d787658-1f8d-45c0-a1c8-4ed8484d9ea8
=> Fixed: Mul file not recognized as such and listing pretty much all languages.

.github/workflows/release.yml, app/build.gradle.kts, app/src/main/res/layout/activity_kiwix_main.xml
Fixes #3933 
* Created a new package name(`org.kiwix.kiwixmobile.standalone`) for the website and nightly APK so that the playStore does not recognize it and do not show updates for these apks.
* Refactored the release CI to upload the app with this new appId.
=> Introduced new standalone apk for website and nightly.

README.md, app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt, core/src/main/java/eu/mhutti1/utils/storage/StorageDeviceUtils.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/download/effects/SetPreferredStorageWithMostSpace.kt, custom/src/test/java/org/kiwix/kiwixmobile/custom/download/effects/SetPreferredStorageWithMostSpaceTest.kt
Fixes #3939 
* Now all the downloading files will be stored in this public app-specific directory.
* Refactored the code to show this new location in settings for both internal and external storage. For existing users, the previously selected location will be replaced by the new public directory like https://github.com/kiwix/kiwix-android/issues/3940#issuecomment-2282722108.
* Updated the `README.md` file to educate users on how they can read already downloaded zim files in the PS version.
* Refactored the test cases according to this change.
https://github.com/user-attachments/assets/4453b456-7f86-4999-b5bf-23e83ac3c898
=> Use `Android/media/org.kiwix/kiwixmobile/` public app folder instead of private app folder (to download ZIM files)

core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt
Fixes #3965 
* Removed the unnecessary rule that was inverting the header image. Since the image was already inverted, there is no need to apply the filter again.
* The poster image was being inverted due to the first rule being applied to the poster element, which caused the image and video inside the poster to be inverted. To correct this, a CSS rule is added to prevent the inversion of the poster's image and video.
https://github.com/user-attachments/assets/23be058d-f6d0-472d-874b-540d7ac277af
=> Fixed: Dark mode failing on "Astrolabe" homepage.

app/src/main/java/org/kiwix/kiwixmobile/nav/helper/ScrollingViewWithBottomNavigationBehavior.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
Fixes #3964
This PR fixes the bottom page being cut when scrolling up and down. Since the zimfile content being fetched is already wrapped with a specific color, adding a big padding will make the color scheme inconsistent. I have tested with 40dp and it seems to work well from my device and emulator.
=> Fix bottom page content being cut

.github/workflows/ci.yml
Fixes #3978 
* Stabilized the emulator caching; CI is now running without errors related to caching.
* Configured the emulator to use 3GB of RAM and a 1024MB SD card instead of 4GB of RAM and a 2048MB SD card to reduce resource usage on CI. Since the emulator works well with 3GB of RAM and a 1024MB SD card on CI for running test cases for custom apps, it is better to use this configuration for the app's test cases as well.
* Now we are generating the `codecov` report on API level 30 instead of API level 25, since some instrumentation test cases, we are running on API level 30 and above, like testing the WifiHotspot, ShowingPlayStoreRestriction in HelpFragment, etc. This change increased the code coverage by 2.75%.
=> Re-enabled the emulator caching in CI.

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt
Fixes #3754 
Disabled the right drawer when the tabs screen is opened, the drawer will be enabled when the tabs screen closes.
=> Fixed: File drawer was showing on Tabs screen.

app/src/androidTest/java/org/kiwix/kiwixmobile/deeplinks/DeepLinksTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/help/HelpFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/intro/IntroFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/localLibrary/CopyMoveFileHandlerTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/main/TopLevelDestinationTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/mimetype/MimeTypeTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/bookmarks/ImportBookmarkTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/bookmarks/LibkiwixBookmarkTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/history/NavigationHistoryTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/reader/EncodedUrlTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/settings/KiwixSettingsFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/webserver/ZimHostFragmentTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/DonationDialogHandler.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt, core/src/main/res/drawable/ic_donation_icon.xml, core/src/main/res/layout/fragment_reader.xml, core/src/main/res/layout/layout_donation_bottom_sheet.xml, core/src/main/res/values/dimens.xml, core/src/main/res/values/strings.xml, core/src/test/java/org/kiwix/kiwixmobile/core/utils/DonationDialogHandlerTest.kt, custom/src/androidTest/java/org/kiwix/kiwixmobile/custom/search/SearchFragmentTestForCustomApp.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt
Fixes #3736 
* The donation popup will be shown to the user every three months.
* If the user clicks the "Later" button, the popup will appear again after 3 days.
* The donation popup will only be shown when there is at least one book available in the library. If no ZIM file is present, it’s not ideal to ask for a donation, as the user has not yet used the application.
* The donation popup will only be shown for custom apps when the support_url is configured. If the support menu item is hidden in the sidebar (a feature we offer), the donation popup will not be displayed, as there is no support_url available for that custom app.
| Kiwix App(When no bottomAppBar)  | Kiwix App(When bottomAppBar showing) | Custom Apps |
| ![Screenshot from …
=> Added a donation popup to our application.

app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/main/DarkModeViewPainterRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/main/DarkModeViewPainterTest.kt, core/src/main/res/xml/preferences.xml, core/src/test/java/org/kiwix/kiwixmobile/core/DarkModeConfigTest.kt, core/src/test/java/org/kiwix/kiwixmobile/core/main/DarkModeViewPainterTest.kt
Fixes #1999 
* Added unit test cases for the `DarkModeViewPainter` class with all the edge cases.
* Added unit test cases for the `DarkModeConfig` class as this class is used in the `DarkModeViewPainter`.
* Added UI test cases to test whether the `DarkModeViewPainter` works correctly or not.
* Sometimes CI stuck on DownloadTest when the test case waits for data to load, but the "Swipe Down for Library" error text shows on the screen because of that CI takes a long time to fail, so to improve this scenario we have refactored our test case if this text is shown on the screen then it tries to refresh the online content and test case will pass. See:
* https://github.com/kiwix/kiwix-android/actions/runs/10770667301/job/29864502974
* https://github.com/kiwix/kiwix-android/actions/runs/1077066730 …
=> Added (unit test/UI test) cases for the `DarkModeViewPainter`.

app/src/androidTest/java/org/kiwix/kiwixmobile/deeplinks/DeepLinksTest.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, app/src/main/res/navigation/kiwix_nav_graph.xml
Fixes #3997 
Fixes #3941 
* Fixed an issue where the ZIM file would not load when opened directly from the file manager.
* Fixed the issue with opening a ZIM file from the browser's download screen.
* We improved the DeppLinksTest to test this functionality, so that we can avoid this type of error in the future.
| Before Fix  | After Fix | After Fix | 
| <video src="https://github.com/user-attachments/assets/5c23e442-050e-4e64-b2a1-fc9ed12c839d"/>  | <video src="https://github.com/user-attachments/assets/4a7cbdff-f854-41c7-a012-edc0078a64d1"/>  | <video src="https://github.com/user-attachments/assets/6f6b8707-64f7-4e2e-a7b0-d9eb76702d83"/> |
=> Fixed: Opening with Kiwix a ZIM file (just after download) from Firefox fails.

app/src/androidTest/java/org/kiwix/kiwixmobile/deeplinks/DeepLinksTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/main/DarkModeViewPainterTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/main/TopLevelDestinationTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/bookmarks/LibkiwixBookmarkTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/history/NavigationHistoryTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/reader/KiwixReaderFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/reader/ZimFileReaderWithSplittedZimFileTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchFragmentTest.kt, app/src/main/res/layout/fragment_destination_download.xml, core/src/main/res/layout/layout_donation_bottom_sheet.xml
Fixes #3991 
| Light Mode  | Night Mode |
|  ![1726828112615](https://github.com/user-attachments/assets/ac99eff8-3fb0-4089-b4a5-99bbcb92ef93)| ![1726828113126](https://github.com/user-attachments/assets/b0e3472e-077f-4225-8be8-6d2e3d509606)   |
| ![1726828112840](https://github.com/user-attachments/assets/4a909960-efbd-4a16-8325-c5d596d52715)  |  ![1726828113004](https://github.com/user-attachments/assets/e1963911-cbb9-4840-8cd5-7d5b4bbd6421) |
Apart from these, all other views use the Android standard colors in our project.
* Fixed an issue where the CI was sometimes failing due to an unknown reason related to the OverflowMenuButton (the three-dot default Android button) width. See this workflow …
=> Fixed: The UI showing incorrect colors in night mode.

app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/localFileTransfer/LocalFileTransferRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/localFileTransfer/LocalFileTransferTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/library/LibraryRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/testutils/TestUtils.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/webserver/ZimHostFragmentTest.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt
Fixes #4001 
* Fixed the `LocalFileTransferTest`, which was failing on API level 33 in the CI.
* Fixed: CI was sometimes stuck on the `DownloadTest`.
* Improved the `DownloadTest` to download the smallest ZIM file, as it was previously downloading a 156MB file, which took too much time.
=> Fixed: CI sometimes stuck on instrumentation test cases.

core/src/main/AndroidManifest.xml
Fixes #4016 
Added the `foregroundServiceType` in the manifest for `ReadAloudService`, and `HotspotService` to properly work with android 14.
=> Added the `foregroundServiceType` in manifest for `ReadAloudService`, and `HotspotService`.

core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ActivityExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/DonationDialogHandler.kt, core/src/main/res/values/dimens.xml
Fixes #3736
The donation popup was not looking good on tablets, so we have improved the design of the donation popup for tablets.
| Tablet landscape  | Tablet portrait |
| ![TabletDayModeLandscape](https://github.com/user-attachments/assets/e69ef986-b318-46a6-8699-b517bce38897) | ![TabletDayModePotrait](https://github.com/user-attachments/assets/e1e881fd-a21b-4c65-9c62-90647d58c01c) | 
| Tablet landscape in Dark mode | Tablet portrait in Dark mode |
| ![TabletDarkModeLandscape](https://github.com/user-attachments/assets/e768cf1d-c5ed-4318-b8eb-31e4c07e86ab) | ![TabletDarkMode](https://github.com/user-attachments/assets/eb928545-63ac-4385-a884-fdbbb5751a0f) |
In normal devices
=> Fixed: The donation popup does not look well in tablet.

app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadTest.kt, core/src/main/res/layout/fragment_page.xml, core/src/main/res/layout/layout_scrolling_toolbar.xml, core/src/main/res/layout/layout_toolbar.xml
Fixes #4024 
* Now we are using the `android:theme` everywhere in our project instead of `app:theme`.
* Little improvement in DownloadTest, since we are downloading the smallest ZIM file so it can be downloaded immediately after starting, so in this case, do not fail the test case. Since we are testing the pause/resume functionality in our other DownloadTest. See in these workflows: 
1. https://github.com/kiwix/kiwix-android/actions/runs/11268664779/job/31335825391?pr=4025
2. https://github.com/kiwix/kiwix-android/actions/runs/11268664779/job/31335825664?pr=4025
=> Fixed: `app:theme` is now deprecated. Please move to using `android:theme` instead.

buildSrc/src/main/kotlin/Versions.kt
=> Upgraded the `java-libkiwix` to `2.2.3` to start using the `libkiwix14`.

app/src/androidTest/java/org/kiwix/kiwixmobile/localLibrary/CopyMoveFileHandlerTest.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/CopyMoveFileHandler.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/AppProgressListenerProvider.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/fileselectView/effects/DeleteFiles.kt, core/src/main/java/org/kiwix/kiwixmobile/core/dao/DownloadRoomDao.kt, core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FileExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt
Fixes #4031 
* Moved the file-deleting logic on the IO thread, and refactored our code according to this change.
* Removed the unused code from the `FileUtils` class.
=> Fixed: Application crashing due to `Input dispatching timed out` when deleting the ZIM files.

custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomFileValidator.kt, custom/src/test/java/org/kiwix/kiwixmobile/custom/download/main/CustomFileValidatorTest.kt
Fixes #4000
* This issue occurred when we tried to access ZIM files from the application’s folder in the `zimFiles()` method. In this method, we add directories to a non-null list of files. However, when attempting to retrieve the list of files from the application directory, the SD card path was null due to the SD card being unmounted, which caused the application to crash.
* To fix this, we have improved our `zimFiles()` and `obbFiles()` methods to return only existing, non-null directories. This ensures proper handling of file system detection, so if a directory is unavailable or returns null, these methods handle it appropriately.
=> Fixed: Medical wikimedia (mini) keeps crashing.

core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/Constants.kt, core/src/main/res/values/strings.xml
Fixes #4005 
* Previously, other apps were appearing in the suggestions when sending the diagnostic report. We have improved our intent so that it now directly opens the user's email client to send the diagnostic report to us.
* We cannot attach a file to the email when using the `ACTION_SENDTO` action in the intent. So we have removed the file from the email and attached the device logs in emailBody.
https://github.com/user-attachments/assets/f1918473-5b55-4fa2-ac78-6a6c6d658175
=> Fixed: "Send diagnostic report" function should open the user's email client.

app/src/androidTest/java/org/kiwix/kiwixmobile/utils/files/FileUtilsInstrumentationTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt
Fixes #4008
* When we open a file from different browsers, they provide a URI through their own file provider, and the content resolver cannot retrieve the file path for these types of URIs. To fix this issue, we have introduced a fallback method that returns the exact path of the file located in the Downloads folder.
* Another issue we encountered on tablets is that the URIs are different from those on regular mobile devices, and our `documentProviderContentQuery` method could not return the path for these types of URIs from the Downloads folder. To fix this issue, we used our fallback method to retrieve the file path for these URIs.
**Before Fix **
https://github.com/user-attachments/assets/7bf5b236-dfe0-47bb-a6bc-1fde772a4bd7
**After Fix** …
=> Fixed: In Samsung tablet of Android 14, downloaded files can not be opened via file picker or deep linking in non-PS variant.

app/src/main/AndroidManifest.xml
Fixes #4002 
* Created a custom intent filter for Samsung's "My Files" app to handle all MIME types, allowing ZIM files to be opened directly from this file manager.
=> Fixed: Not able to open a ZIM file from Samsung's file explorer.

app/src/androidTest/java/org/kiwix/kiwixmobile/localLibrary/CopyMoveFileHandlerRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/localLibrary/CopyMoveFileHandlerTest.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/CopyMoveFileHandler.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt, app/src/test/java/org/kiwix/kiwixmobile/localLibrary/CopyMoveFileHandlerTest.kt
Parent Issue #4002
* We retrieve the file name from the incoming Uri using `DocumentFile` (the official way to handle Uris) and check if it contains `.zim` or `.zimma` before proceeding with the copy/move operation. If the file name is null, we copy/move the file first and then validate it as a ZIM file using `libkiwix`. If valid, the file opens in our reader; otherwise, we revert the copy/move operation.
* Added UI and unit test cases for this new functionality.
https://github.com/user-attachments/assets/52259656-f772-4855-af53-9faeac5f5871
=> Implemented error handling for cases when the selected file is not a ZIM file.

app/src/androidTest/AndroidManifest.xml, core/src/main/AndroidManifest.xml, custom/src/androidTest/AndroidManifest.xml
Fixes #4055 
* Removed the `usesCleartextTraffic` from our manifest, since this attribute is mainly used for allowing the http requests(Mainly used for network requests). The network requests are only used for downloading the ZIM files in our application, and now, no downloading URL is on HTTP, so now, we do not need to keep this attribute.
* Removed this attribute from our test cases manifest as well.
=> Removed the `usesCleartextTraffic` from our manifest

app/src/main/AndroidManifest.xml, app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt
Fixes #4048
* We are now using the `singleInstance` launch mode instead of `singleTop` to prevent Kiwix from opening within the file manager.
* Improved the handling of the `GET_CONTENT` shortcut(it was not properly working if the application was in the background).
https://github.com/user-attachments/assets/3a0fce5f-7299-4fd7-b5fc-98f33678a0f0
=> Fixed: Kiwix opens in the Samsung file navigator.

app/src/androidTest/java/org/kiwix/kiwixmobile/BaseRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/mimetype/MimeTypeTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/reader/EncodedUrlTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/reader/ZimFileReaderWithSplittedZimFileTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/widgets/SearchWidgetRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/widgets/SearchWidgetTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreSearchWidget.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/SearchFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/Action.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModel.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/ProcessActivityResult.kt, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/ProcessActivityResultTest.kt
Fixes #4059 
* Fixed: `SearchWidget` was not properly working, it was due to the direct casting of `kClass` not working, so we have improved our code to get the `appName`(which we are showing in the search widget).
* Also, previously, the "Search" text was hardcoded in the `SearchWidget`, which can not be translated into other languages. So, to fix this, we are starting to use this from our string file so that the sentence can easily be translated into other languages.
https://github.com/user-attachments/assets/3b61107d-2e0c-4b24-8c1d-4ad3d9ea437b
* Fixed: When we click on the mic icon in the `SearchWidget` it opens the `searchFragment` but after searching through voice search it again opens the voice search(It does not search my voice search, same for if I press the back button the voice …
=> Fixed: SearchWidget is not properly working.

core/src/main/res/values/strings.xml
Fixes #4064
Improved the message to copy/move ZIM.
=> Improved the message to copy/move ZIM

CHANGELOG, CONTRIBUTING.md, README.md, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/CopyMoveFileHandler.kt, app/src/main/res/layout/copy_move_progress_bar.xml, app/src/main/res/values/strings.xml, core/src/main/res/values-dag/strings.xml, core/src/main/res/values-fr/strings.xml, core/src/main/res/values-ia/strings.xml, core/src/main/res/values-it/strings.xml, core/src/main/res/values-iw/strings.xml, core/src/main/res/values-ko/strings.xml, core/src/main/res/values-mk/strings.xml, core/src/main/res/values-pt-rBR/strings.xml, core/src/main/res/values-ru/strings.xml, core/src/main/res/values-zh-rTW/strings.xml, core/src/main/res/values-zh/strings.xml, core/src/main/res/values/strings.xml, custom/src/main/res/values-qq/strings.xml, custom/src/main/res/values/strings.xml
Fixes #4066 
* Improved the message of the copy/move ZIM file dialog. Now the new messages will be shown on the dialog are:
1. Copying ZIM file…
2. Moving ZIM file…
| Copy Dialog  | Move Dialog |
| ![Screenshot_20241112-123419_Kiwix](https://github.com/user-attachments/assets/21acf3fe-0249-40e2-a550-2a513f751c85) |![Screenshot_20241112-123631_Kiwix](https://github.com/user-attachments/assets/fdd0bf43-53ee-4f34-b12f-29d8f6c1e6fe)  |
* Corrected all the messages related to ZIM.
=> Corrected all the messages related to ZIM, and improved the message of copy/move ZIM file dialog

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
Fixes #4065 
A flash was showing on the reader screen (with the blue button "Open library") when we were opening the ZIM file from the "Local library screen" because we had moved the `canReadFile` method to the IO thread. We have fixed this issue in this PR. Now, a `progress` will show until the `ZimFileReader` is created on the IO thread to notify users that the ZIM file is in the process of opening.
https://github.com/user-attachments/assets/a89d24fa-3973-448c-9a82-0528a8d0f6d5
=> Fixed: Unclean opening local ZIM file in library

app/src/androidTest/java/org/kiwix/kiwixmobile/deeplinks/DeepLinksTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/help/HelpFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/help/HelpRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/localLibrary/CopyMoveFileHandlerRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/localLibrary/CopyMoveFileHandlerTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/localLibrary/OpeningFilesFromStorageTest.kt, app/src/main/java/org/kiwix/kiwixmobile/help/KiwixHelpFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/CopyMoveFileHandler.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, app/src/test/java/org/kiwix/kiwixmobile/localLibrary/CopyMoveFileHandlerTest.kt, core/src/main/java/eu/mhutti1/utils/storage/StorageSelectDialog.kt, core/src/main/java/eu/mhutti1/utils/storage/adapter/StorageDelegate.kt, core/src/main/java/eu/mhutti1/utils/storage/adapter/StorageViewHolder.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/KiwixDialog.kt, core/src/main/res/values-dag/strings.xml, core/src/main/res/values-fr/strings.xml, core/src/main/res/values-ia/strings.xml, core/src/main/res/values-it/strings.xml, core/src/main/res/values-iw/strings.xml, core/src/main/res/values-ko/strings.xml, core/src/main/res/values-mk/strings.xml, core/src/main/res/values-pt-rBR/strings.xml, core/src/main/res/values-ru/strings.xml, core/src/main/res/values-zh-rTW/strings.xml, core/src/main/res/values-zh/strings.xml, core/src/main/res/values/strings.xml
Fixes #4067 
* Removed the initial dialog of copy/move. Now, we are showing the usual one "Kiwix requires the ZIM file to be in its own data directory. Do you want to copy or move it there?" dialog every time(with a cancel button so that the user can have better control over this functionality).
* Showing the storage selection dialog when there is an SD card available, if not available, it will directly proceed with the copy/move operation. Also, when the SD card is inserted and the user tries to copy/move the ZIM file, at this point, it will show the storage selection dialog. Apart from this, it will also show the storage selection dialog on the reinsertion of the SD card.
https://github.com/user-attachments/assets/c332b4ae-9810-420e-a91e-eeb94759841b
* Added the explanation in the `Help …
=> Fixed: Many problems at first side loading of a ZiM file

app/src/androidTest/java/org/kiwix/kiwixmobile/shortcuts/GetContentShortcutTest.kt, app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt
Fixes #3957 
The issue was with navigateTo(), which breaks the back stack (https://stackoverflow.com/questions/71525493/bottom-navigation-bar-malfunctions-when-navigating-from-a-fragment)
so used the NavigationUI API to navigate.
https://github.com/user-attachments/assets/205d297f-6e4f-4217-9010-cb733e52dec3
ready to rework if changes are needed.
=> fixed shortcut issue

app/src/androidTest/java/org/kiwix/kiwixmobile/localFileTransfer/LocalFileTransferTest.kt, app/src/main/java/org/kiwix/kiwixmobile/localFileTransfer/LocalFileTransferFragment.kt, app/src/main/res/layout/fragment_local_file_transfer.xml, core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ActivityExtensions.kt, core/src/main/res/values/dimens.xml
Fixes #4085 
* It was due to our 3rd and 4th showCase since we are showing the showcase view on `recyclerView` which has the `match_parent` width(So as much as the device has the width our showCase view becomes bigger), and showCase view tries to show the given view inside a circle. So due to this, the circle was very big and the remaining content was going outside the screen.
* To fix this, we have added 2 views to show the showcase view, the width will be adjusted at runtime according to device width which prevents this type of error.
https://github.com/user-attachments/assets/d803245e-36e7-49c8-90a0-9bd1c5f98b77
=> Fixed: Transfer ZIM file freezes on tablet

core/src/main/res/values-qq/strings.xml, core/src/main/res/values/strings.xml
Fixes #4089 
* Now we are using the "Read Aloud" string everywhere in our project.
* Updated the documentation so that TW uses "Read Aloud" instead of "Text to speech".
=> Using Read Aloud string everywhere in our project

app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteRobot.kt, core/src/main/res/menu/menu_main.xml, core/src/main/res/values/strings.xml
=> Improved the Note label in the OverFlowMenu for more clarity

core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt
Fixes #4095 
Introduced a new way of attaching the log file in the email body without showing other apps in the suggestion list. Since there was a `TransactionTooLargeException` error while resolving the email apps when there are large logs available. So to fix this, we have introduced a way to attach the log file in the email body that solves this problem. Also, ensuring that other apps could not show in the suggestion list when sharing.
https://github.com/user-attachments/assets/c49e4e43-d2a3-4512-aa89-cb389ceb8b60
https://github.com/user-attachments/assets/bc225d53-a1b2-4756-b43f-5302117fc1c8
=> Fixed: `Send diagnostic` report does not attach the device logs in `Google Pixel 7a`.

.github/workflows/release.yml
Fixes #4053
Now we are uploading the APKs from CD to the existing release instead of creating the new draft release via GitHub action. By doing this we do not need to manually upload the APK in the existing release and delete the draft release.
=> Fixed: APK files missing at releases since v3.8.1

app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/history/NavigationHistoryTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/reader/KiwixReaderFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchFragmentTest.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/CopyMoveFileHandler.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt
Fixes #4104 
There were 2 issues that caused this error.
* We were previously using `lifecycleScope`, but we encountered an issue where the `lifecycleScope` remained active when navigating away from the reader fragment. Since the fragment was still in the `backStack`, the scope continued running and attempted to set the new ZIM file, even though the reader screen was no longer visible. When we tried to open a new ZIM file, both files were attempting to load in the reader, causing the main page to load content from both files. This happened because the previous `archive` object was disposed of when the new ZIM file was added, and WebView tried to load content from the disposed `archive` object. To address this, we switched to using `coreReaderLifeCycleScope` and ensured that any ongoing …
=> Fixed: Sometimes application crashes due to a native crash when we frequently load the ZIM files in the reader.

app/detekt_baseline.xml, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModel.kt, app/src/test/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModelTest.kt, core/detekt_baseline.xml, core/src/main/java/org/kiwix/kiwixmobile/core/ConnectivityManagerExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/DownloadManagerMonitor.kt, core/src/main/java/org/kiwix/kiwixmobile/core/zim_manager/ConnectivityBroadcastReceiver.kt, core/src/main/java/org/kiwix/kiwixmobile/core/zim_manager/NetworkState.kt
* When the internet connection is interrupted and then restored during an active download, the progress is now accurately tracked while the application remains in the foreground. 
* Tracking progress works fine in this scenario when the application is closed.
=> Minor improvement in downloading functionality.

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, core/src/main/AndroidManifest.xml, core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FragmentExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt
Fixes #4112 
* Improved the back press handling in CoreMainActivity using the latest `onBackPressedDispatcher` API, to properly work with the latest versions of Android.
* Enhanced the back press behavior in OnlineLibraryFragment while searching for ZIM files, so the SearchView will not close when the user presses the back button to simply dismiss the keyboard.
https://github.com/user-attachments/assets/39983cb1-fd90-4418-b014-8249e9fc13ee
=> Fixed: Virtual keyboard reset the search (in library).

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/CopyMoveFileHandler.kt
Fixes #4123 
Moved the delete logic to the IO thread to ensure the deletion operation does not block the main thread. This method was called from the `Main` dispatcher, but now, we ae calling from the `IO` dispatcher.
=> Fixed: Input dispatching timed out at `CopyMoveFileHandler.deleteSourceFile`.

core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/DownloadMonitorService.kt
Fixes #4125 
* Moved the cancel download logic to the IO thread, ensuring that download-related tasks are performed on the IO thread while keeping the main thread free.
* Also moved the functionality to the IO thread for checking the status when we receive the ACTION_DOWNLOAD_COMPLETE broadcast from DownloadManager, to determine if the download was successful or canceled. This ensures it doesn't block the main thread, as cancelDownload is currently causing a blockage.
=> Fixed: Input dispatching timed out at `DownloadMonitorService.cancelDownload`.

app/src/main/java/org/kiwix/kiwixmobile/webserver/KiwixServer.kt, app/src/main/java/org/kiwix/kiwixmobile/webserver/WebServerHelper.kt, app/src/main/java/org/kiwix/kiwixmobile/webserver/ZimHostFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/webserver/wifi_hotspot/HotspotService.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
Fixes #4127 
* Moved the `Book()` object creation to `lifeCycleScope` instead of running it on the main thread. Earlier, it was blocking the UI, especially with large ZIM files. Now, by using `lifeCycleScope`, it won't block the main thread.
* Improved the KiwixServer creation process. Server creation was previously happening on the main thread, which could cause the same issue we are facing with adding bookmarks. Because we are creating the same book object while creating the server, which is required for `server` creation.
* Updated the behavior of the "Starting server" dialog. Before, the dialog disappeared after validating the IP address, even though server creation was still in progress. Now, the server creation process is moved to the IO thread. For large ZIM files, server creation …
=> Fixed: Input dispatching timed out in `CoreReaderFragment.toggleBookmark`.

app/src/androidTest/java/org/kiwix/kiwixmobile/main/TopLevelDestinationTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/shortcuts/GetContentShortcutTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/ExternalLinkOpener.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomMainActivity.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt
Fixes #4083 
Fixed external link warning when user wants to make a donation
=> #4083 fixed external link warning when user wants to make a donation

core/src/main/AndroidManifest.xml
Fixes #4150 
* When users attempt to uninstall the app, the "Keep app data" checkbox will appear in the uninstall dialog. By enabling it, the app's data will not be deleted upon uninstallation, allowing users to access the data again if they reinstall the app. Additionally, this is a good way to notify users that uninstalling the app can delete all app-related data, such as ZIM files.
=> Added the hasFragileUserData tag in the manifest to display the "Keep app data" checkbox in the uninstall dialog.

README.md, app/build.gradle.kts
Parent Issue #4053
See https://github.com/kiwix/kiwix-android/issues/4053#issuecomment-2456951610
* We have disabled the dependencies metadata from the signed APK(For Kiwix App) since this APK we are posting on IzzyOnDroid, GitHub, and our website so the metadata is not needed for this. For the app bundle: We have kept the dependencies metadata since it will upload on the Google PlayStore where the dependency metadata is analyzed to provide actionable feedback on potential issues with project dependencies.
* Added the information about permissions used in the application in the README file to show users why and where we are using these permissions.
* Updated the outdated content of the README file(It was showing file picker is not available in the PS variant).
=> Disabled the dependencies metadata from Singed APK for kiwix app.

app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/CopyMoveFileHandler.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/settings/KiwixPrefsFragment.kt, app/src/test/java/org/kiwix/kiwixmobile/localLibrary/CopyMoveFileHandlerTest.kt, core/src/main/java/eu/mhutti1/utils/storage/StorageDeviceUtils.kt, core/src/main/res/layout/item_storage_preference.xml
Fixes #4163 
* Moved the storage device retrieval to the IO thread.
* Updated the StorageDeviceUtils.getWritableStorage method to a suspend function to ensure execution on the IO thread.
* Refactored CopyMoveFileHandler, OnlineLibraryFragment, KiwixPrefsFragment, and LocalLibraryFragment to adapt to this change.
* Optimized storage device retrieval by caching it in the main activity and reusing it across fragments to enhance performance, especially with large SD cards. Because getting it in fragments again and again is quite expensive because when we switch to other screens the previous saved state will lost, and it again tries(when it requires) to get the list of storage devices if we again come back to that fragment.
* Refactored the CopyMoveFileHandlerTest.
* Improved the showing of …
=> Fixed: Application crash caused by "Input dispatching timed out" while retrieving storageDeviceList information in the online library.

core/src/main/java/eu/mhutti1/utils/storage/StorageDeviceUtils.kt, core/src/main/java/org/kiwix/kiwixmobile/core/dao/NewBookDao.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileSearch.kt, core/src/test/java/org/kiwix/kiwixmobile/core/dao/NewBookDaoTest.kt
Fixes #4175
* Improved the scanning process for ZIM files to reduce scan time by excluding hidden folders, which are unnecessary and caused delays in scanning.
* Updated MediaStore to exclude ZIM files located in the SD card's trash folder, addressing the issue.
* Refactored the NewBookDao to remove any ZIM files from the library screen if they are located in the trash folder.
* Added a new unit test to verify that books located in the trash folder do not appear on the library screen.
=> Fixed: The ZIM file was displayed on the library screen but failed to open (the ZIM file was located in the SD card's trash folder).

README.md
Fixes #4146
To explaining the users why we have introduced 2 variants, and what is the difference between these variants. Also explaining how they can move the content from previous app to this new app.
=> Added a section in the README file to showcase the two variants of our application.

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/CopyMoveFileHandler.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/KiwixDialog.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt, core/src/main/res/values/strings.xml
Fixes #4045 
* Showing a warning dialog when copying/moving the ZIM chunks in the PS version.
* Improved the copying/moving of ZIM chunks, and improved the validation of ZIM chunks.
* The warning dialog will only show for the ZIM chunks, for normal ZIM files it will directly open the ZIM file in the reader like it was working.
https://github.com/user-attachments/assets/82cd6fb5-dbc1-4bc0-92b1-c065f1b04056
=> Showing a warning dialog when copying/moving the ZIM chunks in PS version.

.github/workflows/release.yml, buildSrc/src/main/kotlin/plugin/AppConfigurer.kt
Fixes #4128 
* Before the name was `kiwix-3.13.0.apk` for the release APK(with app id org.kiwix.kiwixmobile app id) we were uploading on the website. But now, we are uploading the standalone APK on the website(with org.kiwix.kiwixmobile.standalone app id) it is a breaking change, and users are not aware of it. So we are changing the APK name so that users can understand this change. See https://github.com/kiwix/kiwix-android/issues/4128#issuecomment-2565693850.
* Renamed the nightly APK since there also we are uploading the standalone APK.
=> Changed the website, and Nightly APKs name.

app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomMainActivity.kt
Fixes #4166 
* The issue occurred because these shortcuts were defined in the manifest, which treated them as immutable and unable to be updated. We removed them from the manifest and added them as dynamic shortcuts. On some devices (e.g., Honor devices), it takes time to remove these shortcuts from the static shortcut list after the user updates the app, causing them to be treated as immutable and unable to be updated. This led to the crash. To fix this, we updated our shortcut IDs so that when the previous static shortcuts are removed by the OS, it will not affect the creation of the new dynamic shortcuts.
* For previously added dynamic shortcuts on other devices, we implemented a removeOutdatedIdShortcuts() method, which removes the old dynamic shortcuts.
* Using the …
=> Fixed: Application crash while adding application shortcuts.

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/res/values/strings.xml
Fixes #4161 
* The issue occurred in the Play Store variant, specifically with the copy/move functionality for ZIM files. After copying or moving a ZIM file, the application attempts to open it in the reader. However, if the application tries to open a split ZIM file with only one chunk, it throws an error indicating that the file is not a valid ZIM file (which is expected, as not all ZIM chunks have been copied/moved). When this error occurs, the menu buttons remain enabled, allowing the user to interact with them. If the user then attempts to open a random article, the application enters an infinite loop and crashes. To resolve this, we now disable the menu controls whenever an error occurs while opening a ZIM file, preventing the user from using them in such scenarios.
**Before fix** …
=> Fixed: Application crashes when opening the random article.

config/detekt/detekt.yml
Linked issue #4159
1.  Increased the `functionThreshold` for `LongParameterList` from 6 to 8.
2.   Enabled `ignoreDefaultParameters` for `LongParameterList`.
3.   Updated `functionPattern` to allow uppercase letters at the beginning.
4.   Add  `ignoreAnnotatedFunctions` to `['Preview']`
5.   Add `ignoreAnnotated` to `['Composable']`
6.   Updated `constantPattern` to accept uppercase letters followed by alphanumeric characters.
7.    Enabled `ignorePropertyDeclaration` for `MagicNumber`.
followed resource https://detekt.dev/docs/introduction/compose/
to edit the properties to support composable functions in detekt config.
=> Updated detekt configuration to support compose:

app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/notes/adapter/NoteListItem.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/notes/viewmodel/effects/ShowDeleteNotesDialog.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/notes/viewmodel/effects/ShowOpenNoteDialog.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/viewmodel/PageViewModel.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/viewmodel/effects/OpenNote.kt
Fixes #4180 
* Removed the unnecessary creation of ZimFileReader when opening notes on the Notes screen.
* Refactored `AddNoteDialog` to use database values for performing note-related operations (e.g., view, edit, delete notes) instead of setting and using `ZimFileReader`.
https://github.com/user-attachments/assets/42219ed2-1a55-4302-8773-d010472ba80a
=> Removed the unnecessary creation of ZimFileReader when opening notes on the Notes screen.

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt
Fixes #4185
* Fixed: If storage permission is permanently denied on Android 11 or below, the selected file via the file picker does not open.
* The storage permission dialog is now shown when the user clicks the "File Picker" button, prompting them to grant the permission first before selecting a ZIM file via the file picker.
* If storage permission is denied or not granted, and the user opens a ZIM file by clicking on it in the file manager, the app will first prompt for permission. Once the permission is granted, the ZIM file will open in the reader. If the permission is not granted, the operation is canceled, and the selected ZIM file will not open.
* Fixed the scenario where, if the application does not have the `MANAGE_EXTERNAL_STORAGE` permission and the user tries to open a ZIM …
=> Fixed: If storage permission is permanently denied on Android 11 or below, the selected file via the file picker does not open.

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
Fixes #4184 
* Disabled the right drawer when the user is reading a book in fullscreen mode to ensure uninterrupted reading.
* Also disabled the drawer while a video is playing in fullscreen mode to avoid interruptions during video playback.
https://github.com/user-attachments/assets/07756576-1fdb-4a86-92c6-7c8f286f6a3e
=> Fixed: Navigation drawer showing while reading a book in fullscreen mode.

buildSrc/src/main/kotlin/Versions.kt
Fixes #3956
We have fixed this issue on `java-libkiwix` side see https://github.com/kiwix/java-libkiwix/pull/116 for full details.
=> Using java-libkiwix `2.2.4` to fix native crashes happens while getting the `getEntryByPath`, and `getData()` methods.

CHANGELOG
=> Updated the `CHANGELOG` file to show changes made in milestone `3.14.0`.

.github/workflows/ci.yml, .github/workflows/pull_request.yml
Fixes #4203 
* The CI pipeline failed due to the deprecated version of `upload-artifact` (v3).
* Upgrading to version 4 resolves the deprecation error and ensures compatibility with the latest features and improvements. Apart from this, the other `actions` are using the latest versions.
=> Bumped the `upload-artifact` action from version 3 to version 4.

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
Fixes #4198 
* The issue occurred because, after closing a tab and quickly navigating to the search screen, the snackbar callback was still running in the background. When switching to the search screen, the WebView list was empty because we cleared it when the fragment's view was destroyed. As a result, the book was closed, and the SearchScreen could not find the ZIM file for searching.
* To fix this, we now dismiss the snackbar callback when the fragment's view is destroyed.
https://github.com/user-attachments/assets/6936ac0b-59b9-4bc8-bfa5-0ab51af20582
=> Fixed: Search was not working when closing a tab and immediately opening the search screen.

app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteRobot.kt, core/src/main/java/org/kiwix/kiwixmobile/core/dao/NotesRoomDao.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt
Fixes #4194 
* The note file is now deleted from storage when the user selects multiple notes and deletes them from the "Notes" screen.
* Improved note deletion in the "Note Dialog." Previously, when deleting a note from the `AddNoteDialog` on the Notes screen, the file was removed from storage, but its entry remained in the database, causing the note to still appear on the "Notes" screen after deletion. This issue has now been fixed.
* Added the UI test cases for both scenarios to avoid future errors.
https://github.com/user-attachments/assets/8ed5213a-a62d-4319-a4a0-1ca2fda81adb
=> Fixed: When a note is deleted, the corresponding file remained in storage.

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt
Fixes #4196 
* The issue was that we were setting the bottom margin to `0` when the fragment was moved to the background (i.e., when switching fragments) to prevent the bottom margin from affecting other screens. This was applied to the `NavHostContainer`, which hosts the reader fragment. Enabling the bottom margin when the fragment view is created worked in most cases. However, on Android 15, the system saves the fragment state and does not recreate the view, which means our margin-setting logic was not executed. As a result, the `bottomAppBar` appeared to disappear, but in reality, it was rendering behind the `BottomNavigationView` (the three options at the bottom).
* To fix this, we now set the bottom margin in the `onResume` method so that whenever the reader screen becomes visible, …
=> Fixed: The bottom bar disappears when reopening the app from the background.

app/src/androidTest/java/org/kiwix/kiwixmobile/testutils/TestUtils.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, custom/src/androidTest/java/org/kiwix/kiwixmobile/custom/search/SearchFragmentTestForCustomApp.kt, custom/src/androidTest/java/org/kiwix/kiwixmobile/custom/search/SearchRobot.kt, custom/src/androidTest/java/org/kiwix/kiwixmobile/custom/testutils/TestUtils.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt
Fixes #4200 
* The previously loaded article was not loading in custom apps when switching to another fragment and then returning to the reader screen. Instead, the home page of the ZIM file was loading. A fix has been implemented to resolve this issue.
* Added test cases for custom apps to cover this scenario and prevent future errors.
* Refactored some deprecated methods used in test cases.
* Improved the logic for handling search-related operations to ensure they are performed after tabs are fully restored.
* Previously, the search observation was initiated before the tabs were restored, causing the `FIND_IN_PAGE` feature to only work in the first tab. This happened because the webView list was empty at the time of observation.
* With the ZIM file opening and tab restoration now moved …
=> Fixed: `FIND_IN_PAGE` feature only works with first tab page.

app/src/main/res/values-ar/strings.xml, app/src/main/res/values-sv/strings.xml, custom/src/main/res/values-sv/strings.xml
=> Localisation updates from https://translatewiki.net.

README.md
~* Updated the playStore link in the README file. The previous link https://android.kiwix.org/ was not working and it is not the Play Store link.~
* Minor improvement in showing the directory path. See the image below; the second directory path does not look correct.
=> Minor improvement in showing the directory path in README file.

core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/DownloadManagerMonitor.kt, core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/DownloadMonitorService.kt, core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/FetchDownloadNotificationManager.kt
Fixes #4207 
* The Fetch library automatically removes the ongoing download notification when a download is paused. To improve the user experience, we have implemented custom logic to display a notification for paused downloads, allowing users to easily resume them.
* Additionally, Android 14 introduces a change that prevents non-dismissible notifications see for more details https://developer.android.com/about/versions/14/behavior-changes-all#non-dismissable-notifications. This means users can now dismiss notifications by swiping left or right. Since our app uses a foreground service for downloads, we must always display a notification. To handle this, we have implemented a mechanism that automatically adds the last notification to our foreground service to satisfy its need when no …
=> Fixed: Download notification disappears when pausing a download.

app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadTest.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModel.kt, app/src/test/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModelTest.kt, core/src/main/res/values/strings.xml
Fixes #4206 
* Added a new "Downloading:" section in `OnlineFragment` to display currently downloading books at the top.
* The language and search filter will not affect this meaning if a user selects another language and searches any ZIM file via the search feature, the "Downloading:" section always shows on the top and the filter will be applied to the remaining books.
https://github.com/user-attachments/assets/8e22d92c-ebe1-4ee5-94b2-b6c20472685e
* Refactored the `ZimManageViewModelTest` according to this new change.
* Refactored the `DownloadTest` which was failing after making this change.
=> Keeping the downloading books always at the top.

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt
Fixes #4213 
Moved shortcut creation to `lifecycleScope` to free up the main thread. This ensures the UI remains responsive while shortcuts are being created.
https://github.com/user-attachments/assets/d36b1305-10f5-4030-a883-6cfce970574b
https://github.com/user-attachments/assets/4b63f09d-87f7-4041-b8db-e337779b00e5
=> Fixed: `Input dispatching timed out` error while creating the application shortcuts.

app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragmentTest.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModel.kt
Fixes #4205
* Preserved search query across lifecycle changes to restore it when the fragment becomes visible again.
* Previously, when the device went to sleep, `viewLifecycleOwner` closed the search view due to lifecycle events, resetting the search.
* Now, the query is stored in `ViewModel` (which is lifecycle-aware) and restored when the online library screen is reopened.
* Search is reset only when the user explicitly clears it.
* Added `OnlineLibraryFragmentTest` instrumentation (UI) test case to test this new functionality.
https://github.com/user-attachments/assets/8d3a0e81-7512-4d44-bcc5-72bb3e197cfa
=> Fixed: When devices went to sleep mode, the search filter was reset of the online library.

CHANGELOG
* Updated the `CHANGELOG` file for milestone `3.14.0` to include the remaining changes made in this milestone.
* Corrected some English mistakes in the `CHANGELOG` file.
=> Updated the `CHANGELOG` file for milestone `3.14.0` to include the remaining changes made in this milestone.

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
Fixes #4224 
* The issue occurred because when moving to another fragment, the `ReaderScreen` remained in the backstack and was not fully destroyed along with its data. Additionally, we were storing the `SearchItem` and `FIND_IN_PAGE` queries in variables to perform these actions after restoring tabs. As a result, when reopening the `ReaderScreen`, the tabs were restored, and these variables retained their values, triggering the related actions again.
* To fix this, we have cleared these variables when the fragment is destroyed, as keeping them is unnecessary when the user navigates away from the reader screen.
https://github.com/user-attachments/assets/63044513-8219-413d-bfce-c94e966b25b6
=> Fixed: Opening SearchItem and FindInPage triggers again when switching back to the reader fragment.

core/src/main/res/values/strings.xml
Fixes #4086 
* There are 2 strings that we have refactored. See the below screenshots.
| Before  | After |
| ![Image](https://github.com/user-attachments/assets/d379a96a-3632-47c5-984f-b55b2546dfdd)  | ![CopyMoveFix](https://github.com/user-attachments/assets/3994e2db-cb40-42cd-b78c-5ba0e1aafca3)  |
| ![BeforeFixExternalDialog](https://github.com/user-attachments/assets/faee8fc3-1d65-47de-af4b-af9ca0ebb6b2)  | ![ExternalLinkAfter](https://github.com/user-attachments/assets/8761573c-b6cd-4709-aa35-b1358bef10ed)  |
=> Added carriage returns to improve readability in strings.

core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/DownloadMonitorService.kt, core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/FetchDownloadNotificationManager.kt
Fixes #4237 
* Two notifications were shown for a completed download when the app was in the background, the download was about to complete, and the app was then opened.
* This occurred because `DownloadMonitorService` pushed a download complete notification before detaching, while the app's lifecycle triggered Fetch to push another notification for the same completed download.
* The fix ensures that any previously completed notification is removed before showing a new one.
=> Fixed: Duplicate download completed notifications showing.

core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/DownloadMonitorService.kt, core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/FetchDownloadNotificationManager.kt, core/src/main/res/values-qq/strings.xml, core/src/main/res/values/strings.xml
Fixes #4236 
Apologies for the confusion! I accidentally closed the previous PR #4241 , so I'm resubmitting the changes here. 
This PR includes all requested changes. Please review again. Thank you!
1. Improving notification wording by replacing "starting" with "resuming" when a paused download is resuming
2. Replacing Default Fetch library strings with our own string resources to handle translation in other languages.
=> #4236 Improved download notification strings replacing default Fetch

core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt
Fixes #4234 
Added a white background to transparent images so that when reading a ZIM file in "Dark mode," the content of transparent images displays properly. It will not affect the image that does not have a transparent background, see in below videos.
https://github.com/user-attachments/assets/98e3612e-7912-4418-a4de-76c747645e2c
https://github.com/user-attachments/assets/a657a166-be1a-4acc-886c-9283cce3ee7b
=> Fixed: Transparent images were not visible in "Dark mode".

.github/workflows/dummy_bundle_and_apk.yml, .github/workflows/nightly.yml, .github/workflows/pull_request.yml, .github/workflows/release.yml, README.md, buildSrc/src/main/kotlin/plugin/AppConfigurer.kt
Fixes #4273 
* ABI splitting is now enabled only when needed (i.e., when building an APK) through an environment variable (APK_BUILD). By default, ABI splitting remains disabled for aab.
* Refactored the workflow to align with this change.
* Updated the README to document this change, ensuring that everyone is aware of this feature.
=> Fixed: After upgrading Gradle, we were unable to upload the AAB because APK splitting was enabled.

custom/build.gradle.kts
Since we upgraded Gradle, we switched to using `layout.buildDirectory` instead of `buildDir`, as the latter is now deprecated. The new approach returns a DirectoryProperty object instead of a direct build directory path. This caused our custom apps' CD pipeline to be unable to locate the generated `.aab` file. We have now updated the code to correctly retrieve the directory path from the `DirectoryProperty` object.
See uploading failure: https://github.com/kiwix/kiwix-android-custom/actions/runs/14241296835/job/39911608568
=> Fixed: AAB file was not found when uploading to Play Store for custom apps.

README.md
See https://github.com/kiwix/kiwix-android/issues/4287
Since there's no official Android Studio IDE that supports Android 16 yet — it's currently in the final beta phase and is expected to launch in May or possibly June — we need to use the `Canary build` of the `Narwhal` version for now. Therefore, we're updating the README file accordingly. Once the official IDE is released, we'll update the README again.
=> Updated the README file to reflect the compatible version of Android Studio.

README.md
The URL to the IzzySoft package includes `.standalone` on the end which was missing from the links
=> Update IzzySoft package URL in README

app/src/main/java/org/kiwix/kiwixmobile/language/LanguageFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/language/LanguageScreen.kt, app/src/main/java/org/kiwix/kiwixmobile/language/viewmodel/LanguageViewModel.kt, app/src/main/java/org/kiwix/kiwixmobile/language/viewmodel/SaveLanguagesAndFinish.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModel.kt, app/src/test/java/org/kiwix/kiwixmobile/language/viewmodel/LanguageViewModelTest.kt, app/src/test/java/org/kiwix/kiwixmobile/language/viewmodel/SaveLanguagesAndFinishTest.kt, app/src/test/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModelTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/dao/DownloadRoomDao.kt, core/src/main/java/org/kiwix/kiwixmobile/core/dao/NewLanguagesDao.kt, core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/DownloadManagerMonitor.kt, core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/DownloadMonitorService.kt, core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FlowExtension.kt
Fixes #4305 
* Removed duplicate method in `DownloadRoomDao` for fetching all downloads.
* Refactored `DownloadManagerMonitor` to use `Coroutines` instead of `RxJava`.
* Improved coroutine usage in `DownloadMonitorService`.
* Updated `LanguageViewModel` to use `Coroutine Flows` instead of `RxJava`.
* Refactored `NewLanguagesDao` to expose Coroutine Flows instead of `RxJava` observables.
* Updated `SaveLanguagesAndFinish` to use coroutines instead of `RxJava`.
* Created a `FlowExtension` utility class to add custom flow-related extensions. In this PR, added the `collectSideEffectWithActivity` extension function, which allows collecting `SideEffects` and handling them with the current Activity in a Compose UI. This also moved the `SideEffect` collection from the Fragment layer to the …
=> Refactored `RxJava` to `Coroutines` in `LanguageViewModel`.

app/src/main/java/org/kiwix/kiwixmobile/webserver/WebServerHelper.kt, app/src/main/java/org/kiwix/kiwixmobile/webserver/wifi_hotspot/HotspotService.kt
Fixes #4306 
* Refactored the IP address polling logic using coroutine Flow. Now the IP check runs on the IO thread and the result is pushed to the main thread, because our callbacks need to work on the main thread. Also, this whole operation will automatically cancel if the user switches the screen or if the given coroutine scope gets cancelled, since the scope is lifecycle-aware. This helps to avoid using extra resources unnecessarily.
* Added clear and concise method-level comments to improve code readability and help others easily understand the purpose and behavior of each method.
=> Refactored the `RxJava` code to use Kotlin `Coroutines` in `WebServerHelper`.

app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/bookmarks/BookmarksRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/bookmarks/LibkiwixBookmarkTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/history/NavigationHistoryTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/test/java/org/kiwix/kiwixmobile/core/dao/NewBookDaoTest.kt
Fixes #4320 
* The issue was caused by using `CoroutineScope(Dispatchers.Main)` while our flow directly accessed the `uuid` of the ZIM file from the `ZimFileReader` object. When the fragment was switched to another screen, the `ZimFileReader` object got disposed. However, the `webViewProgressChanged` method would still trigger, initiating the flow to check if the current page was bookmarked. Since the `ZimFileReader` was already disposed, this resulted in a crash.
* We fixed this by using the viewLifecycleOwner.lifecycleScope so that the job is automatically cancelled when the fragment is destroyed. Additionally, we now retrieve the uuid once at the beginning and reuse it in the flow, avoiding repeated access to the disposed ZimFileReader.
* Improved the `testBookmarks` test case. …
=> Fixed: CI sometimes crashes on `testBookmarks`.

core/detekt_baseline.xml, core/src/main/java/org/kiwix/kiwixmobile/core/zim_manager/Byte.kt
Fixes #4368 
* Changed the size calculation from GiB (binary format) to GB (decimal format).
* Removed the unused `OnSwipeTouchListener` class.
| Before(binary foramt)  |  After(decimal format) |
| <img width="464" height="807" alt="Screenshot from 2025-08-08 14-33-43" src="https://github.com/user-attachments/assets/0d29c894-0275-4aad-94a8-4d0ef3b6da52" /> |  <img width="464" height="807" alt="Screenshot from 2025-08-08 16-17-50" src="https://github.com/user-attachments/assets/0c600223-99af-4e50-b258-1d1ba5cf962d" /> |
| <img width="464" height="807" alt="Screenshot from 2025-08-08 16-14-06" src="https://github.com/user-attachments/assets/1bc063a3-93fe-441b-beb8-9b7cf67253f9" /> |  <img width="464" height="807" alt="Screenshot from 2025-08-08 16-17-56" …
=> Fixed: File size unit / calculation differs from Kiwix-Server.

app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/reader/ReaderRobot.kt, app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt, app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivityScreen.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/reader/CoreReaderFragment.kt
Fixes #4379 
* Fixed: When launching the app fresh (cold start), the search screen could appear before the ZIM file was ready (because ZIM file loading in the reader happens on the IO thread), resulting in no search results. Now, incoming actions are delayed until the ZIM file finishes loading so that the search works correctly.
* Fixed: Multiple fragment instances were created when repeatedly opening different fragments via bottomAppBar buttons, causing the back button to bring them to the foreground one by one instead of the expected behavior.
=> Fixed: When opening the search from widget or from outside the application then search is broken with large ZIM files.

app/src/androidTest/java/org/kiwix/kiwixmobile/page/bookmarks/BookmarksRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/bookmarks/LibkiwixBookmarkTest.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModel.kt, app/src/test/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModelTest.kt
Fixes #4381 
* Cause: The request object emitted after user confirmation was identical to the previous one, so the flow collector skipped it, and the fetch was never triggered.
* Solution: Added a `System.nanoTime()` field to the request to ensure a unique emission while still preserving existing values.
* Refactored the `updateOnlineLibraryFilters updates onlineLibraryRequest` according to this new change.
* Improved the `testBookmarkRemainsSavedOrNot`, which sometimes fails on Android 15 and 16.
| <video src="https://github.com/user-attachments/assets/51320366-58c8-49d7-b327-a508e9bdb724" />  |  <video src="https://github.com/user-attachments/assets/26ca83d1-fcdf-408f-8768-180f2c09eda5" /> |
=> Fixed: Online library was not retrieving after clicking “Allow downloading via mobile network” in the confirmation dialog.

app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteRobot.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt, core/src/main/java/org/kiwix/kiwixmobile/core/ui/components/KiwixSearchView.kt
Fixes #4385
* Updated the placeholder text to display on a single line and show an ellipsis (...) at the end if the text is too long.
* Fixed: `testUserCanSeeNotesForDeletedFiles` which sometimes fails on CI due to `androidx.test.espresso.base.RootViewPicker$RootViewWithoutFocusException`.
| ![Image](https://github.com/user-attachments/assets/d017da4b-d22c-4e5a-bac2-af226a3660b7)  |  ![SearchPlaceholderFix](https://github.com/user-attachments/assets/199c043e-8c7a-4b69-be10-c690ad1386a4) |
=> Fixed: The search placeholder was cut off in the `Romansh` language.

app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadTest.kt, app/src/test/java/org/kiwix/kiwixmobile/language/viewmodel/LanguageViewModelTest.kt, app/src/test/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModelTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/settings/CoreSettingsFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/ui/components/KiwixAppBar.kt, custom/src/test/java/org/kiwix/kiwixmobile/custom/download/CustomDownloadViewModelTest.kt
Fixes #4387 
* The issue occurred because we reopened the settings screen immediately after removing it from the back stack, causing Compose to not settle the previous frame and display a blank screen.
* Resolved by allowing the popBackStack frame to settle before reopening the settings screen.
* Removed some unused code from the project.
* Improved the `testPauseAndResumeInOtherLanguage` according to this change.
* Fixed: `observeLanguages uses network when no cache and online`, and `updateOnlineLibraryFilters updates onlineLibraryRequest` which sometimes fails on CI.
| <video src="https://github.com/user-attachments/assets/1df9be83-683d-4302-8475-df906154c96f" />  |  <video …
=> Fixed: When changing the app's language, a blank screen appeared instead of the settings screen.

app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/bookmarks/BookmarksRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/bookmarks/LibkiwixBookmarkTest.kt, app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/reader/CoreReaderFragment.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomMainActivity.kt
Fixes #4390 
* The issue occurred because the reader screen route was not being created properly, as both modules had different destination classes. We made the openPage method abstract so that each module can provide its own destination with arguments to correctly open pages.
* Improved WebView creation in Compose.
* Added UI test cases for bookmarks and notes to verify that saved items open the exact page in the reader.
=> Fixed: Opening bookmarks, notes, and history in the reader screen does not work.

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/online/OnlineLibraryScreen.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModel.kt
Fixes #4394 
* Removed the code that auto-scrolled the list to show the progress bar. Now, users will see the progress bar only when they scroll down to load more items(which is ideal).
* Improved `isLoadingMoreItem` handling to avoid duplicate `loadMore` calls after appending items
=> Fixed: Online library sometimes automatically loaded more items without user input.

app/src/androidTest/java/org/kiwix/kiwixmobile/webserver/ZimHostFragmentTest.kt, app/src/main/java/org/kiwix/kiwixmobile/webserver/ZimHostFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/webserver/ZimHostPresenter.kt, core/src/main/java/org/kiwix/kiwixmobile/core/base/BaseContract.kt, core/src/main/java/org/kiwix/kiwixmobile/core/base/BasePresenter.kt
Fixes #4409 
* The issue occurred when reopening the `ZimHostScreen`. The presenter was detaching the view of the previous `ZimHostScreen`, but since the presenter is a singleton, it also cleared the reference to the view attached to the new `ZimHostScreen`. As a result, the `ZimHostPresenter` could not post books because the view reference was null.
* Updated `BasePresenter` so that it only detaches the view if it matches the one currently attached, preventing accidental clearing of the new screen’s view.
* Added `testZIMFilesShowingOnZimHostScreen` UI test case for testing this scenario so that we can avoid this type of error in the future.
| <video src="https://github.com/user-attachments/assets/e5800f46-53b3-40c5-8049-d46983 …
=> Fixed: Hotspot list of books appearing empty(when reopening the ZimHostScreen).

app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomMainActivity.kt
Fixes #4416
* In Compose, when the screen rotates and the screen width is above `600dp`, the `drawerState` is automatically set to `open`. Because of this, the issue was happening.
* Now we are storing the `drawerState` and updating the `leftDrawerState` based on the previously saved value when the orientation changes.
* Fixed: `LongMethod` lint error.
| <video src="https://github.com/user-attachments/assets/722364d4-29be-412f-a11d-114afc47abd6" /> | <video src="https://github.com/user-attachments/assets/53bf32c1-2c56-4a41-9d56-88540a4fa197"/>  |
=> Fixed: The `LeftDrawer` automatically opens when we rotate the screen.

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/reader/CoreReaderFragment.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt
Fixes #4418 
1. Tabs not restoring in custom apps:
* This happened because we moved the file scanning logic to the IO thread, and inside that, we were also opening the ZIM file in the reader on the IO thread, and then restoring the tabs (which is now done on the Dispatcher’s main thread instead of the UI main thread). Because of this, the WebView was loading freely and saving new history in the database, which cleared the previous history. As a result, the tabs were not restoring.
* Now, we are not saving new WebView history while restoring tabs, which avoids this issue in a multi-threading environment.
* Made `restoreViewStateOnValidWebViewHistory` and `restoreViewStateOnInvalidWebViewHistory` suspend functions so they can run in the same scope from where we are opening and restoring …
=> Fixed: The Tabs history is not restoring in custom apps.

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/online/DownloadBookItem.kt, core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/FetchDownloadNotificationManager.kt
Fixes #4359 
* Displaying the downloaded size and total size in the download notification.
* Merged the download state and ETA. Now, when the download is "In Progress", it shows the ETA. Otherwise, it displays the download status as before.
https://github.com/user-attachments/assets/7ee79b5a-6f0a-4964-864b-97ce31bb5e36
=> Fixed: Show the downloaded size and total file size in the download notification.

core/src/main/java/org/kiwix/kiwixmobile/core/search/SearchFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchState.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModel.kt, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchStateTest.kt, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModelTest.kt
Fixes #4399 
* Both the initial search (while typing, was already on IO thread) and loading of additional items have been moved to the IO thread, keeping the UI thread free and ensuring a smoother user experience.
* Optimized result fetching from libkiwix: previously, 100 results were retrieved for every typed character. This was inefficient, as users often continue typing and most of those results went unused.
* Even though ongoing requests were canceled when users typed further, fetching 100 results at a time was still wasteful. Once the native C++ code started processing, it consumed memory(as it do not immediately cancel the ongoing process), regardless of cancellation.
* The default has now been adjusted to fetch 20 results per search instead of 100. This reduces memory usage, …
=> Improved search performance on low-memory devices.

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/local/LocalLibraryFragment.kt
Fixes #4427 
Previously, it displayed all files in storage, which caused hangs on devices with large file sets. We have now restricted the file picker to only show files under the "application/*" MIME type, since ZIM files also fall under this type.
=> Improved the file picker to list only ZIM files, reducing the load on the picker.

app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchFragmentTest.kt, app/src/main/java/org/kiwix/kiwixmobile/language/LanguageFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/online/OnlineLibraryFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/PageFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/SearchFragment.kt
Fixes #4456 
* This issue occurred because the exact text from the search box was passed, including unnecessary spaces, which caused libkiwix to return no results. The search term is now trimmed before being passed to libkiwix, ensuring extra spaces are removed.
* The same fix has been applied to PageFragment (for bookmarks, notes, and history) as well as the language list and online content search.
* Added UI test case for this so that we can avoid this type of errors in future.
| Before Fix | After Fix |
|---------------|-------------|
| <video src="https://github.com/user-attachments/assets/e79d438b-fed4-48b2-b79b-e2c8ff7bb6a1" /> | <video src="https://github.com/user-attachments/assets/090905bb-5f89-4991-883f-a9e1a5f67abc" />
=> Fixed: Search results disappear after typing a space.
