kiwix/kiwix-android

.travis.yml, build.gradle, gen-custom-android-build.py, gradle/wrapper/gradle-wrapper.properties, install-kiwix-on-device.sh
Beware all the nice dependency management has been moved to kiwix-build.
$ANDROID_HOME must be set and the correct SDK features installed.
=> Fix custom app generation

src/org/kiwix/kiwixmobile/downloader/DownloadFragment.java
Various fixes to state weirdness when stopping/pausing/resuming downloads
=> Download stop button now pauses downloads and handles resume state

app/build.gradle
Code doesn't set up flavours for each custom app if the custom app directory doesnt exist.
=> Minor Code added in gradle file

app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadFragment.java, app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadService.java, app/src/main/res/layout/download_item.xml, app/src/main/res/values/strings.xml
=> Estimation of download remaining time

app/src/main/java/org/kiwix/kiwixmobile/ZimContentProvider.java
Last PR #147 was incomplete and it has been merged to quickly.
=> Look for the right icu data filename

app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.java, app/src/main/res/layout/language_check_item.xml
=> Make whole row in language picker clickable.

app/src/main/java/org/kiwix/kiwixmobile/utils/NetworkUtils.java, app/src/main/res/values/strings.xml
We create now ZIM files which include pictures but not video/audio files.
=> Support _novid ZIM files

app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/tests/BasicTest.java, app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java, app/src/main/java/org/kiwix/kiwixmobile/SearchActivity.java, app/src/main/java/org/kiwix/kiwixmobile/ZimContentProvider.java, app/src/main/java/org/kiwix/kiwixmobile/bookmarks_view/BookmarksPresenter.java, app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadFragment.java, app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadService.java, app/src/main/java/org/kiwix/kiwixmobile/settings/KiwixSettingsActivity.java, app/src/main/java/org/kiwix/kiwixmobile/utils/KiwixTextToSpeech.java, app/src/main/java/org/kiwix/kiwixmobile/utils/LanguageUtils.java, app/src/main/java/org/kiwix/kiwixmobile/utils/NetworkUtils.java, app/src/main/java/org/kiwix/kiwixmobile/utils/RateAppCounter.java, app/src/main/java/org/kiwix/kiwixmobile/views/AutoCompleteAdapter.java, app/src/main/java/org/kiwix/kiwixmobile/views/web/ToolbarScrollingKiwixWebView.java, app/src/main/java/org/kiwix/kiwixmobile/views/web/ToolbarStaticKiwixWebView.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.java
Doing manually, what ProGuard could do automatically.
=> Remove more unused code

app/src/main/java/org/kiwix/kiwixmobile/KiwixApplication.java, app/src/main/java/org/kiwix/kiwixmobile/bookmarks_view/BookmarksPresenter.java, app/src/main/java/org/kiwix/kiwixmobile/views/SliderPreference.java, app/src/main/java/org/kiwix/kiwixmobile/views/web/KiwixWebView.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectPresenter.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryPresenter.java
Doing manually, what ProGuard could do automatically.
=> Remove methods that are identical to their super implementation

app/build.gradle, app/src/main/java/org/kiwix/kiwixmobile/settings/KiwixSettingsActivity.java
=> Fix custom version numbers

app/build.gradle
=> Bump android-storage-devices

app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/di/modules/TestNetworkModule.java, app/src/main/java/org/kiwix/kiwixmobile/di/modules/ApplicationModule.java, app/src/main/java/org/kiwix/kiwixmobile/di/modules/NetworkModule.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.java
=> We now inject the network state so that the rest of the test is able to run

app/src/main/java/org/kiwix/kiwixmobile/views/AutoCompleteAdapter.java, app/src/main/res/xml/preferences.xml
=> Default and remove preference for fulltext search

app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadFragment.java, app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadService.java
=> Some work on Download Service

app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadService.java
I corrected typos in various comments. There shouldn't be any change to the behaviour.
=> Replaced chuck with chunk in this code. A minor change.

app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java, app/src/main/java/org/kiwix/kiwixmobile/KiwixWebViewClient.java, app/src/main/java/org/kiwix/kiwixmobile/ZimContentProvider.java, app/src/main/java/org/kiwix/kiwixmobile/database/KiwixDatabase.java, app/src/main/java/org/kiwix/kiwixmobile/utils/KiwixTextToSpeech.java, app/src/main/java/org/kiwix/kiwixmobile/utils/LanguageUtils.java, app/src/main/java/org/kiwix/kiwixmobile/utils/NetworkUtils.java, app/src/main/java/org/kiwix/kiwixmobile/views/web/KiwixWebView.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryPresenter.java
Related reading:
https://www.javacodegeeks.com/2011/01/10-tips-proper-application-logging.html
https://github.com/kiwix/kiwix-android/issues/252
There are a few places it'd be nice to look into further. My Java Fu isn't quite up to scratch (_yet_!)
Most notably:
- KiwixWebViewClient.java Line 52
- ZimContentProvider.java Line 372
@mhutti1 Is it worth keeping the log there? It seems some information might be getting lost.
Updated Report as of this PR
[Kiwix 2.pdf](https://github.com/kiwix/kiwix-android/files/1251944/Kiwix.2.pdf)
=> Minor logging changes

app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java, app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadService.java, app/src/main/java/org/kiwix/kiwixmobile/utils/files/FileUtils.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.java
https://github.com/kiwix/kiwix-android/issues/252
Based on results from https://github.com/ISNIT0/log-complexity-comparison I added logging where it seemed most useful.
[Logs And Complexity (1).pdf](https://github.com/kiwix/kiwix-android/files/1322005/Logs.And.Complexity.1.pdf)
=> Added some logging

app/build.gradle
This fixes the issue with arm devices.
=> Bump kiwixlib version

app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadFragment.java, app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadService.java
=> Move download completion logic to onComplete subscription

app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java, app/src/main/java/org/kiwix/kiwixmobile/KiwixWebViewClient.java, app/src/main/java/org/kiwix/kiwixmobile/settings/KiwixSettingsActivity.java, app/src/main/res/values-pl/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
=> External links popup

app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java, app/src/main/res/layout/main.xml, app/src/main/res/values/colors.xml
=> Improve back to top button redability in night mode

app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java
It resolves problem in #156, but when both animations (drawer closing and menu opening) are played, it's not smooth 60fps.
I want to hear feedback about this issue.
=> [Possibly WIP] Fix #156

app/src/main/java/org/kiwix/kiwixmobile/ZimContentProvider.java
=> Fixed duplicate search

app/src/main/java/org/kiwix/kiwixmobile/utils/StorageUtils.java
This should be a nop, just good to help keep our code a bit tidier.
=> Removed unused imports.

app/src/main/java/org/kiwix/kiwixmobile/utils/StorageUtils.java, app/src/main/res/xml/preferences.xml
A minor change, to enable users to understand the purpose of the 'prefer wifi' setting.
=> Improve the UI in the Preferences screen.

app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java, app/src/main/java/org/kiwix/kiwixmobile/KiwixWebViewClient.java, app/src/main/java/org/kiwix/kiwixmobile/SearchActivity.java, app/src/main/java/org/kiwix/kiwixmobile/ZimContentProvider.java, app/src/main/java/org/kiwix/kiwixmobile/bookmarks_view/BookmarksActivity.java, app/src/main/java/org/kiwix/kiwixmobile/database/KiwixDatabase.java, app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadFragment.java, app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadService.java, app/src/main/java/org/kiwix/kiwixmobile/settings/KiwixSettingsActivity.java, app/src/main/java/org/kiwix/kiwixmobile/utils/Constants.java, app/src/main/java/org/kiwix/kiwixmobile/utils/KiwixTextToSpeech.java, app/src/main/java/org/kiwix/kiwixmobile/utils/LanguageUtils.java, app/src/main/java/org/kiwix/kiwixmobile/utils/NetworkUtils.java, app/src/main/java/org/kiwix/kiwixmobile/utils/files/FileSearch.java, app/src/main/java/org/kiwix/kiwixmobile/utils/files/FileUtils.java, app/src/main/java/org/kiwix/kiwixmobile/views/AutoCompleteAdapter.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.java
This patch is a part of #169. It needs a little of a review though.
=> Move majority of hardcoded consts to separate file

app/build.gradle, app/src/main/java/org/kiwix/kiwixmobile/ZimContentProvider.java
=> Update JNI and catch the new exception thrown by an invalid ZIM

app/src/main/java/org/kiwix/kiwixmobile/KiwixWebViewClient.java, app/src/main/java/org/kiwix/kiwixmobile/SearchActivity.java, app/src/main/java/org/kiwix/kiwixmobile/bookmarks_view/BookmarksActivity.java, app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadFragment.java, app/src/main/java/org/kiwix/kiwixmobile/library/LibraryAdapter.java, app/src/main/java/org/kiwix/kiwixmobile/settings/KiwixSettingsActivity.java, app/src/main/java/org/kiwix/kiwixmobile/views/AutoCompleteAdapter.java, app/src/main/java/org/kiwix/kiwixmobile/views/CompatFindActionModeCallback.java, app/src/main/java/org/kiwix/kiwixmobile/views/SliderPreference.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.java
Closes #359 
Changes: Removed redundant View casting from the whole project.
=> chore: Remove redundant view casting in the project

app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java, app/src/main/java/org/kiwix/kiwixmobile/KiwixWebViewClient.java, app/src/main/java/org/kiwix/kiwixmobile/SearchActivity.java, app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadService.java, app/src/main/java/org/kiwix/kiwixmobile/settings/KiwixSettingsActivity.java, app/src/main/java/org/kiwix/kiwixmobile/utils/LanguageUtils.java, app/src/main/java/org/kiwix/kiwixmobile/views/web/KiwixWebView.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryPresenter.java
Closes #363 
Changes: Replaced all anonymous classes with lambdas in the whole project.
=> refactor: Replace anonymous classes with lambdas

app/src/main/java/org/kiwix/kiwixmobile/library/LibraryAdapter.java
closes #369 
Changes: Converted SaveNetworkLanguages AsyncTask to run with RxJava schedulers.
=> refactor: Convert SaveNetworkLanguages AsyncTask to run with RxJava

app/src/main/java/org/kiwix/kiwixmobile/settings/KiwixSettingsActivity.java, app/src/main/res/values/styles.xml
**Description**
On changing mode from day to night, fade in and out animations added for smooth transition.
Fixes #371
=> Fade in/out effect added during transition from day to night mode

app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/tests/BasicTest.java
=> Fix basicTest method to run from any page

app/src/main/java/org/kiwix/kiwixmobile/utils/StyleUtils.java, app/src/main/res/values/styles.xml
=> Fix colors

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Fixes #358 
Changes: Added issues and PR template to the project.
=> feat: Add issues and PR template to the project

app/src/main/java/org/kiwix/kiwixmobile/di/components/ApplicationComponent.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/SectionsPagerAdapter.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManagePresenter.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewCallback.java
Closes: #386 
Changes: Implemented ZimManageActivity according to MVP pattern.
Moved SectionsPagerAdapter to a separate class.
=> refactor: Implement ZimManageActivity according to MVP pattern

app/src/main/java/org/kiwix/kiwixmobile/database/KiwixDatabase.java, app/src/main/java/org/kiwix/kiwixmobile/di/modules/ApplicationModule.java, app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadFragment.java, app/src/main/java/org/kiwix/kiwixmobile/utils/DimenUtils.java, app/src/main/java/org/kiwix/kiwixmobile/utils/LanguageUtils.java, app/src/main/java/org/kiwix/kiwixmobile/utils/NetworkUtils.java
closing https://github.com/kiwix/kiwix-android/issues/431
Closed all unused import statements in respective java classes.
=> Deleted all unused import statements

app/src/main/java/org/kiwix/kiwixmobile/settings/KiwixSettingsActivity.java
Fixes #426
Changes: Dialog Box style changes as soon as mode is changed.
=> Dialog Box style changes in settings itself

app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.java, app/src/main/res/layout/activity_library.xml, app/src/main/res/layout/download_management.xml, app/src/main/res/values/dimens.xml
Fixes #441 
**Changes:** [Add here what changes were made in this issue and if possible provide links.]
created textview widget on activity_library.xml that has the same properties as the one on download_management.xml, and then referenced the new textview instead of the old one in LabraryManagement.java.
**Screenshots/GIF for the change:** [If possible, please add relevant screenshots/GIF]
=> Font Corrected

app/src/main/res/values/styles.xml
Fixes #453 
Changes: [Add here what changes were made in this issue and if possible provide links.]
=> change font color in clear history dialog box

app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.java
Fixes #466 
Changes:
menu.findItem(R.id.action_search).expandActionView();
=> Fixed Deprecated Method

app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java
The bug is resolved. Please verify and let me know if I have to make any changes.
=> Full Screen Bug

.github/ISSUE_TEMPLATE.md
Changes: I fixed some minor grammatical errors. I also removed the *browser/ app* line from the environment description section as I didn't understand its significance here.
=> Fix minor grammatical errors in ISSUE_TEMPLATE.md

app/src/main/java/org/kiwix/kiwixmobile/settings/KiwixSettingsActivity.java, app/src/main/res/values-v19/styles.xml, app/src/main/res/values-v21/styles.xml, app/src/main/res/values/styles.xml, app/src/main/res/xml/preferences.xml
- Fix app language preference list for RTL language.
- Use radio buttons to show language preference.
Fixes #491
All the problems described in the issue have been fixed. Also, the language list now loads faster.
=> Fix app language preference for RTL languages

docs/codestyle.md
Fixes #519
Changes: Included codestyle guidelines to be followed for XML files.
=> Refactor: Explicitly include codestyle for XML files

app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java
Fixes #520 
Changes: Added the fix for lower api versions, it removes the white space/cut off issue between the action bar and the status bar in lower API levels.
@mhutti1 @brijeshshah13 Please check.
=> Action bar gets cut off resolved #520

app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java, app/src/main/java/org/kiwix/kiwixmobile/bookmarks_view/BookmarksActivity.java, app/src/main/java/org/kiwix/kiwixmobile/di/components/ApplicationComponent.java, app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadFragment.java, app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadService.java, app/src/main/java/org/kiwix/kiwixmobile/search/SearchActivity.java, app/src/main/java/org/kiwix/kiwixmobile/settings/KiwixSettingsActivity.java, app/src/main/java/org/kiwix/kiwixmobile/utils/Constants.java, app/src/main/java/org/kiwix/kiwixmobile/utils/LanguageUtils.java, app/src/main/java/org/kiwix/kiwixmobile/utils/SharedPreferenceUtil.java, app/src/main/java/org/kiwix/kiwixmobile/views/AutoCompleteAdapter.java, app/src/main/java/org/kiwix/kiwixmobile/views/web/KiwixWebView.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.java
Fixes #168 
Changes: Added a SharedPreferenceUtil class to unify the default SharedPreference operations.
Screenshots/GIF for the change: NA
@brijeshshah13 @arpank10 @RajaVamsi11 @siddharth2010 @abdulwd @RohanBh @knightcube I would request you guys to kindly download this PR locally, build it and test the application for bugs if any. I have checked it but it will good to have others look into this. Thanks.
=> Refactor: Unify Default Shared Preferences using SharedPreferenceUtil

app/src/main/java/org/kiwix/kiwixmobile/search/SearchActivity.java
Fixes #567 
Changes: Preserved the original contents of search results that contained html style information.
=> Fix articles not opening from global search

app/src/main/java/org/kiwix/kiwixmobile/utils/SharedPreferenceUtil.java
=> Fix: Applied transaction for "isFirstRun" in SharedPreferenceUtil

app/build.gradle, app/src/main/java/org/kiwix/kiwixmobile/KiwixApplication.java
Fixes #364 
Changes: Configure Leak-canary for the project.
One thing to note is that we need to add dependencies to the release and test builds also. 
[Here](https://github.com/square/leakcanary/issues/139) is a github issue for this discussion. It's not a problem though since the apk size won't get affected that much.
Screenshots/GIF for the change: NA
=> Feat: Add Leakcanary to the project

app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/tests/DownloadTest.java
Quick temp fix for #283
Changes: Add wait for test.
=> Add wait to download test as a quick test fix

docs/codestyle.md
We're actually using square's style guide. Google's collapses annotations.
=> Update code style

app/build.gradle, app/src/main/java/org/kiwix/kiwixmobile/KiwixApplication.java, app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java, app/src/main/java/org/kiwix/kiwixmobile/ZimContentProvider.java, app/src/main/java/org/kiwix/kiwixmobile/base/BaseActivity.java, app/src/main/java/org/kiwix/kiwixmobile/base/BaseFragment.java, app/src/main/java/org/kiwix/kiwixmobile/bookmarks_view/BookmarksActivity.java, app/src/main/java/org/kiwix/kiwixmobile/di/components/ApplicationComponent.java, app/src/main/java/org/kiwix/kiwixmobile/di/modules/ActivityBindingModule.java, app/src/main/java/org/kiwix/kiwixmobile/di/modules/ApplicationModule.java, app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadFragment.java, app/src/main/java/org/kiwix/kiwixmobile/search/SearchActivity.java, app/src/main/java/org/kiwix/kiwixmobile/settings/KiwixSettingsActivity.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManagePresenter.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.java, build.gradle
Fixes #591 and part of #615 
Changes: Update **Dagger** version, fix some memory leaks, remove lint warning and some code cleanup.
@mhutti1 Please review. _networkTest_ and _downloadTest_ are sometimes failing which are also failing on _master_ branch. I request you to please merge this PR ASAP as afterward resolving conflicts will be difficult. :)
After it is merged I will fix #615.
=> Update to Dagger 2.15

app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/tests/SettingsTest.java, app/src/main/java/org/kiwix/kiwixmobile/utils/SharedPreferenceUtil.java, app/src/main/res/xml/preferences.xml
Changes: Disable multizim option for 2.4
=> Disable multizim search for 2.4

app/src/androidTest/java/org/kiwix/kiwixmobile/database/KiwixDatabaseTest.java, app/src/main/java/org/kiwix/kiwixmobile/KiwixErrorActivity.java, app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java, app/src/main/java/org/kiwix/kiwixmobile/bookmarks_view/BookmarksActivity.java, app/src/main/java/org/kiwix/kiwixmobile/bookmarks_view/BookmarksPresenter.java, app/src/main/java/org/kiwix/kiwixmobile/database/BookDao.java, app/src/main/java/org/kiwix/kiwixmobile/database/BookmarksDao.java, app/src/main/java/org/kiwix/kiwixmobile/database/KiwixDatabase.java, app/src/main/java/org/kiwix/kiwixmobile/database/NetworkLanguageDao.java, app/src/main/java/org/kiwix/kiwixmobile/database/RecentSearchDao.java, app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadService.java, app/src/main/java/org/kiwix/kiwixmobile/library/LibraryAdapter.java, app/src/main/java/org/kiwix/kiwixmobile/search/SearchActivity.java, app/src/main/java/org/kiwix/kiwixmobile/search/SearchPresenter.java, app/src/main/java/org/kiwix/kiwixmobile/settings/KiwixSettingsActivity.java, app/src/main/java/org/kiwix/kiwixmobile/views/web/KiwixWebView.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectPresenter.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryPresenter.java
Fixes #615 
Continuation of #696
=> Fix memory leaks 

app/src/main/java/org/kiwix/kiwixmobile/KiwixErrorActivity.java, app/src/main/java/org/kiwix/kiwixmobile/di/modules/ActivityBindingModule.java
=> Add dependency injection in KiwixErrorActivity

app/src/main/AndroidManifest.xml, app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.java, app/src/main/res/drawable/ic_add_blue_24dp.xml, app/src/main/res/drawable/ic_file_download_blue_24dp.xml, app/src/main/res/drawable/ic_shortcut_get_content.xml, app/src/main/res/drawable/ic_shortcut_new_tab.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml-v25/shortcuts.xml
Fixes #688 
Changes: Added static shortcuts in the app.
=> Add app shortcuts

app/build.gradle, app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/utils/files/FileUtilsInstrumentationTest.java, app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/utils/files/FileUtilsTest.java, app/src/main/java/org/kiwix/kiwixmobile/utils/files/FileUtils.java, app/src/test/java/org/kiwix/kiwixmobile/downloader/ChunkUtilsTest.java, app/src/test/java/org/kiwix/kiwixmobile/utils/files/FileUtilsTest.java
Add Unit Tests for downloader/ChunkUtils and for utils/files/FileUtils
=> Add more Unit Tests

app/build.gradle, app/src/main/java/org/kiwix/kiwixmobile/utils/SplashActivity.java
Fixes #757 
Changes:Disables crash activity on debug builds.
=> Remove crash activity from debug builds

app/src/main/java/org/kiwix/kiwixmobile/search/SearchActivity.java
Fixes #760 
Changes: Fix search for titles with special characters by using the base text to search for the title not the rendered text.
=> Fix search for titles with special characters

app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.java
Fixes #747 
Changes: Request write permission not read.
=> Request write permission instead of read

app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java, app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadService.java
Changes: Pause DownloadService if network is not available
Noticed the issue while trying to reproduce "SSL exception #675"
=> Pause download service if no network

app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java
Changes: Fixes bookmarks crash
=> Fix crash when attempting to bookmark help

app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java, app/src/main/java/org/kiwix/kiwixmobile/database/BookDao.java, app/src/main/java/org/kiwix/kiwixmobile/downloader/ChunkUtils.java, app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadFragment.java, app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadService.java, app/src/main/java/org/kiwix/kiwixmobile/utils/files/FileUtils.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.java
=> Improve download stablity and rename partial download fragments

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/test_request.md
=> Create new Issue template for "Tests"

app/src/main/java/org/kiwix/kiwixmobile/data/DataSource.java, app/src/main/java/org/kiwix/kiwixmobile/data/Repository.java, app/src/main/java/org/kiwix/kiwixmobile/downloader/DownloadService.java, app/src/main/java/org/kiwix/kiwixmobile/main/MainPresenter.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectPresenter.java
=> Fix ConcurrentModificationException

gradle.properties
To be able to compile the custom apps
=> More memory for compilation

app/build.gradle, app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/help/HelpActivityTest.java, app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/intro/IntroActivityTest.java, app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/splash/SplashActivityTest.java, app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/tests/activities/BookmarksActivityTest.java, app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/tests/activities/SearchActivityTest.java, app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/tests/activities/SettingsActivityTest.java, app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/tests/activities/ZimManageActivityTest.java, app/src/main/java/org/kiwix/kiwixmobile/main/KiwixTextToSpeech.java, app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java, app/src/main/res/mipmap-anydpi-v26/kiwix_icon.xml, app/src/main/res/mipmap-anydpi-v26/kiwix_icon_round.xml, build.gradle, gradle.properties
=> Fix memory leak in text to speech

app/build.gradle
...you'll need to reTag 2.4 after merge
=> Fix versionName

app/build.gradle, app/src/main/res/layout/search.xml, build.gradle, gradle.properties
Fixes #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Changes: [Add here what changes were made in this issue and if possible provide links.]
=> Updated the gradle files.

build.gradle
=> Increase Testdroid Plugin Version

app/src/main/java/org/kiwix/kiwixmobile/views/PageBottomTabLayoutSnackBarBehavior.java, app/src/main/res/layout/main.xml
Fixes #579
Changes: Created PageBottomTabLayoutSnackBarBehavior and binded to PageBottomTabLayout in main.xml, not used Relative Layouts removed
=> Snackbar over bottom toolbar fixed

app/src/main/java/org/kiwix/kiwixmobile/search/SearchActivity.java, build.gradle
Fixes Issue #841  
Changes: The Find In Page button disappears on starting typing and reappears when the search field is empty.
=> Search Find In Page button customized

.editorconfig
see https://editorconfig.org/ for details, quite a number of editors
support it out of the box. fixes #923.
Fixes #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Changes: [Add here what changes were made in this issue and if possible provide links.]
=> add .editorconfig to make formatting rules more explicit

build.gradle, gradle/wrapper/gradle-wrapper.properties
update gradle to newest version, first to use newest android studio, and second to expose deprecated features which will be not any more in gradle-6.
=> update gradle to newest version

docs/codestyle.md
Update the XML Indentation values in the CodeStyle.
=> Change indentation values in Codestyle

app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java
Fix #936 
- I've broken the code in MainActivity's onCreate() by separating the code that is doing same type of task.
- I've separated the code in a total of 6 functions 
- I've also tried to give the methods a readable name that is easy for other developers to understand.
- The code is now much more readable and looks structured.
=> Fix #936 : Improve code structure in Main Activity's onCreate() by Adding Functions

CONTRIBUTING.md
Minor typo in CONTRIBUTIONS.md.
Testing if project forked and integrated with GitHub correctly.
P.s: I am new (very new) here. Want to start contributing. Can someone help?
=> Minor typo in CONTRIBUTIONS.md

app/build.gradle, app/src/androidTestKiwix/java/org/kiwix/kiwixmobile/help/HelpActivityTest.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.java, build.gradle.kts, gradle.properties
Fixes #1003 and various other issues
Changes: - See git commit messages
=> Local and Travis Test fixes

.travis.yml, app/build.gradle, testdroid.py
Switches to using a test gateway between travis and testdroid so that forks can run full tests.
=> Test Gateway

app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/ZimFileSelectFragment.java
Share button is not working in Device Fragment #945
Changes:For API 24 file transfer changes so checking the API level.
=> Share button is not working in Device Fragment #945

app/src/main/java/org/kiwix/kiwixmobile/base/BaseActivity.java, app/src/main/java/org/kiwix/kiwixmobile/bookmark/BookmarksActivity.java, app/src/main/java/org/kiwix/kiwixmobile/history/HistoryActivity.java, app/src/main/java/org/kiwix/kiwixmobile/settings/KiwixSettingsActivity.java, app/src/main/res/layout/activity_help.xml, app/src/main/res/layout/settings.xml, app/src/main/res/layout/zim_manager.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml
Fixes #890 
Changes: 
- Overrode the setTheme in Base Activity.
- Defined new style StatusBar style for Base activity.
Screenshots/GIF for the change: 
**Before**
**After in day mode**
**After in night mode**
=> Fixes Title bar visibility issue

app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java
On clicking menu item icon new tab is open. #995
Changes: Open default new tab after closing all tab
Screenshot
=> On clicking menu item icon new tab is open. #995

app/src/main/java/org/kiwix/kiwixmobile/base/BaseActivity.java
Fixes #1037 
Changes: Added a null check
=> fix: NullPointerException on Fresh Application launch

app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java
Fixes #1135 
Changes: 
added a function call to setUpWebView() when Toolbar visibility is changed in onResume() of MainActivity
=> fix read aloud toolbar  issue

app/src/main/java/org/kiwix/kiwixmobile/utils/NetworkUtils.java, app/src/test/java/org/kiwix/kiwixmobile/utils/NetworkUtilsTest.java
Fixes #933
Changes: 
add checks for null and status 'connected'
This pull request replaces the first one #934 by providing a new clean feature branch based on the current upstream/master
=> improve network status check: respect null and 'connected' (new clean feature branch) #933

app/build.gradle, build.gradle.kts, gradle/wrapper/gradle-wrapper.properties, proguard.cfg
following the migration guide here:
https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/
this is based on PR #1177 - therefor it looks like more commits are in here ...
=> prepare switch to build.gradle.kts

.travis.yml, app/src/main/java/org/kiwix/kiwixmobile/error/ErrorActivity.java
Fixes #1224 
Changes: Use correct suffix, don't send a log that doesn't exist, print the full stacktrace
=> #1224 use correct fileProvider suffix

CONTRIBUTING.md
Minor fix to escape angle brackets
=> Escape angle brackets

app/build.gradle
Fixes #1229
Changes: BuildTypes deleted and leakcanary config altered to use standard resolutions
=> PR: #1229 BuildTypes removed

app/build.gradle, app/src/main/AndroidManifest.xml
Fixes #1219 
Changes: Update to build.gradle and AndroidManifest
=> #1219 support density splits

app/src/main/java/org/kiwix/kiwixmobile/di/modules/NetworkModule.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt
=> Increase timeout to 1 minute

.github/stale.yml
=> #1251 add config for prs

.travis.yml
=> Fix build with lower target emulator

app/build.gradle, app/src/main/java/org/kiwix/kiwixmobile/utils/files/FileSearch.kt, app/src/main/res/layout/item_book.xml
Required to fix CI on multiple PRs
=> Fix lint errors introduced in PRs merged before lint PR

app/src/main/java/org/kiwix/kiwixmobile/zim_manager/Fat32Checker.kt
Fixes #1262 
Changes: Add observeOn IO thread
=> #1262 anr fat32checker

.travis.yml
Fixes #1214 
Changes: fixes to commands after [this failure](https://travis-ci.org/kiwix/kiwix-android/builds/556238601)
=> #1214 Universal APK Upload fixes

.travis.yml
=> Chain deploy commands with && as Multinline is illegal syntax

.travis.yml
=> #1214 Change mode of ssh key

CONTRIBUTING.md, docs/commitstyle.md
=> Update commitstyle and contributing

app/src/main/java/org/kiwix/kiwixmobile/settings/KiwixSettingsActivity.java
=> #1297 Read VersionCode from Manifest

.travis.yml
=> Remove tools/platform tools

app/src/main/java/org/kiwix/kiwixmobile/utils/files/FileSearch.kt, app/src/test/java/org/kiwix/kiwixmobile/utils/files/FileSearchTest.kt
=> #1295 Make FileSearch recursive

.travis.yml
=> Stop jdk installation failure

app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java
Fixes #1235 
Changes: made the number of app-launches 10 from 5 before the 'rate us' dialogue launched.
=> changed rate-us dialog launch to 10 from original 5 per issue #1235

app/build.gradle, app/src/main/java/org/kiwix/kiwixmobile/data/ZimContentProvider.java
=> #1294 Landing page is not displayed on Wikimedia zims develop fix

app/src/main/java/org/kiwix/kiwixmobile/database/newdb/dao/NewBookDao.kt
=> Add only distinct zims to local database

app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java, app/src/main/java/org/kiwix/kiwixmobile/main/MainContract.java, app/src/main/java/org/kiwix/kiwixmobile/main/MainPresenter.java
=> Update Zim File queue on Home Screen on onResume

app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java
Fixes #960 - adds updated icon per suggestion in chat.
=> #960 updated external link warning popup icon to match others

app/src/main/res/menu/menu_main.xml
=> #1344 Reorder menu to make search visible again

app/src/main/res/layout/content_main.xml
=> Fix #1352 Download button is fixed to right even for RTL scripts

app/build.gradle
Fixes #1319 
Changes: Ignore SyntheticAccessor
=> #1319 Lint Issue: SyntheticAccessor

.idea/inspectionProfiles/kiwixAndroidInspections.xml
Fixes #1319 
Changes: Update inspection settings so IDE does not mark instances
=> #1319 update project inspection settings

app/src/main/java/org/kiwix/kiwixmobile/data/DataSource.java, app/src/main/java/org/kiwix/kiwixmobile/data/Repository.kt, app/src/main/java/org/kiwix/kiwixmobile/database/newdb/dao/NewBookmarksDao.kt, app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java, app/src/main/java/org/kiwix/kiwixmobile/main/MainContract.java, app/src/main/java/org/kiwix/kiwixmobile/main/MainPresenter.java
Fixes #1359 
Changes: Delete by url
=> #1359 Unable to remove Bookmark from bottom bar

.travis.yml
Travis denied permissions to use gradlew spontaneously
`19/home/travis/.travis/functions: line 104: ./gradlew: Permission denied`
=> Travis Build Fix

app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/bottom_toolbar.xml
=> #579 Bottom bar improvements

app/src/main/java/org/kiwix/kiwixmobile/database/newdb/dao/NewBookDao.kt
Fixes #1376 
Changes: Purge booksOnDisk from db when their file no longer exists
=> #1376 Unable to delete old zim files after re-install

CHANGELOG, app/build.gradle, app/src/main/java/org/kiwix/kiwixmobile/KiwixMobileActivity.java, app/src/main/java/org/kiwix/kiwixmobile/utils/files/FileUtils.java
=> 2.5.3 fixes

app/src/main/java/org/kiwix/kiwixmobile/main/AddNoteDialog.java
Fixes #1356 
Changes: Added check for extension-less article urls and 'null' articles (ones rendered erroneously without any content)
=> Hotfix for #1356

team-props/git-hooks/pre-commit.sh
=> Hotfix: Pre-commit hook failure message

app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java
Fixes #563 
Moves the variables to their only used function.
=> #563 moved play store variables to isolate them

app/build.gradle
=> Upgrade library

app/src/main/java/org/kiwix/kiwixmobile/history/HistoryActivity.java, app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java
Fixes #1031
Changes: When user clears history and presses back clear the history on webviews and open Home screen
=> #1031 Delete webview history when user clears History in HistoryActivity

app/build.gradle
=> Use Kiwix library 6.0.4

CHANGELOG, app/src/kiwix/play/release-notes/en-US/default.txt
=> #1458 Update changelog

app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java
Fixes #1464 
Changes: Use onBackPressed to close the navDrawer if it is open, not focusability(?)
=> #1464 Impossible to filter by author with Gutenberg

README.md
=> Few readme things

app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java
=> #1419 hide search icon when no zim is present

app/src/main/java/org/kiwix/kiwixmobile/settings/StorageCalculator.kt, app/src/test/java/org/kiwix/kiwixmobile/settings/StorageCalculatorTest.kt
Fixes #1473 
Changes: Check files exist, add tests
=> #1473 fix crash in storageCalculator

app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java
Fixes #1479 
Changes: add stop functionliaty
=> #1479 stop reading aloud

README.md, app/build.gradle
=> Upgrade kiwixlib in 3.0

app/src/main/assets/credits.html, app/src/main/assets/js/styleContent.js
=> Better credits

app/src/main/java/org/kiwix/kiwixmobile/webserver/ZimHostActivity.java
=> #1497 Move state restoration after objects instantiated

app/src/main/java/org/kiwix/kiwixmobile/data/ZimContentProvider.java, app/src/main/java/org/kiwix/kiwixmobile/main/KiwixWebViewClient.java
Fixes #121 
Fixes #1485  
Changes: check if source url was in document types in redirect and restrict redirects to content uris
=> #121 Open epub/pdf files

app/src/main/java/org/kiwix/kiwixmobile/database/newdb/dao/NewBookDao.kt, app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimFileReader.kt
=> #1502 Navigate to correct tab and fix double insertions

app/src/main/java/eu/mhutti1/utils/storage/StorageSelectDialog.kt
=> #1499 detect storage on IO thread

app/src/main/java/org/kiwix/kiwixmobile/utils/LanguageUtils.kt
=> #1514 Catch MissingResourceException

app/src/main/java/org/kiwix/kiwixmobile/di/modules/JNIModule.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimReaderContainer.kt
=> #1517 Make JniSearcher Nullable

app/src/main/res/layout/content_main.xml, app/src/main/res/layout/item_book.xml
=> #1523 Wrap content appropriately

app/build.gradle
=> Bump-up libkiwix to 8.1.0

app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java
=> #1528 Null check view

app/src/main/java/org/kiwix/kiwixmobile/utils/files/FileUtils.kt
=> #1520 Catch IllegalArgumentException

app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimFileReader.kt, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/StorageObserver.kt
=> #1519 JniKiwixException opening Zim file

app/src/main/java/org/kiwix/kiwixmobile/utils/files/FileUtils.kt
=> #1533 allow nullable return

CHANGELOG, app/build.gradle, app/src/kiwix/play/release-notes/en-US/default.txt
=> Release/3.0.4 to Develop

README.md
Changes: Fixed minor grammatical errors in Readme
=> Fixed minor grammatical errors

app/src/main/AndroidManifest.xml, app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/effects/OpenFile.kt, core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ActivityExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomMainActivity.kt
Fixes #1560 
Changes: Rework file opening
=> #1560 Opening a zim file results in a crash

core/src/main/java/org/kiwix/kiwixmobile/core/entity/MetaLinkNetworkEntity.java
Fixes #1566 
Changes: Make fields not required
=> #1566 Meta4 files missing hash/pieces

.github/PULL_REQUEST_TEMPLATE.md
This makes easier to fill the PR template and doesn't require the existing text to be deleted.
=> Update PR template to use comments.

core/src/main/AndroidManifest.xml
=> #1582 delete useless network change state permission from manifest.

.travis.yml, settings.gradle.kts
Test to see if builds from forks can pass
=> change key decrypting to after build

app/src/main/java/org/kiwix/kiwixmobile/language/adapter/LanguageListViewHolder.kt, core/src/main/res/values/strings.xml
=> #1606 Remove plurals translations

core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.java
=> 902 Fix some save media urls

custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomMainActivity.kt
Fixes #1620 
Stop file opening if activity is being recreated
=> #1620 "Read aloud" seems completly broken with `develop` branch

core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt
=> #1627 In night mode videos with div poster overlay are inverted

app/src/main/AndroidManifest.xml
=> #1634 App becomes unresponsive in the library - add permission back

core/src/main/java/org/kiwix/kiwixmobile/core/zim_manager/fileselect_view/adapter/BooksOnDiskViewHolder.kt
=> #1632 Categories/Tags in Download Books present with no tag data

team-props/git-hooks/pre-commit.sh
=> Make prominent warning about JDK8

.github/workflows/coverage.yml
=> #1693 Coverage Reports not uploading via Github Actions

core/src/main/java/org/kiwix/kiwixmobile/core/settings/CorePrefsFragment.java, core/src/main/java/org/kiwix/kiwixmobile/core/settings/SliderPreference.java
Fixes #1715 
Added missing condition in `SliderPrefernce.java`
=> Solves issue #1715 of zoom control

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java, core/src/main/java/org/kiwix/kiwixmobile/core/settings/CorePrefsFragment.java
Fixes #1707 
Restart MainActivity when Night Mode changes
=> #1707 A Problem with the Night Mode

core/src/main/java/org/kiwix/kiwixmobile/core/bookmark/BookmarksActivity.java, core/src/main/java/org/kiwix/kiwixmobile/core/history/HistoryActivity.java, core/src/main/res/layout/activity_bookmarks.xml, core/src/main/res/layout/activity_history.xml, core/src/main/res/menu/menu_bookmarks.xml, core/src/main/res/values/strings.xml, core/src/main/res/values/styles.xml, core/src/main/res/values/themes.xml
Fixes #1730 
Changed the UI of the bookmarks menu to match that of the history menu. Also added a clear all bookmarks feature.
=> #1730 Revamp the bookmarks section to be similar to the history section

core/src/main/java/org/kiwix/kiwixmobile/core/bookmark/BookmarksActivity.java, core/src/main/java/org/kiwix/kiwixmobile/core/history/HistoryActivity.java, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java, core/src/main/java/org/kiwix/kiwixmobile/core/utils/Constants.java
=> #1729 3.1.3 Crash Report: FileUriExposedException - don't use uris

app/src/androidTest/java/org/kiwix/kiwixmobile/intro/IntroActivityTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivityTest.kt
=> Ignore flaky tests

core/src/main/java/org/kiwix/kiwixmobile/core/zim_manager/TagsView.kt
=> #1766 Fix Tag Display Behaviour - correct inversion and add rule

core/src/main/res/layout/main_activity_content.xml
Fixes #709 
Progress bar color changed to `blue400` which increases visibility.
=>  Progress Bar (top of screen) made more visible.

core/src/main/java/org/kiwix/kiwixmobile/core/dao/NewRecentSearchDao.kt
Fixes #1850 
- Increase search history shown from 5 to 100.
=> #1850: Increase search history shown

app/src/main/java/org/kiwix/kiwixmobile/webserver/wifi_hotspot/HotspotService.java, core/src/main/res/values-ar/strings.xml, core/src/main/res/values-cs/strings.xml, core/src/main/res/values-es/strings.xml, core/src/main/res/values-fr/strings.xml, core/src/main/res/values-iw/strings.xml, core/src/main/res/values-ko/strings.xml, core/src/main/res/values-mk/strings.xml, core/src/main/res/values-pl/strings.xml, core/src/main/res/values-pt-rBR/strings.xml, core/src/main/res/values-sc/strings.xml, core/src/main/res/values-sv/strings.xml, core/src/main/res/values-tr/strings.xml, core/src/main/res/values-xmf/strings.xml, core/src/main/res/values-zh-rTW/strings.xml, core/src/main/res/values/strings.xml
Fixes #1847 
Added a toast when server is stopped. I also fixed a typo in another string resource.
=> Fix #1847 Show a toast when the server is stopped

.github/workflows/coverage.yml
=> Fix coverage report upload

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java
Fixes #1861 
As per the issue
**Case1:** No Animation should appear.
**Case2:** Open Home Page
=> Fixes #1861 Animation fix

core/src/main/java/org/kiwix/kiwixmobile/core/bookmark/BookmarksContract.kt
Fixes #1843 
Converted `BookmarksContract` to Kotlin
N/A
Signed-off-by: Saurav Tiwary <srv.twry@gmail.com>
=> Fixes #1843 Convert BookmarksContract to Kotlin

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java, core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.java, core/src/main/res/values/strings.xml
Fixes #1887 
Added notifications in the form of toast messages where ever "Surface to user" TODOs were present. 
Files changed: 
- KiwixTextToSpeech.java
- CoreMainActivity.java
=> Fix #1887 Notifications shown to user where ever needed

core/src/main/java/org/kiwix/kiwixmobile/core/help/HelpAdapter.java, core/src/main/java/org/kiwix/kiwixmobile/core/utils/AnimationUtils.java
Fixes #1855 
Added `description.setVisibility(View.GONE);` and 
`description.setVisibility(View.VISIBLE); `
It results into the same thing as expected.
=> Fixed animation

core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.java, core/src/main/res/menu/menu_add_note_dialog.xml, core/src/main/res/values/strings.xml
Fixes #1916 
Added an option to delete a note. 
=> Fix #1916 Add option to delete a note

core/src/main/java/org/kiwix/kiwixmobile/core/bookmark/BookmarksActivity.java
=> Alert Dialogue added while deleting selected Bookmarks

core/src/main/java/org/kiwix/kiwixmobile/core/bookmark/BookmarksActivity.java, core/src/main/java/org/kiwix/kiwixmobile/core/history/HistoryActivity.java
Fixes #1907 
Changed:
BookmarksActivity, HistoryActivity : made switch "View from all books" invisible in action mode.
=> Fixed bug in bookmark and history list.

core/src/main/java/org/kiwix/kiwixmobile/core/extensions/BookExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/BookUtils.kt
=> Fixes #1910 converted BookUtils to kotlin

core/src/main/java/org/kiwix/kiwixmobile/core/utils/KiwixDialog.kt, core/src/main/res/drawable-night/ic_warning.xml, core/src/main/res/drawable/ic_warning.xml, core/src/main/res/drawable/icon_question.xml, core/src/main/res/values/strings.xml
=> Text Improved and Icon added for Alert Dialogue in Bookmark & History

core/src/main/java/org/kiwix/kiwixmobile/core/downloader/ChunkUtils.java, core/src/main/java/org/kiwix/kiwixmobile/core/utils/StorageUtils.kt
=> Fix #1933 Converted StorageUtils to Kotlin

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java
Fixes #1966 
The home title gets updated when returning from a zim.
=> Fix #1966 Update home title when exiting a zim

app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/adapter/LibraryListItem.kt, core/src/main/java/org/kiwix/kiwixmobile/core/dao/FetchDownloadDao.kt, core/src/main/java/org/kiwix/kiwixmobile/core/dao/entities/BookOnDiskEntity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/dao/entities/FetchDownloadEntity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/downloader/model/DownloadItem.kt, core/src/main/java/org/kiwix/kiwixmobile/core/downloader/model/DownloadRequest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/entity/LibraryNetworkEntity.java
Fixes #1977
propogate nullability through models
=> #1977 Can't Download Item with no description 

app/src/main/java/org/kiwix/kiwixmobile/intro/IntroPresenter.kt
=> Fixed #1983 Converted IntroPreseter to Kotlin

app/src/main/res/layout/item_download.xml, app/src/main/res/layout/item_library.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/dimens.xml, buildSrc/src/main/kotlin/Libs.kt, buildSrc/src/main/kotlin/Versions.kt, core/build.gradle.kts, core/src/main/java/org/kiwix/kiwixmobile/core/main/TabsAdapter.java, core/src/main/res/layout/activity_kiwix_error.xml, core/src/main/res/layout/content_main.xml, core/src/main/res/layout/item_book.xml, core/src/main/res/layout/kiwix_search_widget.xml, core/src/main/res/values-night/color.xml, core/src/main/res/values/colors.xml, core/src/main/res/values/dimens.xml, core/src/main/res/values/styles.xml, core/src/main/res/values/themes.xml
Fixes #1974 
Background color changed for dark mode.
Text color changed.
The changes made increases contrast and better visuals are developed.
=> Fixes #1974 Better Colors Used

core/src/main/java/org/kiwix/kiwixmobile/core/di/modules/JNIModule.kt
=> Fixed #1991 Convert JNIModule to Kotlin

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Versions.kt
=> Upgrade kotlin version

core/src/main/java/org/kiwix/kiwixmobile/core/dao/NewRecentSearchDao.kt, core/src/sharedTestFunctions/java/org/kiwix/sharedFunctions/TestModelFunctions.kt, core/src/test/java/org/kiwix/kiwixmobile/core/dao/NewRecentSearchDaoTest.kt
=> #1865 Add unit tests for NewRecentSearchDao 

buildSrc/src/main/kotlin/Versions.kt
=> #2014 Upgrade kiwixlib - bump version

core/src/main/java/org/kiwix/kiwixmobile/core/bookmark/BookmarksAdapter.java, core/src/main/java/org/kiwix/kiwixmobile/core/bookmark/BookmarksPresenter.java
=> Fix lint warnings in bookmark package

buildSrc/src/main/kotlin/Versions.kt
=> bump GPP version

core/src/main/java/org/kiwix/kiwixmobile/core/main/MainPresenter.kt
Fixes #2034 
- safeguard against NPE
=> #2034 Crash after building from source

core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt
Fixes #2038 
- catch exception and return default value
=> #2038 Crash Report 3.3.0: ZimFileReader.mimeTypeFromReader (ZimFileReader.java:132)

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.java, core/src/main/java/org/kiwix/kiwixmobile/core/main/NightModeViewPainter.kt
Fixes #2037 
- make NPE impossible
=> #2037 Crash Report 3.3.0: NPE NightModeViewPainter.deactivateNightMode (NightModeViewPainter.java:55)

core/src/main/java/org/kiwix/kiwixmobile/core/dao/NewBookDao.kt, core/src/sharedTestFunctions/java/org/kiwix/sharedFunctions/TestModelFunctions.kt, core/src/test/java/org/kiwix/kiwixmobile/core/dao/NewBookDaoTest.kt
=> #1864 Add unit tests for NewBookDao 

app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/adapter/LibraryListItem.kt, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/adapter/LibraryViewHolder.kt, app/src/test/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModelTest.kt
=> #2024 Two strings are not localized correctly 

core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt
Fixes #2032 
- load svgs as assets
=> #2032 some Latex based formulas not shown on Kiwix Android APK 3.3.0/3.2.1 

core/src/main/java/org/kiwix/kiwixmobile/core/history/HistoryDateHeaderItemViewHolder.kt
Fixes #2049 
- catch exception
=> #2049 Crash Report 3.3.0: DateTimeParseException 

app/src/androidTest/java/org/kiwix/kiwixmobile/intro/IntroRobot.kt, app/src/main/res/layout/item_intro_1.xml, core/src/main/res/values-ar/strings.xml, core/src/main/res/values-ast/strings.xml, core/src/main/res/values-cs/strings.xml, core/src/main/res/values-diq/strings.xml, core/src/main/res/values-eo/strings.xml, core/src/main/res/values-es/strings.xml, core/src/main/res/values-fi/strings.xml, core/src/main/res/values-fr/strings.xml, core/src/main/res/values-in/strings.xml, core/src/main/res/values-iw/strings.xml, core/src/main/res/values-ko/strings.xml, core/src/main/res/values-mk/strings.xml, core/src/main/res/values-pl/strings.xml, core/src/main/res/values-pt-rBR/strings.xml, core/src/main/res/values-sc/strings.xml, core/src/main/res/values-sl/strings.xml, core/src/main/res/values-sv/strings.xml, core/src/main/res/values-tr/strings.xml, core/src/main/res/values-zh-rTW/strings.xml, core/src/main/res/values/strings.xml
=> 'humankind' in place of 'human kind'

core/src/main/java/org/kiwix/kiwixmobile/core/history/HistoryActivity.java, core/src/main/java/org/kiwix/kiwixmobile/core/history/HistoryContract.kt
=> Fixes #2063 Convert HistoryContract to Kotlin

app/src/main/res/layout/item_intro_1.xml, core/src/main/res/layout/content_main.xml, core/src/main/res/values-ar/strings.xml, core/src/main/res/values-ast/strings.xml, core/src/main/res/values-br/strings.xml, core/src/main/res/values-ckb/strings.xml, core/src/main/res/values-cs/strings.xml, core/src/main/res/values-diq/strings.xml, core/src/main/res/values-eo/strings.xml, core/src/main/res/values-es/strings.xml, core/src/main/res/values-fa/strings.xml, core/src/main/res/values-fi/strings.xml, core/src/main/res/values-fr/strings.xml, core/src/main/res/values-iw/strings.xml, core/src/main/res/values-ko/strings.xml, core/src/main/res/values-lb/strings.xml, core/src/main/res/values-mk/strings.xml, core/src/main/res/values-ml/strings.xml, core/src/main/res/values-pl/strings.xml, core/src/main/res/values-pt-rBR/strings.xml, core/src/main/res/values-sc/strings.xml, core/src/main/res/values-sl/strings.xml, core/src/main/res/values-sv/strings.xml, core/src/main/res/values-tr/strings.xml, core/src/main/res/values-zh-rTW/strings.xml, core/src/main/res/values/strings.xml
=> Remove confusing image description

app/src/main/java/org/kiwix/kiwixmobile/intro/IntroContract.kt
=> Refactor : IntroContract to Kotlin

core/src/main/java/org/kiwix/kiwixmobile/core/history/HistoryModule.kt, core/src/main/java/org/kiwix/kiwixmobile/core/history/HistoryPresenter.kt
=> Fixes #2081 Convert HistorModule to Kotlin

app/src/main/java/org/kiwix/kiwixmobile/di/modules/KiwixModule.kt, app/src/main/java/org/kiwix/kiwixmobile/webserver/ZimHostActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/ConnectivityReporter.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/KiwixDialog.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/WifiManagerUtils.kt, core/src/main/res/values/strings.xml
Fixes #1841 
Changes made to the start server workflow:
- Wifi on: A dialog is shown 
- Hotspot on: Server started directly
- None on: A dialog is shown
**Screenshots:**
-  None on:
- WiFi on:
- Hotspot on:
=> Fix #1841 Enhance workflow of the host books section

core/src/main/res/values-ar/strings.xml, core/src/main/res/values-ast/strings.xml, core/src/main/res/values-bg/strings.xml, core/src/main/res/values-ca/strings.xml, core/src/main/res/values-ckb/strings.xml, core/src/main/res/values-cs/strings.xml, core/src/main/res/values-da/strings.xml, core/src/main/res/values-diq/strings.xml, core/src/main/res/values-eo/strings.xml, core/src/main/res/values-es/strings.xml, core/src/main/res/values-eu/strings.xml, core/src/main/res/values-fi/strings.xml, core/src/main/res/values-fr/strings.xml, core/src/main/res/values-it/strings.xml, core/src/main/res/values-iw/strings.xml, core/src/main/res/values-ko/strings.xml, core/src/main/res/values-lb/strings.xml, core/src/main/res/values-mk/strings.xml, core/src/main/res/values-ml/strings.xml, core/src/main/res/values-pl/strings.xml, core/src/main/res/values-pt-rBR/strings.xml, core/src/main/res/values-pt/strings.xml, core/src/main/res/values-qq/strings.xml, core/src/main/res/values-ru/strings.xml, core/src/main/res/values-sc/strings.xml, core/src/main/res/values-sv/strings.xml, core/src/main/res/values-tr/strings.xml, core/src/main/res/values-xmf/strings.xml, core/src/main/res/values-zh-rTW/strings.xml, core/src/main/res/values-zh/strings.xml
=> Localisation updates from https://translatewiki.net.

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Versions.kt
=> #2130 Upgrade Kotlin to 1.3.72 

core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimReaderContainer.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchResultGenerator.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModel.kt, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModelTest.kt, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/ZimSearchResultGeneratorTest.kt
Fixes #26
- debounce and search with a copy of the fileReader
=> #26 Search problem - some results disappear as typing advances 

core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.java
Fixes #2106 
- prevent contains from throwing ClassNotFoundException
=> #2106 Crash Report 3.3.1: java.lang.ClassNotFoundException ErrorActivity.onCreate 

.github/workflows/coverage.yml, .github/workflows/nightly.yml, buildSrc/src/main/kotlin/plugin/AllProjectConfigurer.kt
=> #2149 Fix NDK version 

core/src/main/java/org/kiwix/kiwixmobile/core/StorageObserver.kt, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimReaderContainer.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchResultGenerator.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.java, core/src/test/java/org/kiwix/kiwixmobile/core/StorageObserverTest.kt, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/ZimSearchResultGeneratorTest.kt
Fixes #2175 
- make file detection and searching dispose
- remove fulltext search
=> #2175 ZimFileReaders not being disposed 

core/detekt_baseline.xml, core/src/main/java/org/kiwix/kiwixmobile/core/downloader/fetch/FetchDownloadNotificationManager.kt
Fixes #2157 
- remove pause button in notification
=> #2157 Cannot resume download after pausing 

.github/workflows/coverage.yml, .github/workflows/nightly.yml
Fixes #2139 
- remove emulator 29
=> #2139 KiwixSettingsActivity.testStorageDialog failing consistently on  API 29 emulator

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java
Fixes #2204 
- convert to primitive
=> #2204 Crash Report 3.3.3: CoreReaderFragment.toggleBookmark 

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java
Fixes #2203 
- use activity_main_root
=> #2203 Fullscreen Video does not display 

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreWebViewClient.java
Fixes #2126 
- load url again when # is present
=> #2126 Hash ignored when linking to other article 

core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt
Fixes #2202 
- fix redirects for urls containing "?"
=> #2202 Can't open videos 

core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.java
Fixes #2217 
- read data from kiwixlib explicitly
=> #2217 "Save media" seems broken

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Versions.kt
=> #2220 Update AGP to 4.0.1 

CONTRIBUTING.md
=> #2215 updated to correct links in contributing.md

core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModel.kt
Linked issue #2082 
- cancel previously active task
=> #2082 Very slow search function 

buildSrc/src/main/kotlin/Libs.kt, buildSrc/src/main/kotlin/Versions.kt, core/build.gradle.kts, core/src/main/java/org/kiwix/kiwixmobile/core/CoreApp.kt, core/src/main/java/org/kiwix/kiwixmobile/core/ServiceWorkerInitialiser.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreWebViewClient.java, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt
Fixes #2222 
- support service workers 
- load war2c as asset
=> #2222 Impossible to read warc2zim generated ZIM files 

app/src/main/java/org/kiwix/kiwixmobile/di/modules/KiwixModule.kt, buildSrc/src/main/kotlin/Versions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/di/modules/ActivityModule.kt, core/src/main/java/org/kiwix/kiwixmobile/core/di/modules/DownloaderModule.kt
Fixes #2267 
- bump versions 
- dagger lint fixes
=> #2267 Increase Library versions

core/src/main/res/drawable-night/ic_open_in_new_24dp.xml, core/src/main/res/drawable/ic_open_in_new_24dp.xml, gradle/wrapper/gradle-wrapper.properties
Fixes #2266
Added drawable resource for night mode
[Click here](https://ibb.co/9gwjRrP)
=> Open in new tab when searching has bad contrast in dark mode 

core/src/main/java/org/kiwix/kiwixmobile/core/main/FileReader.kt
Fixes #2306 
Parent issue  #1826 
* Converted FileReader to Kotlin
=> Convert FileReader.java file to kotlin #2306

app/src/main/res/layout/activity_zim_host.xml
Fixes #2349 
**Changes**
Changed button background to backgroundTint.
=> fixed #2349 color overiden in zim host activity

app/src/main/java/org/kiwix/kiwixmobile/settings/KiwixPrefsFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/LibraryFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/settings/CorePrefsFragment.java, core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.java
Fixes #2256 
- don't depend on isEmulated
=> #2256 External device mgmt is not robust and gives contradictory information 

app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/adapter/LibraryViewHolder.kt, app/src/main/res/layout/item_library.xml, core/src/main/res/values/styles.xml
Fixes #2300 
- remove bottom 2 lines
- divide spaces with chains
=> #2300 Missing wrap in library

app/detekt_baseline.xml, app/src/main/java/org/kiwix/kiwixmobile/di/modules/KiwixModule.kt, app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/MountFileSystemChecker.kt, app/src/main/res/layout/activity_kiwix_main.xml, core/detekt_baseline.xml, core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java, core/src/main/java/org/kiwix/kiwixmobile/core/main/NavigationHostFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/zim_manager/MountPointProducer.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomMainActivity.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt, custom/src/main/res/layout/activity_custom_main.xml
Fixes #2375 
- move common functionality down
- use same NavHostFragment
- align packages in core
=> #2375 Fix Back Navigation in custom apps 

core/src/main/res/layout/reader_fragment_content.xml
=> #2411 fixed scrolling toolbar

app/src/main/java/org/kiwix/kiwixmobile/help/KiwixHelpFragment.kt, app/src/main/res/navigation/kiwix_nav_graph.xml, core/src/main/java/org/kiwix/kiwixmobile/core/help/HelpFragment.kt, core/src/main/res/values/arrays.xml, core/src/main/res/values/strings.xml, custom/src/main/java/org/kiwix/kiwixmobile/custom/help/CustomHelpFragment.kt, custom/src/main/res/navigation/custom_nav_graph.xml
Fixes #2223 
- add new section for non custom only
=> #2223 Added "How to update zim files?" to Kiwix, Wikipedia offline app

core/src/main/java/org/kiwix/kiwixmobile/core/ServiceWorkerInitialiser.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreWebViewClient.java, core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimReaderContainer.kt
Reverts kiwix/kiwix-android#2406
=> Revert "Feature/macgills/2347 range headers"

core/src/main/java/org/kiwix/kiwixmobile/core/CoreApp.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreWebViewClient.java, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt
=> #2303 remove support for service workers

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java, core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/WebViewCallback.java
=> Feature/gouri-panda/2407 Navigation view not hidden for full screen video

app/src/androidTest/java/org/kiwix/kiwixmobile/KiwixMockServer.kt, buildSrc/src/main/kotlin/Versions.kt
Fixes #2107 
- bump fetch version
=>  #2107 Crash Report 3.3.1: java.lang.IllegalStateException FetchCoreUtils.getFileTempDir

core/src/main/java/eu/mhutti1/utils/storage/StorageSelectDialog.kt, core/src/main/java/eu/mhutti1/utils/storage/adapter/StorageDelegate.kt, core/src/main/java/eu/mhutti1/utils/storage/adapter/StorageViewHolder.kt, core/src/main/res/layout/device_item.xml
Fixes #2257 
Added radio buttons in the recyclerView
I'll add the visuals once the implementation gets reactive, currently it doesn't work as expected
=> style: Added RadioButtons in storageSelectDialog

core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt
Close #2258 
* Appended the mail body and device configs to the logs file. 
* [Here](https://docs.google.com/document/d/186nqZb2TR55_DD_sOJzt8Yr9Ts7VwUE4SruJN96oI4g/edit?usp=sharing) is the current logs file.
NA
=> fix: Appended Device Details in the logs file as well

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java
=> fix: Set the tts working in background as well

app/src/main/AndroidManifest.xml, app/src/main/java/org/kiwix/kiwixmobile/localFileTransfer/LocalFileTransferFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/webserver/ZimHostFragment.kt, buildSrc/src/main/kotlin/Config.kt, core/src/main/AndroidManifest.xml, core/src/main/java/org/kiwix/kiwixmobile/core/main/FileReader.kt, core/src/test/java/org/kiwix/kiwixmobile/core/entity/MetaLinkNetworkEntityTest.kt, core/src/test/java/org/kiwix/kiwixmobile/core/utils/files/FileSearchTest.kt
Fixes #2310 
- target 29
- use Fine location permission for local file transfer
- clean up local file transfer
=> #2310 Target Android 29 before November 

DESIGN.md
Fixes #2466
Changed "simplifiy" to "simplify"
=> #2466 Fixed typo in DESIGN.md

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt
=> #2463 Progress Bar Fixed in VideoView

app/src/main/java/org/kiwix/kiwixmobile/help/KiwixHelpFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/help/HelpFragment.kt
Fixes #2472 
- only show items in main app
=> #2472 FAQ entries not relevant for custom apps should be removed/blind

core/src/main/java/org/kiwix/kiwixmobile/core/page/PageFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/bookmark/BookmarksFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/history/HistoryFragment.kt
=> #2475 History and Bookmark fragments are not showing their title

.github/workflows/coverage.yml, .github/workflows/nightly.yml, .github/workflows/release.yml
=> CI: Removed Deprecated command from GH workflows

.github/workflows/pull_request.yml
Close #2484 
Wrote a job to upload APK on GH actions and to the usual apk path in the project.
NA
=> CI: Uploads build APKs as artifacts at GH-Actions

.github/workflows/nightly.yml
=> CI: Updated runner version used in Nightly Runs

.github/workflows/coverage.yml, .github/workflows/pull_request.yml
Fixes #2486 
Added concerned jobs and steps wherever needed
NA
=> CI: Upload Reports to github actions

core/src/main/java/org/kiwix/kiwixmobile/core/settings/CoreSettingsFragment.kt
=> FIX: 2469 KiwixPrefsFragment is leaking

app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomMainActivity.kt
=> #2497 Removed empty/white sidebar

buildSrc/src/main/kotlin/Versions.kt
libzim is a lot faster in this version
=> Bump-up libkiwix to version 9.4.1

buildSrc/src/main/kotlin/Libs.kt, buildSrc/src/main/kotlin/Versions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/settings/CoreSettingsFragment.kt, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/ProcessActivityResultTest.kt
Fixes #2299 
As per comment on the ticket I am hijacking the ticket for a general upgrade
- bump library versions
=> #2299 Upgrade to Kotlin 1.4.0 

app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt, core/src/main/java/org/kiwix/kiwixmobile/core/di/modules/NetworkModule.kt, core/src/main/java/org/kiwix/kiwixmobile/core/entity/LibraryNetworkEntity.java
Fixes #2385 
- make serialiser strict
=> #2385 Online Library is just loading and loading 

app/detekt_baseline.xml, app/src/androidTest/java/org/kiwix/kiwixmobile/main/TopLevelDestinationTest.kt, app/src/main/java/org/kiwix/kiwixmobile/intro/IntroFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/fileselect_view/effects/DeleteFiles.kt, app/src/main/res/navigation/kiwix_nav_graph.xml, app/src/test/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModelTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt
Fixes #2520 
- use livedata to control display of dialog
- reorder methods in LibraryFragments to follow lifecycle
- simplified navigation from intro
=> #2520 Kiwix uses mobile data without asking 

app/src/main/res/layout/fragment_destination_download.xml, app/src/main/res/layout/fragment_destination_library.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/styles.xml, core/src/main/res/layout/fragment_reader.xml, core/src/main/res/layout/fragment_search.xml, core/src/main/res/values/dimens.xml, core/src/main/res/values/styles.xml
Fixes #2515 
Fixed UI for all messages displayed.
Typography is same and the position of message is also same.
<p>
</p>
=> Redesign: Fixed UI for messages displayed

app/src/main/java/org/kiwix/kiwixmobile/intro/IntroFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt, app/src/main/res/navigation/kiwix_nav_graph.xml
Fixes #2530 
- use pops to make intro the only destination on the stack
=> #2530 Remove activity finishing from IntroFragment and rely on default behaviour

core/src/main/res/values-qq/strings.xml, core/src/main/res/values/strings.xml, core/src/main/res/xml/preferences.xml
Close #2535 
Removed hardcoding and added needed strings in concerned files
NA
=> fix: Removed hardcoded strings from prefs screen

core/src/main/java/org/kiwix/kiwixmobile/core/page/PageFragment.kt
=> fix: Handled navigate up from toolbar in bookmarks and history screens

core/src/main/java/org/kiwix/kiwixmobile/core/ServiceWorkerInitialiser.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreWebViewClient.java, core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimReaderContainer.kt
Fixes #2532 
- readd range headers
=> #2532 Video seeking does not work anymore with 3.4.2 

app/src/main/assets/credits.html, custom/src/main/assets/credits.html
=> Updated contributors list

CHANGELOG, app/build.gradle.kts
To be merged after release branch is merged to master
=> Release/3.4.3 to Develop

core/src/main/java/org/kiwix/kiwixmobile/core/main/CompatFindActionModeCallback.kt
=> Memory leak fixed in KiwixReaderFragment

.github/workflows/coverage.yml, .github/workflows/nightly.yml, buildSrc/src/main/kotlin/plugin/AllProjectConfigurer.kt
=> Bump-up NDK version to 22.0.7026061

.github/workflows/nightly.yml
Fixes #2585 
Eliminated dependence from pre-existing ndk version runners and install 'em in runtime
NA
=> CI: fixed Nightly test & release Job

.github/workflows/coverage.yml, .github/workflows/nightly.yml
=> fix: Coverage reporting failure

app/src/androidTest/java/org/kiwix/kiwixmobile/help/HelpFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/help/HelpRobot.kt
=> test: Completed the HelpFragmentTest

core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt
Fixes #2174 
Mime-type wasn't being parsed correctly, it now works fine(as expected).
|Now| Previously| 
|---|--|
|![boqqq](https://user-images.githubusercontent.com/56556919/110164914-1285b700-7e18-11eb-8d19-b63f39a42c62.jpeg)|![ols](https://user-images.githubusercontent.com/56556919/110164972-27fae100-7e18-11eb-9c04-21e6cf27d094.jpg)|
=> fix: Issue opening Bouquineux

app/src/androidTest/java/org/kiwix/kiwixmobile/main/TopLevelDestinationRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/webserver/ZimHostRobot.kt, app/src/main/java/org/kiwix/kiwixmobile/webserver/ZimHostFragment.kt, core/src/main/res/menu/menu_drawer_main.xml, core/src/main/res/values-ar/strings.xml, core/src/main/res/values-ckb/strings.xml, core/src/main/res/values-cs/strings.xml, core/src/main/res/values-diq/strings.xml, core/src/main/res/values-fa/strings.xml, core/src/main/res/values-fi/strings.xml, core/src/main/res/values-fr/strings.xml, core/src/main/res/values-iw/strings.xml, core/src/main/res/values-ko/strings.xml, core/src/main/res/values-ku/strings.xml, core/src/main/res/values-mk/strings.xml, core/src/main/res/values-pl/strings.xml, core/src/main/res/values-pt-rBR/strings.xml, core/src/main/res/values-qq/strings.xml, core/src/main/res/values-ro/strings.xml, core/src/main/res/values-ru/strings.xml, core/src/main/res/values-sc/strings.xml, core/src/main/res/values-sv/strings.xml, core/src/main/res/values-tr/strings.xml, core/src/main/res/values-uk/strings.xml, core/src/main/res/values-zh-rTW/strings.xml, core/src/main/res/values-zh/strings.xml, core/src/main/res/values/strings.xml
=> fix: #1554 Minute Refactor from `Host Books` to `WiFi Hotspot`

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java, core/src/main/java/org/kiwix/kiwixmobile/core/search/SearchFragment.kt
=> #2607 search menu items recreates multiple times

app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ConnectivityBroadcastReceiver.kt, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt
=> Fixed ZimManageViewModel Leaking

.github/workflows/nightly.yml, custom/.gitignore
=> fix nightly Builds

.github/workflows/coverage.yml, .github/workflows/nightly.yml, .github/workflows/pull_request.yml, .github/workflows/release.yml, buildSrc/src/main/kotlin/plugin/AllProjectConfigurer.kt
See more info at https://github.com/kiwix/kiwix-android-custom/issues/64
=> Update to LTS NDK version

core/src/test/java/org/kiwix/kiwixmobile/core/dao/HistoryDaoTest.kt
=> Add unit tests for HistoryDao.kt

core/src/main/java/org/kiwix/kiwixmobile/core/search/SearchFragment.kt
=> #2657 Input methods were broken

build.gradle.kts, buildSrc/src/main/kotlin/Versions.kt, buildSrc/src/main/kotlin/plugin/AllProjectConfigurer.kt, jacoco.gradle
Fixes #2667 
Description:-
Due to some reason `JacocoPluginExtension` didn't find the 0.7.9 version.
Added  `mavenCentral()`
=> #2667_ci_issue

core/src/test/java/org/kiwix/kiwixmobile/core/dao/NewBookmarksDaoTest.kt
=> Add unit tests for NewBookmarksDao.kt

app/detekt_baseline.xml, app/src/main/java/org/kiwix/kiwixmobile/webserver/ZimHostFragment.kt, app/src/main/res/drawable/ic_share_35dp.xml, app/src/main/res/layout/activity_zim_host.xml, core/src/main/res/values/strings.xml
Fixes #1542 
* Adds a new icon to share the socket address via different applications
* Makes the url _spottable_ and clickable
https://user-images.githubusercontent.com/56556919/126885025-f9ea72e2-5696-462e-a3d9-6dfd560963df.mp4
=> Fix #1542 : Makes socket address user friendly

core/src/test/java/org/kiwix/kiwixmobile/core/dao/NewLanguagesDaoTest.kt
=> Add unit tests for NewLanguagesDao.kt

.github/workflows/release.yml
Fixes #2706 hopefully
Changes:
Added specific env variable for production releases on download. kiwix.org
=> Production releases fails on download.kiwix.org

custom/src/main/java/org/kiwix/kiwixmobile/custom/settings/CustomPrefsFragment.kt
=> Download over wifi shows on custom app

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FragmentExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/PageFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/SimpleRecyclerViewScrollListener.kt
Fixes #2717
https://user-images.githubusercontent.com/75211982/137470182-efae0cbd-4e29-42df-bff1-d60632b8363f.mp4
=> #2717 Hide Keyboard when Scrolling in OnlineLibraryFragment/PagerFragment

README.md
=> #2636 Added Nightly Status Badge in Readme

app/src/main/java/org/kiwix/kiwixmobile/language/LanguageFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/extensions/FragmentExtensions.kt
=> fixes#2756 close keyboard when clicked on menu buttons of download screen and choose language

core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt
Fixes #2797
I have changed the method for retrieving data directory for android 10 or above.
=> #2797 fixing the note not saving issue.

app/src/androidTest/java/org/kiwix/kiwixmobile/BaseRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/intro/IntroRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/settings/KiwixSettingsFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/utils/StandardActions.java, app/src/main/res/layout/activity_kiwix_main.xml
Fixes #2741 
Sometimes For some reason, our test robot couldn't find the views we want to see.
=> Pass test for Android 21 in IntroFragment

app/src/androidTest/java/org/kiwix/kiwixmobile/mimetype/MimeTypeTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimReaderContainer.kt, core/src/sharedTestFunctions/java/org/kiwix/kiwixmobile/core/reader/ZimFileReaderTest.kt
Fixes #2793
Fixes #2813
Checkif mime on android end and server end is different then select server end mime type and render the page.
=> Fixing .js ending articles broken rendering

CHANGELOG, app/build.gradle.kts
=> release version 3.5.0 and change log update

app/build.gradle.kts, app/src/main/java/org/kiwix/kiwixmobile/intro/CustomPageIndicator.kt, app/src/main/res/layout/fragment_intro.xml, app/src/main/res/values/attrs_page_indicator.xml, buildSrc/src/main/kotlin/Libs.kt, buildSrc/src/main/kotlin/Versions.kt, buildSrc/src/main/kotlin/plugin/AllProjectConfigurer.kt
=> library code migrated to our project

CHANGELOG
Just updating the small change log for latest fix.
=> change log update

.github/workflows/release.yml, README.md
Moving playstore publishing job after download.kiwix.org .
=> Moving playstore publishing job after download.kiwix.org .

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, app/src/main/res/layout/fragment_destination_download.xml, core/src/main/res/values/strings.xml, core/src/main/res/values/styles.xml
=> Added internet permission message

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreWebViewClient.java, core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt, core/src/test/java/org/kiwix/kiwixmobile/core/utils/files/FileUtilsTest.kt
Fixes #2709
Fixes #2788
Fixes #2684
Fixes #2518
Fixes #2517
Fixing pdf downloading and rendering issue
=> PDF downloading fixes

.github/workflows/release.yml
=> fixing CI/CD github failure

core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt
=> Fix same picture and pdf saved multiple times

.github/workflows/release.yml, app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/org/kiwix/kiwixmobile/localFileTransfer/LocalFileTransferFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreWebViewClient.java, core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt, core/src/main/java/org/kiwix/kiwixmobile/core/settings/CorePrefsFragment.java, core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt, core/src/main/res/values/strings.xml, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt
=> Playstore compilation flag

app/src/main/java/org/kiwix/kiwixmobile/localFileTransfer/SenderHandShake.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/Fat32Checker.kt, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/FileWritingFileSystemChecker.kt, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageViewModel.kt, app/src/main/java/org/kiwix/kiwixmobile/zim_manager/library_view/adapter/LibraryViewHolder.kt, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Versions.kt, buildSrc/src/main/kotlin/plugin/AllProjectConfigurer.kt, buildSrc/src/main/kotlin/plugin/KiwixConfigurationPlugin.kt, core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/NavigationHostFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/AnimationUtils.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt, lintConfig.xml
=> Upgrade to kotlin 1.7.0

core/src/main/java/org/kiwix/kiwixmobile/core/di/qualifiers/Computation.kt
=> #1826 converted Computation.java to kotlin

.github/workflows/release.yml, app/build.gradle.kts
ref: https://github.com/kiwix/kiwix-android/issues/1682#issuecomment-1178822759
=> Fix VERSION_INFO formatting

core/src/main/java/org/kiwix/kiwixmobile/core/search/SearchFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/OpenSearchItem.kt, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/OpenSearchItemTest.kt
=> Fix Back button after opening a search result closes the app

app/src/main/java/org/kiwix/kiwixmobile/settings/KiwixPrefsFragment.kt
=> Hide manage external storage permission from settings in play store build

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java
=> Fix CoreReaderFragment.webViewFailedLoading crash

buildSrc/src/main/kotlin/Libs.kt, buildSrc/src/main/kotlin/Versions.kt, buildSrc/src/main/kotlin/plugin/AllProjectConfigurer.kt, core/src/main/java/org/kiwix/kiwixmobile/core/CoreApp.kt, core/src/main/res/values/strings.xml
=> Fix missing architecture in object box

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java
=> #2606 navigation fixes while pressing back button

core/src/main/res/values/strings.xml
=> Fixes Literal `n` in a message

core/src/main/res/values/strings.xml
And thanks a lot for fixing #2919!
=> Remove unnecessary space from a message

.github/workflows/coverage.yml, app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/testutils/TestUtils.java, core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ActivityExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchViewModel.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/OpenSearchItem.kt, core/src/test/java/org/kiwix/kiwixmobile/core/search/viewmodel/effects/OpenSearchItemTest.kt, lintConfig.xml
=> Search fix

core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt
=> Search screen not popup after pressing back from search result

.github/workflows/nightly.yml
=> Added nightly to F-Droid

app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.java
=> Search widget issue fix

app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchRobot.kt
=> SearchFragmentTest often failed at lower android version on nightly build

CHANGELOG
=> Update change log for release

.github/workflows/nightly.yml
=> Revert nightly F-Droid

.github/workflows/nightly.yml
=> Upgrading Runner And Checkout for Nightly

.github/workflows/nightly.yml
=> disable animation

.github/workflows/release.yml
adding insight to get more logs why publishing  to playstore failing.
=> adding scanning to get more insight on failure

buildSrc/src/main/kotlin/Libs.kt, buildSrc/src/main/kotlin/Versions.kt, buildSrc/src/main/kotlin/plugin/AllProjectConfigurer.kt, core/src/main/java/org/kiwix/kiwixmobile/core/CoreApp.kt, core/src/main/res/values-fr/strings.xml, core/src/main/res/values-mk/strings.xml, core/src/main/res/values-sk/strings.xml, core/src/main/res/values/strings.xml
=> Remove Google Play Core Services

.github/workflows/nightly.yml, .github/workflows/release.yml, buildSrc/src/main/kotlin/Libs.kt, buildSrc/src/main/kotlin/Versions.kt, buildSrc/src/main/kotlin/plugin/AllProjectConfigurer.kt, core/src/main/java/org/kiwix/kiwixmobile/core/CoreApp.kt, core/src/main/res/values-fr/strings.xml, core/src/main/res/values-mk/strings.xml, core/src/main/res/values-sk/strings.xml, core/src/main/res/values/strings.xml
Merging develop to master to support Fdroid build.
=> Merging changes to master.

build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Libs.kt, buildSrc/src/main/kotlin/Versions.kt, buildSrc/src/main/kotlin/plugin/AllProjectConfigurer.kt, core/build.gradle.kts, core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt
=> Removed JCenter From Project and Update KiwixLib

gradle.properties
=> Added kotlin code conventional style to 1.7

.github/workflows/coverage.yml, .github/workflows/nightly.yml, .github/workflows/pull_request.yml
=> Refactored CI

.github/workflows/pull_request.yml
=> Fixes Pull Request workflow's CI jobs 

core/src/main/java/org/kiwix/kiwixmobile/core/data/DataModule.kt
Fixes: #2982
Converted DataModule.java file into Kotlin
=> Convert DataModule.java to kotlin

.github/workflows/nightly.yml
=> Reverted to ubuntu for unit tests in nightly workflow

app/src/main/res/layout/fragment_destination_download.xml
=> Scrollbar Indicator Added

app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteRobot.kt
=> Added `NoteFragment` UI Test

.codecov.yml
=> #2883 Added codecov configuration

core/src/main/AndroidManifest.xml
=> Fixes Instrumentation test exported problem

app/detekt_baseline.xml, app/src/main/java/org/kiwix/kiwixmobile/webserver/wifi_hotspot/IpAddressCallbacks.kt
Fixes: #3027 
Converted IpAddressCallbacks.java into kotlin
=> Convert IpAddressCallbacks.java into kotlin

core/src/main/java/org/kiwix/kiwixmobile/core/di/qualifiers/MainThread.kt
Fixes: #3012 
Converted MainThread.java to kotlin
=> Convert MainThread.java to kotlin

core/src/main/java/org/kiwix/kiwixmobile/core/di/qualifiers/IO.kt
Fixes: #3011 
Converted IO.java to kotlin
=> Convert IO.java to kotlin

.github/workflows/coverage.yml, .github/workflows/nightly.yml, app/src/androidTest/java/org/kiwix/kiwixmobile/help/HelpRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/main/TopLevelDestinationTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/library/LibraryRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/bookmarks/BookmarksRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/history/HistoryRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/settings/SettingsRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/webserver/ZimHostRobot.kt, jacoco.gradle
Fixes #2928 
**This PR Changes**
* Added macOS version 11 in coverage and nightly
* Added Pixel 2 in Profile 
* Added Google API 21 & 30
* Refactor the tests that are most likely to fail in CI sometimes
=> Refactored CI and Tests

core/src/main/java/org/kiwix/kiwixmobile/core/data/local/entity/LibraryDataSource.kt
Fixes: #3001 
Converted LibraryDataSource.java into kotlin
=> Convert LibraryDataSource.java into kotlin

core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/WebViewCallback.kt
Fixes: #3031 
Converted WebViewCallback.java into kotlin
=> Convert WebViewCallback.java into kotlin

core/src/main/java/org/kiwix/kiwixmobile/core/data/local/entity/NetworkLanguageSpec.kt
Fixes: #3003 
Converted NetworkLanguageSpec.java into kotlin
=> Convert NetworkLanguageSpec.java into kotlin

core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixTextToSpeech.kt
=> Removed `TextInputSpeech` memory leak

app/src/androidTest/java/org/kiwix/kiwixmobile/ZimTest.kt
Fixes: #3066 
Converted ZimTest.java into kotlin
=> Convert ZimTest.java into kotlin

buildSrc/src/main/kotlin/Libs.kt, buildSrc/src/main/kotlin/Versions.kt
Fixes: #3073 
Parent Issue: #2816
=> Update KiwixLib to 10.1.1

app/src/main/res/layout/fragment_destination_library.xml, app/src/main/res/values/strings.xml
Fixes #2993 
Change content description of floating button.
=> Change content description in file picker floating button

app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadTest.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt, lintConfig.xml
=> Fix Initial download doesn't happen

app/src/androidTest/java/org/kiwix/kiwixmobile/utils/KiwixIdlingResource.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/TestingUtils.kt
Fixes: #3023 
Converted TestingUtils.java into kotlin and improve KiwixIdlingResource.kt code
=> Convert TestingUtils.java into kotlin

app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/LanguageUtils.kt
Fixes #3088 
The issue is when  we change language UI is not refreshing, so i have implemented ```onConfigurationChanged()``` and refresh UI component.
=> Fix UI is not immediately translated (after changing UI language)

core/src/main/java/org/kiwix/kiwixmobile/core/data/local/entity/RecentSearchSpec.kt
Fixes: #3005
Converted RecentSearchSpec.java into kotlin
=> Convert RecentSearchSpec.java into kotlin

core/src/main/java/org/kiwix/kiwixmobile/core/data/local/entity/BookDataSource.kt
Fixes: #3007 
Converted BookDataSource.java into kotlin
=> Convert BookDataSource.java into kotlin

app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/main/TopLevelDestinationTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/utils/StandardActions.kt
=> Fix nightly workflow is almost always red

core/src/main/java/org/kiwix/kiwixmobile/core/data/local/entity/BookmarksSpec.kt
Fixes: #2999 
Converted BookmarksSpec.java into kotlin
=> Convert BookmarksSpec.java into kotlin

.github/workflows/coverage.yml, app/src/androidTest/java/org/kiwix/kiwixmobile/help/HelpFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/intro/IntroFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/main/TopLevelDestinationTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/settings/KiwixSettingsFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/splash/KiwixSplashActivityTest.kt
=> Introduce android 13 CI in project

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/settings/CorePrefsFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt
=> Fix Storage permission on Android 13

app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/downloader/fetch/FetchDownloadNotificationManager.kt, core/src/main/java/org/kiwix/kiwixmobile/core/settings/CorePrefsFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/LanguageUtils.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt
=> Fixed cancel button translation issue in download notification

app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/utils/RecyclerViewMatcher.kt
=> Added tests cases in LanguageFragmentTest

core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt
=> fixed night mode looks really weird on android

app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/settings/KiwixSettingsFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/settings/SettingsRobot.kt
=> Fixed. Test instrumentation process crashed in ```KiwixSettingsFragmentTest```

app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadRobot.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadTest.kt
=> Fixed sometimes CI fails in InitialDownloadTest

app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageRobot.kt
=> Fixed sometimes CI fails in LanguageFragmentTest

app/build.gradle.kts, app/src/androidTest/java/org/kiwix/kiwixmobile/download/DownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/help/HelpFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/initial/download/InitialDownloadTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/intro/IntroFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/language/LanguageFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/main/TopLevelDestinationTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/note/NoteFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/search/SearchFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/settings/KiwixSettingsFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/splash/KiwixSplashActivityTest.kt, app/src/main/java/org/kiwix/kiwixmobile/webserver/ZimHostFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/webserver/wifi_hotspot/HotspotService.kt, buildSrc/src/main/kotlin/Libs.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/SearchFragment.kt
Fixes #3156 , #3148 , #3154, #2605
=> Remove (CI detected) memory leaks

core/src/main/res/xml/kiwix_widget_provider_info.xml
=> Updated widgets minimum resize width

.github/workflows/coverage.yml, .github/workflows/nightly.yml, .github/workflows/pull_request.yml, buildSrc/src/main/kotlin/plugin/AllProjectConfigurer.kt
=> Removed explicit NDK version from project

.github/workflows/nightly.yml
=> Fixed nightly worflow should only compile and upload APK

.github/workflows/nightly.yml, app/build.gradle.kts, buildSrc/src/main/kotlin/plugin/AppConfigurer.kt
=> Change nightly APK filename

core/src/main/res/layout/activity_kiwix_error.xml
=> fixed the button in the UI which was not consistent

app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt
Fixes #3236 
**What is the problem**
* ```onConfigurationChanged``` method is calling before isInitializing the ```activityKiwixMainBinding```.
**How i fixed this problem**
* I have added a condition on ```activityKiwixMainBinding``` in ```onConfigurationChanged``` method if ```activityKiwixMainBinding``` is ```isInitialized``` then this method code executes.
=> Fixes of Application randomly crash on KiwixMainActivity

app/src/main/java/org/kiwix/kiwixmobile/language/LanguageFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/localFileTransfer/LocalFileTransferFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/LocalLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/PageFragment.kt
Google has deprecated the setHasOptionsMenu(true) in  early 2022 and we have new better API to handle menu 
Fixes #3245
I have replaced the deprecated method with new API which makes the flow more fluent
Tested on OnePlus Nord CE
=> replaced the deprecated setHasOptionsMenu(true) with new API

.github/workflows/pull_request.yml, .github/workflows/release.yml
Fixes #3283 
We have upgraded ubuntu version from ```18.04``` to ```22.04```
=> Upgraded ubuntu version in pull_request.yml

app/src/androidTest/java/org/kiwix/kiwixmobile/reader/KiwixReaderFragmentTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/reader/ReaderRobot.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/res/values/strings.xml
Fixes #3249 
Added "Tabs Closed" dialog with Undo action for preventing accidental closing of all tabs.
[device-2023-03-01-155753.webm](https://user-images.githubusercontent.com/85388413/222113471-246d7cc9-6adf-428f-928b-0197f8a6a3bc.webm)
=> Added "Tabs Closed" Dialog

buildSrc/src/main/kotlin/custom/Auth.kt
=> Fixes of error in uploading custom apps on play store

CHANGELOG, app/build.gradle.kts, core/build.gradle.kts
=> Updating change log for 3.7.0 release

custom/build.gradle.kts
=> Updated language split for each apk in the bundle

app/src/main/AndroidManifest.xml, core/src/main/AndroidManifest.xml
=> Removed package permission from core to app package

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt
Fixes #3309 
* We are currently using the deprecated method `conManager.activeNetworkInfo?.isConnected` to check network connectivity. However, starting from Android 23 and above, this method fails to accurately detect the absence of an internet connection. As a result, our condition to prevent loading content when the internet is not available is being bypassed. Consequently, an error message stating `No items available` is displayed because we are unable to fetch the content without an internet connection. https://github.com/kiwix/kiwix-android/blob/ce423820f0b2aee20cdd69e064095ba4db24b4a2/app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt#L337
* The snack bar is not displaying when attempting to download the zim file without …
=> Fixed online content(Zim files) are removed if there is no internet connection

core/src/main/java/org/kiwix/kiwixmobile/core/search/SearchFragment.kt
Fixes #3374 
**Fix**
* We were using the deprecated method to inflate the menu, now we have refactored the deprecated method.
* The search menu does not appear when clicking on the search option in the custom app. This issue arises because we set the toolbar in our `onCreateView`, which causes it to be treated as if it's in the background. As a result, it is not recognized. To resolve this problem, we utilized the post method of the view class to explicitly indicate that we are executing this on the main thread. After implementing this approach, the search menu now correctly appears when clicking on the search icon.
=> Fixed Search edit text is not showing in custom apps

app/src/main/java/org/kiwix/kiwixmobile/webserver/ZimHostFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/base/BaseFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/help/HelpFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/PageFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/settings/CoreSettingsFragment.kt
Fixes #3395 
Moved the common toolbar functionality to the BaseFragment to avoid duplicity.
=> Fixes of Refactor the Toolbar functionality

app/src/main/java/org/kiwix/kiwixmobile/intro/CustomPageIndicator.kt, app/src/main/java/org/kiwix/kiwixmobile/language/viewmodel/LanguageViewModel.kt, app/src/main/java/org/kiwix/kiwixmobile/localFileTransfer/SenderDevice.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/OnlineLibraryFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/settings/KiwixPrefsFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModel.kt, core/src/main/java/org/kiwix/kiwixmobile/core/CoreApp.kt, core/src/main/java/org/kiwix/kiwixmobile/core/base/BasePresenter.kt, core/src/main/java/org/kiwix/kiwixmobile/core/base/adapter/AdapterDelegateManager.kt, core/src/main/java/org/kiwix/kiwixmobile/core/dao/NewBookDao.kt, core/src/main/java/org/kiwix/kiwixmobile/core/di/modules/DatabaseModule.kt, core/src/main/java/org/kiwix/kiwixmobile/core/downloader/DownloaderImpl.kt, core/src/main/java/org/kiwix/kiwixmobile/core/error/ErrorActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/help/HelpFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/page/viewmodel/PageViewModel.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/RateDialogHandler.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/download/CustomDownloadFragment.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/download/CustomDownloadViewModel.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomReaderFragment.kt
Fixes #3446 
* Fixed UnnecessaryAbstractClass issue of detekt
* Fixed the UnsafeCallOnNullableType detekt issue in the project.
=> Fixes of `UnsafeCallOnNullableType` and `UnnecessaryAbstractClass` issues found by detekt

custom/build.gradle.kts
=> Updated the asset folder naming

CHANGELOG
=> Updated CHANGELOG file to show the changes made in the version `3.8.0`.

buildSrc/src/main/kotlin/Config.kt
=> Updated kiwix version to 3.8.1

.github/workflows/release.yml
=> Fixes #3569

buildSrc/src/main/kotlin/Config.kt
=> Updated kiwix version to `3.9.0`.

CHANGELOG
=> Updated `CHANGELOG` for `3.9.0`.

CHANGELOG
=> Added a small change in the CHANGELOG for `3.9.0`.

CHANGELOG, buildSrc/src/main/kotlin/Config.kt
=> Release 3.9.1

gradle.properties
=> Fixes custom app wikimed bundle build problem 

core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ViewExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
Fixes #3673
Other places:
Bookmark:
=> #3673 Added color Independent snack function

core/src/main/java/org/kiwix/kiwixmobile/core/main/AddNoteDialog.kt
Fixes #3682 
* Now, the user can view the notes even if the ZIM file does not exist. However, they cannot edit the note since the corresponding ZIM file is not present. Nevertheless, the user can still share and delete that note.
* Removed the `closeKeyboard()` method from `onFailureToCreateAddNoteDialog()` because we are calling this in our `onCreate` method and the dialog is not visible right now and this method requires the view, so it is throwing an error `this was called before onCreateView()`.
https://github.com/kiwix/kiwix-android/assets/34593983/903fe633-9932-4120-a7eb-d0b314f6e331
=> Fixed: The application crashes when attempting to open saved notes in the absence of the ZIM file.

app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt
=> #3675 Notification Navigation to KiwixReaderFragment

core/src/main/res/values/strings.xml
Parent Issue #3555 
Fixed some `TypographyQuotes` errors in our main English version.
=> Fixed some `TypographyQuotes` errors in our main English version.

buildSrc/src/main/kotlin/Config.kt
=> Updated kiwix version to `3.10.0`.

CHANGELOG
Parent Fixes #3685
Added the changes in the `CHANGELOG` file that we have made in milestone `3.10.0`.
=> Updated CHANGELOG file for `3.10.0`.

.github/workflows/ci.yml
=> Add CODECOV_TOKEN

CHANGELOG
Parent Issue #3685
Updated the `CHANGELOG` file since we have fix some bugs and added some improvements in milestone `3.10.0` that should be documented in the `CHANGELOG` file.
=> Updated `CHANGELOG` file

CHANGELOG
Updated the CHANGELOG file for `3.10.1`.
=> Updated the CHANGELOG file for `3.10.1`.

buildSrc/src/main/kotlin/Config.kt
Updated kiwix version to `3.10.1`.
=> Updated kiwix version to `3.10.1`.

CHANGELOG
* We have fixed some issues in this milestone which should be mentioned in the `CHANGELOG` file so we have added them in the `CHANGELOG` file.
=> Updated the CHANGELOG file for version `3.10.1`.

buildSrc/src/main/kotlin/Config.kt
=> Upgraded the kiwix version to `3.11.0`.

CHANGELOG
=> Updated the CHANGELOG file for `3.11.0`.

buildSrc/src/main/kotlin/Config.kt
=> Upgraded the kiwix version to 3.11.1

CHANGELOG
=> Updated CHANGELOG file to show the changes made in milestone `3.11.1`.

buildSrc/src/main/kotlin/Versions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/search/viewmodel/SearchState.kt
=> Use java-libkiwix 2.2.1

core/src/main/java/org/kiwix/kiwixmobile/core/utils/dialog/RateDialogHandler.kt
Fixes #3963 
Now, it asks for an evaluation when the user has opened the application at least 20 times, has been using the application for the past two weeks, and has one or more ZIM files in their library.
=> Changed the criteria for requesting a Google Play Store evaluation.

app/src/main/java/org/kiwix/kiwixmobile/zimManager/libraryView/adapter/LibraryViewHolder.kt
=> minor improvements on shouldEnablePauseResumeButton

buildSrc/src/main/kotlin/Versions.kt
=> Use java-libkiwix 2.2.2

core/src/main/java/org/kiwix/kiwixmobile/core/utils/DonationDialogHandler.kt, core/src/test/java/org/kiwix/kiwixmobile/core/utils/DonationDialogHandlerTest.kt
Fixes #3736 
* Improved the showing of the donation popup. Previously it immediately showed when there is a ZIM file available in the application, but now it will only show the donation popup after 3 months of installation of the application.
* If someone clicks on the "Later" button then the donation popup will show after 3 months of the current date. Previously, if a user clicked on the donation popup, it was showing after 3 days.
* Added the test cases for this functionality.
=> Improved donation popup schedule

app/src/main/java/org/kiwix/kiwixmobile/main/KiwixMainActivity.kt
Fixes #4078 
Handled Notification Intent in oncreate which fixes the issue
https://github.com/user-attachments/assets/93a2ae73-72d8-4899-812e-90c57c0561ce
=> Fixed: zim file not opening from notification issue

buildSrc/src/main/kotlin/Config.kt
=> Upgraded the kiwix version to `3.12.0`

README.md
=> Added IzzyOnDroid badge and link in README file instead of F-droid badge and link.

CHANGELOG
=> Updated `CHANGELOG` file to show the changes made in milestone `3.12.0`.

CHANGELOG
=> Minor fixes are added in the `CHANGELOG` file for milestone `3.12.0`.

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModel.kt, core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/DownloadManagerMonitor.kt, core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/DownloadMonitorService.kt, core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ActivityExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/extensions/ContextExtensions.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreMainActivity.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, custom/src/main/java/org/kiwix/kiwixmobile/custom/main/CustomMainActivity.kt
Fixes #4113 
Fixes #4106
* Updating the UI correctly when there is an error while creating the KiwiService (especially when it fails to connect with the server).
* Fixed: The downloading always shows "In Progress", and shows it is not started for large files because the progress was not showing.
* Fixed: The download progress sometimes stopped when resuming a download, as the Download Manager took some time to update the status. Meanwhile, the foreground service stopped due to no active downloads being detected. This issue has been resolved to ensure proper tracking of active download progress.
Apk for testing this PR code https://drive.google.com/file/d/1x4aIJ7BlYBAfzEH_KtxhWxmiSg83vJYm/view?usp=sharing
=> Fixed: Impossible to download full Wikipedia in English.

README.md, app/src/main/assets/credits.html, custom/src/main/assets/credits.html
* Removed the `ButterKnife` from the README file as we are not using this library in our project anymore.
* Also removed this library from the `credits.html` of both the app and custom modules.
=> Removed the `ButterKnife` from the README file as we are not using this library in our project anymore.

CHANGELOG
Parent Issue https://github.com/kiwix/kiwix-android/issues/4137
=> Updated the CHANGELOG file to show changes made in milestone `.3.13.0`.

core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/DownloadMonitorService.kt
* Fixed an issue where the notification for a completed download would disappear when the same notification ID was used for the foreground service.
* Enhanced the cancellation logic to immediately remove the ongoing download notification when the user cancels a download and no other downloads are active. This resolves the delay (2-3 seconds) that occurred when the notification was set as the foreground notification.
* Added the necessary comments in methods to understand this fix.
**Issue**
https://github.com/user-attachments/assets/bf9a50d1-5e70-4600-8b9c-98daefe9b4a0
**Fix**
https://github.com/user-attachments/assets/099a1347-21e4-45f1-989c-f1eab8ccb1ae
=> Improved handling of completed and canceled download notifications(When app is in background or closed).

buildSrc/src/main/kotlin/Config.kt
=> Upgraded the kiwix version to `3.14.0`.

CHANGELOG
=> Updated the `CHANGELOG` file to include the remaining changes made in milestone `3.14.0`.

.github/workflows/release.yml
Fixes #4226 
Now, only APK files will be uploaded in the release.
=> Removed the uploading of unnecessary files in the release.

core/src/main/java/org/kiwix/kiwixmobile/core/downloader/downloadManager/FetchDownloadNotificationManager.kt
Fixes #4278 
* The issue occurred when the user paused a download from the notification while the application was in the background and only a single download was active. At that point, a paused notification was posted on the IO thread to inform the user, and shortly after, the same notification was set on the foreground service. Due to a timing conflict, both notifications were being processed simultaneously, leading to a crash.
* To fix this, a synchronization lock is added inside the `getCancelNotification` method to ensure that only one thread can access the notification builder at a time.
=> Fixed: Application crashes on `FetchDownloadNotificationManager.getCancelNotification` method.

core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt
Fixes #4282 
* Moved the download logic to the IO thread to prevent blocking the main thread.
* Also refactored the code structure slightly to reduce nesting and resolve the `NestedBlockDepth` lint warning.
=> Fixed: `Input dispatching timed out` error while downloading files from ZIM files.

custom/src/main/java/org/kiwix/kiwixmobile/custom/download/CustomDownloadFragment.kt
Fixes #4280 
* The issue occurred because the notification permission was not granted. On Android 13 and above, notifications won't appear without this permission.
* To fix this, we now properly request notification permission on devices running Android 13 and above.
https://github.com/user-attachments/assets/e943ce74-bbc2-4785-974e-9210ec657ed5
=> Fixed: Notification not showing when downloading ZIM files in custom apps.

core/src/main/java/org/kiwix/kiwixmobile/core/dao/WebViewHistoryRoomDao.kt, core/src/main/java/org/kiwix/kiwixmobile/core/data/DataSource.kt, core/src/main/java/org/kiwix/kiwixmobile/core/data/Repository.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/MainRepositoryActions.kt
Fixes #4309 
Refactored the code to use the coroutine flow instead of `RxJava` flowable.
=> Refactored the `RxJava` to coroutines in retrieving the webView history.

app/src/androidTest/java/org/kiwix/kiwixmobile/ObjectBoxToLibkiwixMigratorTest.kt, app/src/androidTest/java/org/kiwix/kiwixmobile/page/bookmarks/ImportBookmarkTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/dao/LibkiwixBookmarks.kt, core/src/main/java/org/kiwix/kiwixmobile/core/data/DataSource.kt, core/src/main/java/org/kiwix/kiwixmobile/core/data/Repository.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/MainRepositoryActions.kt, core/src/test/java/org/kiwix/kiwixmobile/core/page/bookmark/viewmodel/BookmarkViewModelTest.kt
Fixes #4304 
* Refactored the code to use coroutines instead of `RxJava` for saving/retrieving the bookmarks from libkiwix.
* Refactored all the unit and UI test cases according to it.
=> Refactored the code to use coroutines instead of rxJava for saving/retrieving the bookmarks from libkiwix.

core/src/main/java/org/kiwix/kiwixmobile/core/reader/ZimFileReader.kt
Fixes #4310 
* Migrated ZIM content loading logic from RxJava to Kotlin coroutines.
* The previous implementation used `RxJava` to stream content on the IO thread, but it was not lifecycle-aware. This caused the task to continue running even when the WebView navigated away or stopped rendering.
* Updated the implementation to use coroutines, ensuring that the task is lifecycle-aware and automatically cancels when the page changes or the user navigates away.
* This improves resource efficiency and prevents unnecessary background work during page transitions.
https://github.com/user-attachments/assets/9f53efe5-a17f-45b0-8fa5-87aef6b5e457
=> Refactored `RxJava` to `coroutines` in `ZimFileReader`.

app/src/main/java/org/kiwix/kiwixmobile/nav/destination/library/CopyMoveFileHandler.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/Fat32Checker.kt, app/src/main/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModel.kt, app/src/test/java/org/kiwix/kiwixmobile/localLibrary/CopyMoveFileHandlerTest.kt, app/src/test/java/org/kiwix/kiwixmobile/zimManager/ZimManageViewModelTest.kt, core/src/main/java/org/kiwix/kiwixmobile/core/DarkModeConfig.kt, core/src/main/java/org/kiwix/kiwixmobile/core/main/KiwixWebView.kt, core/src/main/java/org/kiwix/kiwixmobile/core/utils/SharedPreferenceUtil.kt, core/src/test/java/org/kiwix/kiwixmobile/core/DarkModeConfigTest.kt
Fixes #4307 
Fixes #4318
* Refactored all `RxJava` code in `SharedPreferenceUtil` to coroutines.
* Refactored `RxJava` code to coroutines in `Fat32Checker`.
* Refactored `RxJava` code to coroutines in `DarkModeConfig`.
* Refactored all related code of these classes accordingly.
* Updated unit test cases to work with coroutines.
=> Refactored RxJava to coroutines in Fat32Checker, and `SharedPreferenceUtil`.

core/src/main/res/values/strings.xml
=> Changed "ip" as "IP" in our string file.

core/src/main/res/values-ar/strings.xml, core/src/main/res/values-da/strings.xml, core/src/main/res/values-de/strings.xml, core/src/main/res/values-fr/strings.xml, core/src/main/res/values-hi/strings.xml, core/src/main/res/values-hu/strings.xml, core/src/main/res/values-ia/strings.xml, core/src/main/res/values-in/strings.xml, core/src/main/res/values-it/strings.xml, core/src/main/res/values-iw/strings.xml, core/src/main/res/values-kg/strings.xml, core/src/main/res/values-ko/strings.xml, core/src/main/res/values-lb/strings.xml, core/src/main/res/values-ln/strings.xml, core/src/main/res/values-mk/strings.xml, core/src/main/res/values-nl/strings.xml, core/src/main/res/values-pl/strings.xml, core/src/main/res/values-pt-rBR/strings.xml, core/src/main/res/values-pt/strings.xml, core/src/main/res/values-ro/strings.xml, core/src/main/res/values-ru/strings.xml, core/src/main/res/values-skr/strings.xml, core/src/main/res/values-zh-rTW/strings.xml, core/src/main/res/values-zh/strings.xml, core/src/main/res/values/strings.xml
=> Improved the "Downloading" section title on the download screen.
